// generated by newgenasym  Tue Mar 29 11:56:58 2011


module conn10t (a1, a10, a2, a3, a4, a5, a6, a7, a8, a9);
    inout a1;
    inout a10;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;


    initial
        begin
        end

endmodule
