-- generated by newgenasym Tue Mar 29 12:00:33 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MIC2937A12 is
    port (    
	GROUND:    INOUT  STD_LOGIC;    
	INPUT:     IN     STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC);
end MIC2937A12;
