`timescale 1ns/1ns

module base_mon ();
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:24 2015
// from tubii_lib/BASE_MON/sch_1

  // global signal glbl.vcc;
  // global signal glbl.vcc5m;

  wire  unnamed_1_csmd0805_i10_a;
  wire  unnamed_1_csmd0805_i11_a;
  wire  unnamed_1_csmd0805_i6_a;
  wire  unnamed_1_csmd0805_i7_a;
  wire  unnamed_1_csmd0805_i8_a;
  wire  unnamed_1_csmd0805_i9_a;
  wire  unnamed_1_idsc10_i1_pin1;
  wire  unnamed_1_idsc10_i1_pin10;
  wire  unnamed_1_idsc10_i1_pin2;
  wire  unnamed_1_idsc10_i1_pin3;
  wire  unnamed_1_idsc10_i1_pin4;
  wire  unnamed_1_idsc10_i1_pin5;
  wire  unnamed_1_idsc10_i1_pin6;
  wire  unnamed_1_idsc10_i1_pin7;
  wire  unnamed_1_idsc10_i1_pin8;
  wire  unnamed_1_idsc10_i1_pin9;
  wire  unnamed_1_idsc10_i2_pin1;
  wire  unnamed_1_idsc10_i2_pin10;
  wire  unnamed_1_idsc10_i2_pin2;
  wire  unnamed_1_idsc10_i2_pin3;
  wire  unnamed_1_idsc10_i2_pin4;
  wire  unnamed_1_idsc10_i2_pin5;
  wire  unnamed_1_idsc10_i2_pin6;
  wire  unnamed_1_idsc10_i2_pin7;
  wire  unnamed_1_idsc10_i2_pin8;
  wire  unnamed_1_idsc10_i2_pin9;

  wire  vcc;
  wire  page1_vcc;
  wire  vcc5m;
  wire  page1_vcc5m;

  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vcc5m = glbl.vcc5m;
  assign page1_vcc5m = vcc5m;

// begin instances 

  ids_c10 page1_i1  (.pin1(unnamed_1_idsc10_i1_pin1),
	.pin2(unnamed_1_idsc10_i1_pin2),
	.pin3(unnamed_1_idsc10_i1_pin3),
	.pin4(unnamed_1_idsc10_i1_pin4),
	.pin5(unnamed_1_idsc10_i1_pin5),
	.pin6(unnamed_1_idsc10_i1_pin6),
	.pin7(unnamed_1_idsc10_i1_pin7),
	.pin8(unnamed_1_idsc10_i1_pin8),
	.pin9(unnamed_1_idsc10_i1_pin9),
	.pin10(unnamed_1_idsc10_i1_pin10));

  ids_c10 page1_i2  (.pin1(unnamed_1_idsc10_i2_pin1),
	.pin2(unnamed_1_idsc10_i2_pin2),
	.pin3(unnamed_1_idsc10_i2_pin3),
	.pin4(unnamed_1_idsc10_i2_pin4),
	.pin5(unnamed_1_idsc10_i2_pin5),
	.pin6(unnamed_1_idsc10_i2_pin6),
	.pin7(unnamed_1_idsc10_i2_pin7),
	.pin8(unnamed_1_idsc10_i2_pin8),
	.pin9(unnamed_1_idsc10_i2_pin9),
	.pin10(unnamed_1_idsc10_i2_pin10));

  opa4277 page1_i3  (.\+in_a (unnamed_1_idsc10_i1_pin1),
	.\+in_b (unnamed_1_idsc10_i1_pin2),
	.\+in_c (unnamed_1_idsc10_i1_pin3),
	.\+in_d (unnamed_1_idsc10_i1_pin4),
	.\-in_a (unnamed_1_idsc10_i2_pin1),
	.\-in_b (unnamed_1_idsc10_i2_pin2),
	.\-in_c (unnamed_1_idsc10_i2_pin3),
	.\-in_d (unnamed_1_idsc10_i2_pin4),
	.out_a(unnamed_1_idsc10_i2_pin1),
	.out_b(unnamed_1_idsc10_i2_pin2),
	.out_c(unnamed_1_idsc10_i2_pin3),
	.out_d(unnamed_1_idsc10_i2_pin4),
	.\v+ (unnamed_1_csmd0805_i6_a),
	.\v- (unnamed_1_csmd0805_i7_a));

  opa4277 page1_i4  (.\+in_a (unnamed_1_idsc10_i1_pin6),
	.\+in_b (unnamed_1_idsc10_i1_pin7),
	.\+in_c (unnamed_1_idsc10_i1_pin8),
	.\+in_d (unnamed_1_idsc10_i1_pin9),
	.\-in_a (unnamed_1_idsc10_i2_pin6),
	.\-in_b (unnamed_1_idsc10_i2_pin6),
	.\-in_c (unnamed_1_idsc10_i2_pin8),
	.\-in_d (unnamed_1_idsc10_i2_pin9),
	.out_a(unnamed_1_idsc10_i2_pin6),
	.out_b(unnamed_1_idsc10_i2_pin7),
	.out_c(unnamed_1_idsc10_i2_pin8),
	.out_d(unnamed_1_idsc10_i2_pin9),
	.\v+ (unnamed_1_csmd0805_i8_a),
	.\v- (unnamed_1_csmd0805_i9_a));

  opa2277 page1_i5  (.\+in_a (unnamed_1_idsc10_i1_pin10),
	.\+in_b (unnamed_1_idsc10_i1_pin5),
	.\-in_a (unnamed_1_idsc10_i2_pin10),
	.\-in_b (unnamed_1_idsc10_i2_pin5),
	.out_a(unnamed_1_idsc10_i2_pin10),
	.out_b(unnamed_1_idsc10_i2_pin5),
	.\v+ (unnamed_1_csmd0805_i10_a),
	.\v- (unnamed_1_csmd0805_i11_a));

  csmd0805 page1_i6  (.a(unnamed_1_csmd0805_i6_a),
	.b({glbl.vcc}));

  csmd0805 page1_i7  (.a(unnamed_1_csmd0805_i7_a),
	.b({glbl.vcc5m}));

  csmd0805 page1_i8  (.a(unnamed_1_csmd0805_i8_a),
	.b({glbl.vcc}));

  csmd0805 page1_i9  (.a(unnamed_1_csmd0805_i9_a),
	.b({glbl.vcc5m}));

  csmd0805 page1_i10  (.a(unnamed_1_csmd0805_i10_a),
	.b({glbl.vcc}));

  csmd0805 page1_i11  (.a(unnamed_1_csmd0805_i11_a),
	.b({glbl.vcc5m}));

endmodule // base_mon(sch_1) 
