// generated by newgenasym  Wed Oct 01 15:10:42 2014


module \ecl-lvds  (ecl_in_bnc, ecl_in_smb, lvds_out);
    input ecl_in_bnc;
    input ecl_in_smb;
    output lvds_out;


    initial
        begin
        end

endmodule
