-- generated by newgenasym Tue Oct 14 18:35:37 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ecl-lvds\ is
    port (    
	ECL_IN:    IN     STD_LOGIC;    
	LVDS_OUT:  OUT    STD_LOGIC);
end \ecl-lvds\;
