// generated by newgenasym  Tue Mar 29 11:59:44 2011


module \10h604  (clk, \clk* , d, mr, q, \q* , ref, tclk);
    parameter    size = 1;
    input clk;
    input \clk* ;
    input [size-1:0] d;
    input mr;
    output [size-1:0] q;
    output [size-1:0] \q* ;
    output ref;
    input tclk;


    initial
        begin
        end

endmodule
