// generated by newgenasym  Tue Mar 29 11:57:20 2011


module dg506a_l (a, d, en, s1, s10, s11, s12, s13, s14, s15, s16, s2, s3, s4, s5, s6,
        s7, s8, s9, \v+ , \v- );
    parameter    size = 1;
    input [3:0] a;
    inout [size-1:0] d;
    input en;
    inout [size-1:0] s1;
    inout [size-1:0] s10;
    inout [size-1:0] s11;
    inout [size-1:0] s12;
    inout [size-1:0] s13;
    inout [size-1:0] s14;
    inout [size-1:0] s15;
    inout [size-1:0] s16;
    inout [size-1:0] s2;
    inout [size-1:0] s3;
    inout [size-1:0] s4;
    inout [size-1:0] s5;
    inout [size-1:0] s6;
    inout [size-1:0] s7;
    inout [size-1:0] s8;
    inout [size-1:0] s9;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
