-- generated by newgenasym Tue Mar 29 11:57:20 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DG506A_L is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	D:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	EN:        IN     STD_LOGIC;    
	S1:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S10:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S11:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S12:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S13:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S14:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S15:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S16:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S2:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S3:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S4:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S5:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S6:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S7:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S8:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S9:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end DG506A_L;
