// generated by newgenasym  Wed Jun 22 12:19:45 2011


module prescaletrig (prescaletrigs, rawtrigs);
    input [3:0] prescaletrigs;
    output [3:0] rawtrigs;


    initial
        begin
        end

endmodule
