-- generated by newgenasym Wed Jun 22 12:19:45 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PRESCALETRIG is
    port (    
	PRESCALETRIGS: IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	RAWTRIGS:  OUT    STD_LOGIC_VECTOR (3 DOWNTO 0));
end PRESCALETRIG;
