// generated by newgenasym  Tue Mar 29 12:00:23 2011


module connj96 (a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20,
        a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a4,
        a5, a6, a7, a8, a9, b1, b10, b11, b12, b13, b14, b15, b16, b17, b18,
        b19, b2, b20, b21, b22, b23, b24, b25, b26, b27, b28, b29, b3, b30,
        b31, b32, b4, b5, b6, b7, b8, b9, c1, c10, c11, c12, c13, c14, c15,
        c16, c17, c18, c19, c2, c20, c21, c22, c23, c24, c25, c26, c27,
        c28, c29, c3, c30, c31, c32, c4, c5, c6, c7, c8, c9);
    output a1;
    output a10;
    output a11;
    output a12;
    output a13;
    output a14;
    output a15;
    output a16;
    output a17;
    output a18;
    output a19;
    inout a2;
    output a20;
    output a21;
    output a22;
    output a23;
    output a24;
    output a25;
    output a26;
    output a27;
    output a28;
    output a29;
    output a3;
    output a30;
    output a31;
    output a32;
    output a4;
    output a5;
    output a6;
    output a7;
    output a8;
    output a9;
    output b1;
    output b10;
    output b11;
    output b12;
    output b13;
    output b14;
    output b15;
    output b16;
    output b17;
    output b18;
    output b19;
    output b2;
    output b20;
    output b21;
    output b22;
    output b23;
    output b24;
    output b25;
    output b26;
    output b27;
    output b28;
    output b29;
    output b3;
    output b30;
    output b31;
    output b32;
    output b4;
    output b5;
    output b6;
    output b7;
    output b8;
    output b9;
    output c1;
    output c10;
    output c11;
    output c12;
    output c13;
    output c14;
    output c15;
    output c16;
    output c17;
    output c18;
    output c19;
    output c2;
    output c20;
    output c21;
    output c22;
    output c23;
    output c24;
    output c25;
    output c26;
    output c27;
    output c28;
    output c29;
    output c3;
    output c30;
    output c31;
    output c32;
    output c4;
    output c5;
    output c6;
    output c7;
    output c8;
    output c9;


    initial
        begin
        end

endmodule
