// generated by newgenasym  Tue Mar 29 11:57:06 2011


module conn32 (p1, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p2, p20,
        p21, p22, p23, p24, p25, p26, p27, p28, p29, p3, p30, p31, p32, p4,
        p5, p6, p7, p8, p9);
    output p1;
    output p10;
    output p11;
    output p12;
    output p13;
    output p14;
    output p15;
    output p16;
    output p17;
    output p18;
    output p19;
    output p2;
    output p20;
    output p21;
    output p22;
    output p23;
    output p24;
    output p25;
    output p26;
    output p27;
    output p28;
    output p29;
    output p3;
    output p30;
    output p31;
    output p32;
    output p4;
    output p5;
    output p6;
    output p7;
    output p8;
    output p9;


    initial
        begin
        end

endmodule
