// generated by newgenasym  Tue Aug 19 11:28:26 2014


module coto2342 (ctrl_in, ctrl_out, in1, in2, nc1, nc2, no1, no2);
    inout ctrl_in;
    inout ctrl_out;
    inout in1;
    inout in2;
    inout nc1;
    inout nc2;
    inout no1;
    inout no2;


    initial
        begin
        end

endmodule
