// generated by newgenasym  Tue Mar 29 11:58:37 2011


module relaysz (s1, s2, vin, vout);
    parameter    size = 1;
    input [size-1:0] s1;
    input [size-1:0] s2;
    inout [size-1:0] vin;
    inout [size-1:0] vout;


    initial
        begin
        end

endmodule
