// generated by newgenasym  Tue Mar 29 12:00:33 2011


module mic2937a12 (ground, \input , \output );
    inout ground;
    input \input ;
    output \output ;


    initial
        begin
        end

endmodule
