-- generated by newgenasym Tue Mar 29 11:56:45 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ADOP177G_L is
    port (    
	NIN:       INOUT  STD_LOGIC;    
	NVSS:      IN     STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	PIN:       INOUT  STD_LOGIC;    
	PVSS:      IN     STD_LOGIC);
end ADOP177G_L;
