-- generated by newgenasym Tue Mar 29 11:59:21 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity XC1736 is
    port (    
	\ce*\:     IN     STD_LOGIC;    
	\ceo*\:    OUT    STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	D:         OUT    STD_LOGIC;    
	\rsoe*\:   IN     STD_LOGIC);
end XC1736;
