-- generated by newgenasym Tue Mar 29 11:59:12 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity UPF1764 is
    port (    
	CA0:       IN     STD_LOGIC;    
	CA1:       IN     STD_LOGIC;    
	CA2:       IN     STD_LOGIC;    
	CA3:       IN     STD_LOGIC;    
	CA4:       IN     STD_LOGIC;    
	CA5:       IN     STD_LOGIC;    
	CA6:       IN     STD_LOGIC;    
	CA7:       IN     STD_LOGIC;    
	CA8:       IN     STD_LOGIC;    
	CA9:       IN     STD_LOGIC;    
	\casen*\:  IN     STD_LOGIC;    
	CP:        IN     STD_LOGIC;    
	DTACK:     IN     STD_LOGIC;    
	GNT:       IN     STD_LOGIC;    
	MA0:       OUT    STD_LOGIC;    
	MA1:       OUT    STD_LOGIC;    
	MA2:       OUT    STD_LOGIC;    
	MA3:       OUT    STD_LOGIC;    
	MA4:       OUT    STD_LOGIC;    
	MA5:       OUT    STD_LOGIC;    
	MA6:       OUT    STD_LOGIC;    
	MA7:       OUT    STD_LOGIC;    
	MA8:       OUT    STD_LOGIC;    
	MA9:       OUT    STD_LOGIC;    
	RA0:       IN     STD_LOGIC;    
	RA1:       IN     STD_LOGIC;    
	RA2:       IN     STD_LOGIC;    
	RA3:       IN     STD_LOGIC;    
	RA4:       IN     STD_LOGIC;    
	RA5:       IN     STD_LOGIC;    
	RA6:       IN     STD_LOGIC;    
	RA7:       IN     STD_LOGIC;    
	RA8:       IN     STD_LOGIC;    
	RA9:       IN     STD_LOGIC;    
	\ras*\:    IN     STD_LOGIC;    
	RCP:       IN     STD_LOGIC;    
	\req1*\:   IN     STD_LOGIC;    
	\req2*\:   IN     STD_LOGIC;    
	\sel1*\:   INOUT  STD_LOGIC;    
	\sel2*\:   INOUT  STD_LOGIC;    
	WG:        IN     STD_LOGIC);
end UPF1764;
