// generated by newgenasym  Tue Mar 29 11:59:34 2011


module \10el34  (clk, \clk* , \en* , mr, q0, \q0* , q1, \q1* , q2, \q2* , vbb);
    input clk;
    input \clk* ;
    input \en* ;
    input mr;
    output q0;
    output \q0* ;
    output q1;
    output \q1* ;
    output q2;
    output \q2* ;
    output vbb;


    initial
        begin
        end

endmodule
