-- generated by newgenasym Tue Mar 29 11:58:18 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MC7805K_L is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC;    
	REF:       INOUT  STD_LOGIC);
end MC7805K_L;
