// generated by newgenasym  Mon Oct 13 18:03:19 2014


module comparators (clk, data, data_rdy, dgth, dgtl, fast_comp_outh,
        fast_comp_outl, fast_pulse, le_tune, lockout, \lockout* ,
        tune_comp_outh, tune_comp_outl, tune_pulse);
    input clk;
    input data;
    input data_rdy;
    output dgth;
    output dgtl;
    output fast_comp_outh;
    output fast_comp_outl;
    inout fast_pulse;
    input le_tune;
    output lockout;
    output \lockout* ;
    output tune_comp_outh;
    output tune_comp_outl;
    inout tune_pulse;


    initial
        begin
        end

endmodule
