// generated by newgenasym  Wed Feb 25 10:35:04 2015


module comparators (clk, data, data_rdy, dgth, fast_comp_out_n,
        fast_comp_out_p, fast_pulse, gtrig, le_tune, \lockout* ,
        tune_comp_out_n, tune_comp_out_p, tune_pulse);
    input clk;
    input data;
    input data_rdy;
    output dgth;
    output fast_comp_out_n;
    output fast_comp_out_p;
    inout fast_pulse;
    output gtrig;
    input le_tune;
    output \lockout* ;
    output tune_comp_out_n;
    output tune_comp_out_p;
    inout tune_pulse;


    initial
        begin
        end

endmodule
