// generated by newgenasym  Mon Oct 20 11:26:45 2014


module comparators (clk, data, data_rdy, dgth, fast_comp_outh, fast_comp_outl,
        fast_pulse, gtrig, le_tune, \lockout* , tune_comp_outh,
        tune_comp_outl, tune_pulse);
    input clk;
    input data;
    input data_rdy;
    output dgth;
    output fast_comp_outh;
    output fast_comp_outl;
    inout fast_pulse;
    output gtrig;
    input le_tune;
    output \lockout* ;
    output tune_comp_outh;
    output tune_comp_outl;
    inout tune_pulse;


    initial
        begin
        end

endmodule
