-- generated by newgenasym Thu Oct 02 11:24:08 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity comparators is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	DGTH:      INOUT  STD_LOGIC;    
	DGTL:      INOUT  STD_LOGIC;    
	FAST_COMP_OUTH: INOUT  STD_LOGIC;    
	FAST_COMP_OUTL: INOUT  STD_LOGIC;    
	FAST_PULSE: INOUT  STD_LOGIC;    
	LE_TUNE:   IN     STD_LOGIC;    
	LOCKOUT:   INOUT  STD_LOGIC;    
	\lockout*\: INOUT  STD_LOGIC;    
	TUNE_COMP_OUTH: INOUT  STD_LOGIC;    
	TUNE_COMP_OUTL: INOUT  STD_LOGIC;    
	TUNE_PULSE: INOUT  STD_LOGIC);
end comparators;
