// generated by newgenasym  Wed Oct 01 11:18:39 2014


module pot (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
