-- generated by newgenasym Wed Oct 01 11:18:39 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pot is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end pot;
