`timescale 1ns/1ns

module latchexttrig (exttrig );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:11 2015
// from tubii_lib/LATCHEXTTRIG/sch_1

  inout [15:0] exttrig;
  // global signal glbl.gnd;
  // global signal glbl.vcc;
  // global signal glbl.vtt;

  wire  unnamed_1_10e116_i101_a;
  wire  unnamed_1_10e116_i101_b;
  wire  unnamed_1_10e116_i101_y;
  wire  unnamed_1_10e116_i101_y_1;
  wire  unnamed_1_10e116_i109_a;
  wire  unnamed_1_10e116_i109_b;
  wire  unnamed_1_10e116_i109_y;
  wire  unnamed_1_10e116_i109_y_1;
  wire  unnamed_1_10e116_i117_a;
  wire  unnamed_1_10e116_i117_b;
  wire  unnamed_1_10e116_i117_y;
  wire  unnamed_1_10e116_i117_y_1;
  wire  unnamed_1_10e116_i125_a;
  wire  unnamed_1_10e116_i125_b;
  wire  unnamed_1_10e116_i125_y;
  wire  unnamed_1_10e116_i125_y_1;
  wire  unnamed_1_10e116_i133_a;
  wire  unnamed_1_10e116_i133_b;
  wire  unnamed_1_10e116_i133_y;
  wire  unnamed_1_10e116_i133_y_1;
  wire  unnamed_1_10e116_i138_a;
  wire  unnamed_1_10e116_i138_b;
  wire  unnamed_1_10e116_i138_y;
  wire  unnamed_1_10e116_i138_y_1;
  wire  unnamed_1_10e116_i43_a;
  wire  unnamed_1_10e116_i43_b;
  wire  unnamed_1_10e116_i43_y;
  wire  unnamed_1_10e116_i43_y_1;
  wire  unnamed_1_10e116_i93_a;
  wire  unnamed_1_10e116_i93_b;
  wire  unnamed_1_10e116_i93_y;
  wire  unnamed_1_10e116_i93_y_1;
  wire  unnamed_1_10h125_i102_y;
  wire  unnamed_1_10h125_i110_y;
  wire  unnamed_1_10h125_i118_y;
  wire  unnamed_1_10h125_i126_y;
  wire  unnamed_1_10h125_i134_y;
  wire  unnamed_1_10h125_i135_y;
  wire  unnamed_1_10h125_i84_y;
  wire  unnamed_1_10h125_i94_y;
  wire  unnamed_1_8merge_i178_a;
  wire  unnamed_1_8merge_i178_b;
  wire  unnamed_1_8merge_i178_c;
  wire  unnamed_1_8merge_i178_d;
  wire  unnamed_1_8merge_i178_e;
  wire  unnamed_1_8merge_i178_f;
  wire  unnamed_1_8merge_i178_g;
  wire  unnamed_1_8merge_i178_h;
  wire  unnamed_1_f07_i193_a;
  wire  unnamed_1_f07_i194_a;
  wire  unnamed_1_f07_i195_a;
  wire  unnamed_1_f07_i196_a;
  wire  unnamed_1_f07_i197_a;
  wire  unnamed_1_f07_i198_a;
  wire  unnamed_1_f07_i199_a;
  wire  unnamed_1_f07_i200_a;

  wire [15:0] page1_exttrig;
  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;
  wire  vtt;
  wire  page1_vtt;

  assign page1_exttrig[8:8] = exttrig[8:8];
  assign page1_exttrig[9:9] = exttrig[9:9];
  assign page1_exttrig[10:10] = exttrig[10:10];
  assign page1_exttrig[11:11] = exttrig[11:11];
  assign page1_exttrig[12:12] = exttrig[12:12];
  assign page1_exttrig[13:13] = exttrig[13:13];
  assign page1_exttrig[14:14] = exttrig[14:14];
  assign page1_exttrig[15:15] = exttrig[15:15];
  assign page1_exttrig[0:0] = exttrig[0:0];
  assign page1_exttrig[1:1] = exttrig[1:1];
  assign page1_exttrig[2:2] = exttrig[2:2];
  assign page1_exttrig[3:3] = exttrig[3:3];
  assign page1_exttrig[4:4] = exttrig[4:4];
  assign page1_exttrig[5:5] = exttrig[5:5];
  assign page1_exttrig[6:6] = exttrig[6:6];
  assign page1_exttrig[7:7] = exttrig[7:7];
  assign page1_exttrig[15:8] = exttrig[15:8];
  assign page1_exttrig[7:0] = exttrig[7:0];
  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;
  assign unnamed_1_10h125_i102_y = exttrig[4:4];
  assign unnamed_1_10h125_i110_y = exttrig[3:3];
  assign unnamed_1_10h125_i118_y = exttrig[2:2];
  assign unnamed_1_10h125_i126_y = exttrig[1:1];
  assign unnamed_1_10h125_i134_y = exttrig[0:0];
  assign unnamed_1_10h125_i135_y = exttrig[7:7];
  assign unnamed_1_10h125_i84_y = exttrig[6:6];
  assign unnamed_1_10h125_i94_y = exttrig[5:5];
  assign unnamed_1_8merge_i178_a = exttrig[15:15];
  assign unnamed_1_8merge_i178_b = exttrig[14:14];
  assign unnamed_1_8merge_i178_c = exttrig[13:13];
  assign unnamed_1_8merge_i178_d = exttrig[12:12];
  assign unnamed_1_8merge_i178_e = exttrig[11:11];
  assign unnamed_1_8merge_i178_f = exttrig[10:10];
  assign unnamed_1_8merge_i178_g = exttrig[9:9];
  assign unnamed_1_8merge_i178_h = exttrig[8:8];

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  testpoint_l page1_i29  (.a(glbl.gnd));

  testpoint_l page1_i30  (.a(unnamed_1_10e116_i43_a));

  rsmd0805 page1_i41  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i43_a));

  \10e116  page1_i43  (.a(unnamed_1_10e116_i43_a),
	.\b* (unnamed_1_10e116_i43_b),
	.ref(unnamed_1_10e116_i43_b),
	.y(unnamed_1_10e116_i43_y_1),
	.\y* (unnamed_1_10e116_i43_y));
  defparam page1_i43.size = 1;

  \10h125  page1_i84  (.a(unnamed_1_10e116_i43_y_1),
	.\b* (unnamed_1_10e116_i43_y),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i84_y));
  defparam page1_i84.size = 1;

  rsmd0805 page1_i85  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i43_y_1));

  rsmd0805 page1_i86  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i43_y));

  testpoint_l page1_i88  (.a(glbl.gnd));

  testpoint_l page1_i89  (.a(unnamed_1_10e116_i93_a));

  rsmd0805 page1_i90  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i93_a));

  rsmd0805 page1_i91  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i93_y));

  rsmd0805 page1_i92  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i93_y_1));

  \10e116  page1_i93  (.a(unnamed_1_10e116_i93_a),
	.\b* (unnamed_1_10e116_i93_b),
	.ref(unnamed_1_10e116_i93_b),
	.y(unnamed_1_10e116_i93_y),
	.\y* (unnamed_1_10e116_i93_y_1));
  defparam page1_i93.size = 1;

  \10h125  page1_i94  (.a(unnamed_1_10e116_i93_y),
	.\b* (unnamed_1_10e116_i93_y_1),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i94_y));
  defparam page1_i94.size = 1;

  testpoint_l page1_i96  (.a(glbl.gnd));

  testpoint_l page1_i97  (.a(unnamed_1_10e116_i101_a));

  rsmd0805 page1_i98  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i101_a));

  rsmd0805 page1_i99  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i101_y_1));

  rsmd0805 page1_i100  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i101_y));

  \10e116  page1_i101  (.a(unnamed_1_10e116_i101_a),
	.\b* (unnamed_1_10e116_i101_b),
	.ref(unnamed_1_10e116_i101_b),
	.y(unnamed_1_10e116_i101_y_1),
	.\y* (unnamed_1_10e116_i101_y));
  defparam page1_i101.size = 1;

  \10h125  page1_i102  (.a(unnamed_1_10e116_i101_y_1),
	.\b* (unnamed_1_10e116_i101_y),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i102_y));
  defparam page1_i102.size = 1;

  testpoint_l page1_i104  (.a(glbl.gnd));

  testpoint_l page1_i105  (.a(unnamed_1_10e116_i109_a));

  rsmd0805 page1_i106  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i109_a));

  rsmd0805 page1_i107  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i109_y_1));

  rsmd0805 page1_i108  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i109_y));

  \10e116  page1_i109  (.a(unnamed_1_10e116_i109_a),
	.\b* (unnamed_1_10e116_i109_b),
	.ref(unnamed_1_10e116_i109_b),
	.y(unnamed_1_10e116_i109_y_1),
	.\y* (unnamed_1_10e116_i109_y));
  defparam page1_i109.size = 1;

  \10h125  page1_i110  (.a(unnamed_1_10e116_i109_y_1),
	.\b* (unnamed_1_10e116_i109_y),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i110_y));
  defparam page1_i110.size = 1;

  testpoint_l page1_i112  (.a(glbl.gnd));

  testpoint_l page1_i113  (.a(unnamed_1_10e116_i117_a));

  rsmd0805 page1_i114  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i117_a));

  rsmd0805 page1_i115  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i117_y_1));

  rsmd0805 page1_i116  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i117_y));

  \10e116  page1_i117  (.a(unnamed_1_10e116_i117_a),
	.\b* (unnamed_1_10e116_i117_b),
	.ref(unnamed_1_10e116_i117_b),
	.y(unnamed_1_10e116_i117_y_1),
	.\y* (unnamed_1_10e116_i117_y));
  defparam page1_i117.size = 1;

  \10h125  page1_i118  (.a(unnamed_1_10e116_i117_y_1),
	.\b* (unnamed_1_10e116_i117_y),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i118_y));
  defparam page1_i118.size = 1;

  testpoint_l page1_i120  (.a(glbl.gnd));

  testpoint_l page1_i121  (.a(unnamed_1_10e116_i125_a));

  rsmd0805 page1_i122  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i125_a));

  rsmd0805 page1_i123  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i125_y_1));

  rsmd0805 page1_i124  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i125_y));

  \10e116  page1_i125  (.a(unnamed_1_10e116_i125_a),
	.\b* (unnamed_1_10e116_i125_b),
	.ref(unnamed_1_10e116_i125_b),
	.y(unnamed_1_10e116_i125_y_1),
	.\y* (unnamed_1_10e116_i125_y));
  defparam page1_i125.size = 1;

  \10h125  page1_i126  (.a(unnamed_1_10e116_i125_y_1),
	.\b* (unnamed_1_10e116_i125_y),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i126_y));
  defparam page1_i126.size = 1;

  testpoint_l page1_i128  (.a(glbl.gnd));

  testpoint_l page1_i129  (.a(unnamed_1_10e116_i133_a));

  rsmd0805 page1_i130  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i133_a));

  rsmd0805 page1_i131  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i133_y_1));

  rsmd0805 page1_i132  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i133_y));

  \10e116  page1_i133  (.a(unnamed_1_10e116_i133_a),
	.\b* (unnamed_1_10e116_i133_b),
	.ref(/* unconnected */),
	.y(unnamed_1_10e116_i133_y_1),
	.\y* (unnamed_1_10e116_i133_y));
  defparam page1_i133.size = 1;

  \10h125  page1_i134  (.a(unnamed_1_10e116_i133_y_1),
	.\b* (unnamed_1_10e116_i133_y),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i134_y));
  defparam page1_i134.size = 1;

  \10h125  page1_i135  (.a(unnamed_1_10e116_i138_y),
	.\b* (unnamed_1_10e116_i138_y_1),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i135_y));
  defparam page1_i135.size = 1;

  rsmd0805 page1_i136  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i138_y));

  rsmd0805 page1_i137  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i138_y_1));

  \10e116  page1_i138  (.a(unnamed_1_10e116_i138_a),
	.\b* (unnamed_1_10e116_i138_b),
	.ref(/* unconnected */),
	.y(unnamed_1_10e116_i138_y),
	.\y* (unnamed_1_10e116_i138_y_1));
  defparam page1_i138.size = 1;

  rsmd0805 page1_i139  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i138_a));

  rsmd0805 page1_i140  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i138_b));

  testpoint_l page1_i141  (.a(unnamed_1_10e116_i138_a));

  testpoint_l page1_i142  (.a(unnamed_1_10e116_i138_b));

  testpoint_l page1_i143  (.a(unnamed_1_f07_i196_a));

  testpoint_l page1_i144  (.a(glbl.gnd));

  testpoint_l page1_i157  (.a(unnamed_1_f07_i195_a));

  testpoint_l page1_i158  (.a(glbl.gnd));

  testpoint_l page1_i160  (.a(unnamed_1_f07_i193_a));

  testpoint_l page1_i161  (.a(glbl.gnd));

  testpoint_l page1_i163  (.a(unnamed_1_f07_i194_a));

  testpoint_l page1_i164  (.a(glbl.gnd));

  testpoint_l page1_i166  (.a(unnamed_1_f07_i198_a));

  testpoint_l page1_i167  (.a(glbl.gnd));

  testpoint_l page1_i169  (.a(unnamed_1_f07_i199_a));

  testpoint_l page1_i170  (.a(glbl.gnd));

  testpoint_l page1_i172  (.a(unnamed_1_f07_i200_a));

  testpoint_l page1_i173  (.a(glbl.gnd));

  testpoint_l page1_i175  (.a(unnamed_1_f07_i197_a));

  testpoint_l page1_i176  (.a(glbl.gnd));

  f07 page1_i193  (.a(unnamed_1_f07_i193_a),
	.y(unnamed_1_8merge_i178_d));
  defparam page1_i193.size = 1;

  f07 page1_i194  (.a(unnamed_1_f07_i194_a),
	.y(unnamed_1_8merge_i178_e));
  defparam page1_i194.size = 1;

  f07 page1_i195  (.a(unnamed_1_f07_i195_a),
	.y(unnamed_1_8merge_i178_c));
  defparam page1_i195.size = 1;

  f07 page1_i196  (.a(unnamed_1_f07_i196_a),
	.y(unnamed_1_8merge_i178_b));
  defparam page1_i196.size = 1;

  f07 page1_i197  (.a(unnamed_1_f07_i197_a),
	.y(unnamed_1_8merge_i178_a));
  defparam page1_i197.size = 1;

  f07 page1_i198  (.a(unnamed_1_f07_i198_a),
	.y(unnamed_1_8merge_i178_f));
  defparam page1_i198.size = 1;

  f07 page1_i199  (.a(unnamed_1_f07_i199_a),
	.y(unnamed_1_8merge_i178_g));
  defparam page1_i199.size = 1;

  f07 page1_i200  (.a(unnamed_1_f07_i200_a),
	.y(unnamed_1_8merge_i178_h));
  defparam page1_i200.size = 1;

  csmd0805 page1_i207  (.a({glbl.gnd}),
	.b(unnamed_1_10e116_i125_b));

  csmd0805 page1_i209  (.a({glbl.gnd}),
	.b(unnamed_1_10e116_i133_b));

  csmd0805 page1_i211  (.a({glbl.gnd}),
	.b(unnamed_1_10e116_i117_b));

  csmd0805 page1_i213  (.a({glbl.gnd}),
	.b(unnamed_1_10e116_i109_b));

  csmd0805 page1_i215  (.a({glbl.gnd}),
	.b(unnamed_1_10e116_i101_b));

  csmd0805 page1_i217  (.a({glbl.gnd}),
	.b(unnamed_1_10e116_i93_b));

  csmd0805 page1_i219  (.a({glbl.gnd}),
	.b(unnamed_1_10e116_i43_b));

  rsmd0805 page1_i222  (.a({glbl.vcc}),
	.b(unnamed_1_8merge_i178_e));

  rsmd0805 page1_i223  (.a({glbl.vcc}),
	.b(unnamed_1_8merge_i178_f));

  rsmd0805 page1_i224  (.a({glbl.vcc}),
	.b(unnamed_1_8merge_i178_g));

  rsmd0805 page1_i225  (.a({glbl.vcc}),
	.b(unnamed_1_8merge_i178_h));

  rsmd0805 page1_i226  (.a(unnamed_1_8merge_i178_d),
	.b({glbl.vcc}));

  rsmd0805 page1_i227  (.a(unnamed_1_8merge_i178_c),
	.b({glbl.vcc}));

  rsmd0805 page1_i228  (.a(unnamed_1_8merge_i178_b),
	.b({glbl.vcc}));

  rsmd0805 page1_i229  (.a(unnamed_1_8merge_i178_a),
	.b({glbl.vcc}));

endmodule // latchexttrig(sch_1) 
