// generated by newgenasym  Mon Oct 20 16:18:15 2014


module gt_delays (clk, data, dgt_ttl, dgth, dgtl, gtrigh, gtrigl, le_dgt,
        lockout, \lockout* , \lockout*_ttl , \mtcd_lo* , select_lo_src);
    input clk;
    input data;
    output dgt_ttl;
    output dgth;
    output dgtl;
    input gtrigh;
    input gtrigl;
    input le_dgt;
    output lockout;
    output \lockout* ;
    output \lockout*_ttl ;
    output \mtcd_lo* ;
    input select_lo_src;


    initial
        begin
        end

endmodule
