// generated by newgenasym  Tue Oct 28 15:28:26 2014


module gt_delays (clk, data, dgt_ttl, dgth, dgtl, gtrigh, gtrigl, le_dgt,
        lockout, \lockout* , \mtcd_lo* , select_lo_src, \ttl_lockout* );
    input clk;
    input data;
    output dgt_ttl;
    output dgth;
    output dgtl;
    input gtrigh;
    input gtrigl;
    input le_dgt;
    output lockout;
    output \lockout* ;
    output \mtcd_lo* ;
    input select_lo_src;
    output \ttl_lockout* ;


    initial
        begin
        end

endmodule
