// generated by newgenasym  Wed Feb 25 17:56:25 2015


module gt_delays (clk, data, dgt_n, dgt_p, dgt_ttl, gtrig, le_dgt, lockout,
        \lockout* , \mtcd_lo* , select_lo_src, \ttl_lockout* );
    input clk;
    input data;
    output dgt_n;
    output dgt_p;
    output dgt_ttl;
    input gtrig;
    input le_dgt;
    output lockout;
    output \lockout* ;
    output \mtcd_lo* ;
    input select_lo_src;
    output \ttl_lockout* ;


    initial
        begin
        end

endmodule
