// generated by newgenasym  Tue Mar 29 11:56:04 2011


module \1n914sz  (an, cat);
    parameter    size = 1;
    inout [size-1:0] an;
    inout [size-1:0] cat;


    initial
        begin
        end

endmodule
