-- generated by newgenasym Tue Mar 29 11:59:03 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity THM81000 is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	A6:        IN     STD_LOGIC;    
	A7:        IN     STD_LOGIC;    
	A8:        IN     STD_LOGIC;    
	A9:        IN     STD_LOGIC;    
	\cas*\:    IN     STD_LOGIC;    
	DQ0:       INOUT  STD_LOGIC;    
	DQ1:       INOUT  STD_LOGIC;    
	DQ2:       INOUT  STD_LOGIC;    
	DQ3:       INOUT  STD_LOGIC;    
	DQ4:       INOUT  STD_LOGIC;    
	DQ5:       INOUT  STD_LOGIC;    
	DQ6:       INOUT  STD_LOGIC;    
	DQ7:       INOUT  STD_LOGIC;    
	\ras*\:    IN     STD_LOGIC;    
	\we*\:     IN     STD_LOGIC);
end THM81000;
