`timescale 1ns/1ns

module tubii ();
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:25 2015
// from tubii_lib/TUBII/sch_1

  wire  unnamed_3_10h125_i4_a;
  wire  unnamed_3_10h125_i4_b;
  wire  unnamed_3_10h125_i4_y;
  wire  unnamed_3_10h125_i5_a;
  wire  unnamed_3_10h125_i5_b;
  wire  unnamed_3_10h125_i5_y;
  wire  unnamed_3_10h125_i6_a;
  wire  unnamed_3_10h125_i6_b;
  wire  unnamed_3_10h125_i6_y;
  wire  unnamed_3_ports2_i3_clock100outh;
  wire  unnamed_3_ports2_i3_clock100outl;
  wire  unnamed_3_ports2_i3_clock200outh;
  wire  unnamed_3_ports2_i3_clock200outl;
  wire [15:0] unnamed_3_ports2_i3_exttrig;
  wire [3:0] unnamed_3_ports2_i3_rawtrigs;
  wire  unnamed_3_ports2_i3_smelliedelayin;
  wire  unnamed_3_ports2_i3_smelliedelayout;
  wire  unnamed_3_ports2_i3_smelliepulseout;
  wire  unnamed_3_ports2_i3_telliedelayin;
  wire  unnamed_3_ports2_i3_telliedelayout;
  wire  unnamed_3_ports2_i3_telliepulseout;
  wire  unnamed_3_ports2_i3_tubclkin;
  wire  unnamed_3_ports2_i3_tubiirt;
  wire  unnamed_3_ports_i2_asyncdelayin;
  wire  unnamed_3_ports_i2_asyncdelayout;
  wire  unnamed_3_ports_i2_asyncpulseout;
  wire [11:0] unnamed_3_ports_i2_caenanpulse;
  wire [7:0] unnamed_3_ports_i2_caenout;
  wire  unnamed_3_ports_i2_dgth;
  wire  unnamed_3_ports_i2_dgtl;
  wire  unnamed_3_ports_i2_extpedin;
  wire  unnamed_3_ports_i2_extpedout;
  wire  unnamed_3_ports_i2_fastanpulse;
  wire  unnamed_3_ports_i2_fastcompouth;
  wire  unnamed_3_ports_i2_fastcompoutl;
  wire  unnamed_3_ports_i2_lockout;
  wire  unnamed_3_ports_i2_lockout_1;
  wire  unnamed_3_ports_i2_mtcdlo;
  wire [7:0] unnamed_3_ports_i2_scopeout;
  wire  unnamed_3_ports_i2_sync24hlvds;
  wire  unnamed_3_ports_i2_sync24llvds;
  wire  unnamed_3_ports_i2_syncdelayin;
  wire  unnamed_3_ports_i2_syncdelayout;
  wire  unnamed_3_ports_i2_synchlvds;
  wire  unnamed_3_ports_i2_syncllvds;
  wire  unnamed_3_ports_i2_syncpulseout;
  wire  unnamed_3_ports_i2_tuneanpulse;
  wire  unnamed_3_ports_i2_tunecompouth;
  wire  unnamed_3_ports_i2_tunecompoutl;

// begin instances 

  trigger_utility_board_mkii page3_i1  (.async_delay_in(unnamed_3_ports_i2_asyncdelayin),
	.async_delay_out(unnamed_3_ports_i2_asyncdelayout),
	.async_pulse_out(unnamed_3_ports_i2_asyncpulseout),
	.caen_anpulse(unnamed_3_ports_i2_caenanpulse[11:0]),
	.caen_out(unnamed_3_ports_i2_caenout[7:0]),
	.clock100_outh(unnamed_3_ports2_i3_clock100outh),
	.clock100_outl(unnamed_3_ports2_i3_clock100outl),
	.clock200_outh(unnamed_3_ports2_i3_clock200outh),
	.clock200_outl(unnamed_3_ports2_i3_clock200outl),
	.dgth(unnamed_3_ports_i2_dgth),
	.dgtl(unnamed_3_ports_i2_dgtl),
	.exttrig(unnamed_3_ports2_i3_exttrig[15:0]),
	.ext_ped_in(unnamed_3_ports_i2_extpedin),
	.ext_ped_out(unnamed_3_ports_i2_extpedout),
	.fast_anpulse(unnamed_3_ports_i2_fastanpulse),
	.fast_comp_outh(unnamed_3_ports_i2_fastcompouth),
	.fast_comp_outl(unnamed_3_ports_i2_fastcompoutl),
	.gtrigh_ecl(unnamed_3_10h125_i6_b),
	.gtrigl_ecl(unnamed_3_10h125_i6_a),
	.gtrig_ttl(unnamed_3_10h125_i4_y),
	.lockout(unnamed_3_ports_i2_lockout_1),
	.\lockout* (unnamed_3_ports_i2_lockout),
	.\mtcd_lo* (unnamed_3_ports_i2_mtcdlo),
	.rawtrigs(unnamed_3_ports2_i3_rawtrigs[3:0]),
	.scope_out(unnamed_3_ports_i2_scopeout[7:0]),
	.smellie_delay_in(unnamed_3_ports2_i3_smelliedelayin),
	.smellie_delay_out(unnamed_3_ports2_i3_smelliedelayout),
	.smellie_pulse_out(unnamed_3_ports2_i3_smelliepulseout),
	.sync24h_ecl(unnamed_3_10h125_i4_b),
	.sync24h_lvds(unnamed_3_ports_i2_sync24hlvds),
	.sync24l_ecl(unnamed_3_10h125_i4_a),
	.sync24l_lvds(unnamed_3_ports_i2_sync24llvds),
	.sync24_ttl(unnamed_3_10h125_i6_y),
	.synch_ecl(unnamed_3_10h125_i5_b),
	.synch_lvds(unnamed_3_ports_i2_synchlvds),
	.syncl_ecl(unnamed_3_10h125_i5_a),
	.syncl_lvds(unnamed_3_ports_i2_syncllvds),
	.sync_delay_in(unnamed_3_ports_i2_syncdelayin),
	.sync_delay_out(unnamed_3_ports_i2_syncdelayout),
	.sync_pulse_out(unnamed_3_ports_i2_syncpulseout),
	.sync_ttl(unnamed_3_10h125_i5_y),
	.tellie_delay_in(unnamed_3_ports2_i3_telliedelayin),
	.tellie_delay_out(unnamed_3_ports2_i3_telliedelayout),
	.tellie_pulse_out(unnamed_3_ports2_i3_telliepulseout),
	.tubii_rt_out(unnamed_3_ports2_i3_tubiirt),
	.tub_clk_in(unnamed_3_ports2_i3_tubclkin),
	.tune_anpulse(unnamed_3_ports_i2_tuneanpulse),
	.tune_comp_outh(unnamed_3_ports_i2_tunecompouth),
	.tune_comp_outl(unnamed_3_ports_i2_tunecompoutl));

  ports page3_i2  (.async_delay_in(unnamed_3_ports_i2_asyncdelayin),
	.async_delay_out(unnamed_3_ports_i2_asyncdelayout),
	.async_pulse_out(unnamed_3_ports_i2_asyncpulseout),
	.caen_anpulse(unnamed_3_ports_i2_caenanpulse[11:0]),
	.caen_out(unnamed_3_ports_i2_caenout[7:0]),
	.dgth(unnamed_3_ports_i2_dgth),
	.dgtl(unnamed_3_ports_i2_dgtl),
	.ext_ped_in(unnamed_3_ports_i2_extpedin),
	.ext_ped_out(unnamed_3_ports_i2_extpedout),
	.fast_anpulse(unnamed_3_ports_i2_fastanpulse),
	.fast_comp_outh(unnamed_3_ports_i2_fastcompouth),
	.fast_comp_outl(unnamed_3_ports_i2_fastcompoutl),
	.gtrigh_ecl(unnamed_3_10h125_i6_b),
	.gtrigl_ecl(unnamed_3_10h125_i6_a),
	.lockout(unnamed_3_ports_i2_lockout_1),
	.\lockout* (unnamed_3_ports_i2_lockout),
	.\mtcd_lo* (unnamed_3_ports_i2_mtcdlo),
	.scope_out(unnamed_3_ports_i2_scopeout[7:0]),
	.sync24h_ecl(unnamed_3_10h125_i4_b),
	.sync24h_lvds(unnamed_3_ports_i2_sync24hlvds),
	.sync24l_ecl(unnamed_3_10h125_i4_a),
	.sync24l_lvds(unnamed_3_ports_i2_sync24llvds),
	.synch_ecl(unnamed_3_10h125_i5_b),
	.synch_lvds(unnamed_3_ports_i2_synchlvds),
	.syncl_ecl(unnamed_3_10h125_i5_a),
	.syncl_lvds(unnamed_3_ports_i2_syncllvds),
	.sync_delay_in(unnamed_3_ports_i2_syncdelayin),
	.sync_delay_out(unnamed_3_ports_i2_syncdelayout),
	.sync_pulse_out(unnamed_3_ports_i2_syncpulseout),
	.tune_anpulse(unnamed_3_ports_i2_tuneanpulse),
	.tune_comp_outh(unnamed_3_ports_i2_tunecompouth),
	.tune_comp_outl(unnamed_3_ports_i2_tunecompoutl));

  ports2 page3_i3  (.clock100_outh(unnamed_3_ports2_i3_clock100outh),
	.clock100_outl(unnamed_3_ports2_i3_clock100outl),
	.clock200_outh(unnamed_3_ports2_i3_clock200outh),
	.clock200_outl(unnamed_3_ports2_i3_clock200outl),
	.exttrig(unnamed_3_ports2_i3_exttrig[15:0]),
	.rawtrigs(unnamed_3_ports2_i3_rawtrigs[3:0]),
	.smellie_delay_in(unnamed_3_ports2_i3_smelliedelayin),
	.smellie_delay_out(unnamed_3_ports2_i3_smelliedelayout),
	.smellie_pulse_out(unnamed_3_ports2_i3_smelliepulseout),
	.tellie_delay_in(unnamed_3_ports2_i3_telliedelayin),
	.tellie_delay_out(unnamed_3_ports2_i3_telliedelayout),
	.tellie_pulse_out(unnamed_3_ports2_i3_telliepulseout),
	.tubii_rt(unnamed_3_ports2_i3_tubiirt),
	.tub_clk_in(unnamed_3_ports2_i3_tubclkin));

  \10h125  page3_i4  (.a(unnamed_3_10h125_i4_a),
	.\b* (unnamed_3_10h125_i4_b),
	.v(/* unconnected */),
	.y(unnamed_3_10h125_i4_y));
  defparam page3_i4.size = 1;

  \10h125  page3_i5  (.a(unnamed_3_10h125_i5_a),
	.\b* (unnamed_3_10h125_i5_b),
	.v(/* unconnected */),
	.y(unnamed_3_10h125_i5_y));
  defparam page3_i5.size = 1;

  \10h125  page3_i6  (.a(unnamed_3_10h125_i6_a),
	.\b* (unnamed_3_10h125_i6_b),
	.v(/* unconnected */),
	.y(unnamed_3_10h125_i6_y));
  defparam page3_i6.size = 1;

endmodule // tubii(sch_1) 
