// generated by newgenasym  Tue Mar 29 12:00:30 2011


module lm309h_l (an, cat, gnd, ref);
    input an;
    output cat;
    inout gnd;
    inout ref;


    initial
        begin
        end

endmodule
