// generated by newgenasym  Fri Feb 20 13:36:38 2015


module ttl_ecl_translation (ecl_in, ecl_out, ttl_in, ttl_out);
    input ecl_in;
    output ecl_out;
    input ttl_in;
    output ttl_out;


    initial
        begin
        end

endmodule
