-- generated by newgenasym Fri Feb 20 13:36:38 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ttl_ecl_translation is
    port (    
	ECL_IN:    IN     STD_LOGIC;    
	ECL_OUT:   OUT    STD_LOGIC;    
	TTL_IN:    IN     STD_LOGIC;    
	TTL_OUT:   OUT    STD_LOGIC);
end ttl_ecl_translation;
