// generated by newgenasym  Tue Mar 29 11:56:43 2011


module ad842 (nin, nvss, out, pin, pvss);
    inout nin;
    input nvss;
    inout out;
    inout pin;
    input pvss;


    initial
        begin
        end

endmodule
