// generated by newgenasym  Fri Oct 10 10:54:44 2014


module caen (an_pulse_in, caen_out, clk, data, data_rdy, gtrigh_ecl,
        gtrigl_ecl, le, scope_out, sync24h_ecl, sync24h_lvds,
        sync24l_ecl, sync24l_lvds, synch_ecl, synch_lvds,
        syncl_ecl, syncl_lvds);
    output [11:0] an_pulse_in;
    output [7:0] caen_out;
    input clk;
    input data;
    input data_rdy;
    output gtrigh_ecl;
    output gtrigl_ecl;
    input le;
    output [7:0] scope_out;
    output sync24h_ecl;
    output sync24h_lvds;
    output sync24l_ecl;
    output sync24l_lvds;
    output synch_ecl;
    output synch_lvds;
    output syncl_ecl;
    output syncl_lvds;


    initial
        begin
        end

endmodule
