// generated by newgenasym  Wed Feb 25 10:35:14 2015


module caen (an_pulse_in, caen_out, clk, data, data_rdy, gt_ecl_n,
        gt_ecl_p, le, scope_out, sync24_ecl_n, sync24_ecl_p,
        sync24_lvds_n, sync24_lvds_p, sync_ecl_n, sync_ecl_p,
        sync_lvds_n, sync_lvds_p);
    output [11:0] an_pulse_in;
    output [7:0] caen_out;
    input clk;
    input data;
    input data_rdy;
    output gt_ecl_n;
    output gt_ecl_p;
    input le;
    output [7:0] scope_out;
    output sync24_ecl_n;
    output sync24_ecl_p;
    output sync24_lvds_n;
    output sync24_lvds_p;
    output sync_ecl_n;
    output sync_ecl_p;
    output sync_lvds_n;
    output sync_lvds_p;


    initial
        begin
        end

endmodule
