-- generated by newgenasym Wed Oct 08 11:47:45 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen is
    port (    
	CAEN_OUT:  OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	GTRIGH_ECL: OUT    STD_LOGIC;    
	GTRIGL_ECL: OUT    STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	SCOPE_OUT: OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	SYNC24H_ECL: OUT    STD_LOGIC;    
	SYNC24H_LVDS: OUT    STD_LOGIC;    
	SYNC24L_ECL: OUT    STD_LOGIC;    
	SYNC24L_LVDS: OUT    STD_LOGIC;    
	SYNCH_ECL: OUT    STD_LOGIC;    
	SYNCH_LVDS: OUT    STD_LOGIC;    
	SYNCL_ECL: OUT    STD_LOGIC;    
	SYNCL_LVDS: OUT    STD_LOGIC);
end caen;
