-- generated by newgenasym Wed Feb 25 10:35:14 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen is
    port (    
	AN_PULSE_IN: OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);    
	CAEN_OUT:  OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	GT_ECL_N:  OUT    STD_LOGIC;    
	GT_ECL_P:  OUT    STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	SCOPE_OUT: OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	SYNC24_ECL_N: OUT    STD_LOGIC;    
	SYNC24_ECL_P: OUT    STD_LOGIC;    
	SYNC24_LVDS_N: OUT    STD_LOGIC;    
	SYNC24_LVDS_P: OUT    STD_LOGIC;    
	SYNC_ECL_N: OUT    STD_LOGIC;    
	SYNC_ECL_P: OUT    STD_LOGIC;    
	SYNC_LVDS_N: OUT    STD_LOGIC;    
	SYNC_LVDS_P: OUT    STD_LOGIC);
end caen;
