// generated by newgenasym  Tue Mar 29 11:59:36 2011


module \10h103_l  (a, b, c, d, y0, y1, \y1* );
    parameter    section = 0;
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] b;
    input [size-1:0] c;
    input [size-1:0] d;
    output [size-1:0] y0;
    output [size-1:0] y1;
    output [size-1:0] \y1* ;


    initial
        begin
        end

endmodule
