-- generated by newgenasym Tue Mar 29 11:58:40 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SCHOTTKY is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC);
end SCHOTTKY;
