// generated by newgenasym  Tue Mar 29 12:00:38 2011


module res_j (a, b);
    parameter    size = 1;
    input [size-1:0] a;
    output [size-1:0] b;


    initial
        begin
        end

endmodule
