// generated by newgenasym  Wed Oct 29 18:30:21 2014


module \10h124  (common, d, y, \y* );
    input common;
    input d;
    output y;
    output \y* ;


    initial
        begin
        end

endmodule
