-- generated by newgenasym Mon Jan  3 14:10:25 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h124\ is
    port (    
	C:         IN     STD_LOGIC;    
	D:         IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC);
end \10h124\;
