-- generated by newgenasym Tue Mar 29 11:59:40 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h601\ is
    port (    
	D0:        IN     STD_LOGIC;    
	D1:        IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	D5:        IN     STD_LOGIC;    
	D6:        IN     STD_LOGIC;    
	D7:        IN     STD_LOGIC;    
	D8:        IN     STD_LOGIC;    
	\oeecl*\:  IN     STD_LOGIC;    
	\oettl*\:  IN     STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	Q5:        OUT    STD_LOGIC;    
	Q6:        OUT    STD_LOGIC;    
	Q7:        OUT    STD_LOGIC;    
	Q8:        OUT    STD_LOGIC);
end \10h601\;
