// generated by newgenasym  Wed Oct 01 15:10:42 2014


module \nim-ecl  (ecl_out_bnc, ecl_out_smb, nim_in);
    output ecl_out_bnc;
    output ecl_out_smb;
    input nim_in;


    initial
        begin
        end

endmodule
