-- generated by newgenasym Tue Oct 14 18:35:48 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \nim-ecl\ is
    port (    
	ECL_OUT:   OUT    STD_LOGIC;    
	NIM_IN:    IN     STD_LOGIC);
end \nim-ecl\;
