-- generated by newgenasym Wed Oct 01 15:10:42 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \nim-ecl\ is
    port (    
	ECL_OUT_BNC: OUT    STD_LOGIC;    
	ECL_OUT_SMB: OUT    STD_LOGIC;    
	NIM_IN:    IN     STD_LOGIC);
end \nim-ecl\;
