// generated by newgenasym  Tue Mar 29 12:00:08 2011


module xmemfifot (cclk, m2, \program* , \pwrdwn* , \rdata* , \reset* , rtrig, sdin,
        sdout, spares, xbba, \xbrw* , xbwr_add, \xfifo_reset* , xmdtack,
        \xmem_write_enable* , \xmemack1* , \xmemack2* , \xmemreq2* ,
        \xmemspace* , \xmodsel* , \xreq1* , \xreq2* , \xsel1* , \xsel2* ,
        \xsimm_en- , xtestmem1, xtestmem2);
    input cclk;
    output m2;
    input \program* ;
    input \pwrdwn* ;
    output \rdata* ;
    input \reset* ;
    input rtrig;
    input sdin;
    output sdout;
    input [9:0] spares;
    input [24:2] xbba;
    input \xbrw* ;
    output [21:2] xbwr_add;
    input \xfifo_reset* ;
    input xmdtack;
    output \xmem_write_enable* ;
    output \xmemack1* ;
    output \xmemack2* ;
    input \xmemreq2* ;
    input \xmemspace* ;
    input \xmodsel* ;
    output \xreq1* ;
    output \xreq2* ;
    input \xsel1* ;
    input \xsel2* ;
    output [7:0] \xsimm_en- ;
    input xtestmem1;
    input xtestmem2;


    initial
        begin
        end

endmodule
