-- generated by newgenasym Tue Mar 29 12:00:08 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity XMEMFIFOT is
    port (    
	CCLK:      IN     STD_LOGIC;    
	M2:        OUT    STD_LOGIC;    
	\program*\: IN     STD_LOGIC;    
	\pwrdwn*\: IN     STD_LOGIC;    
	\rdata*\:  OUT    STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	RTRIG:     IN     STD_LOGIC;    
	SDIN:      IN     STD_LOGIC;    
	SDOUT:     OUT    STD_LOGIC;    
	SPARES:    IN     STD_LOGIC_VECTOR (9 DOWNTO 0);    
	XBBA:      IN     STD_LOGIC_VECTOR (24 DOWNTO 2);    
	\xbrw*\:   IN     STD_LOGIC;    
	XBWR_ADD:  OUT    STD_LOGIC_VECTOR (21 DOWNTO 2);    
	\xfifo_reset*\: IN     STD_LOGIC;    
	XMDTACK:   IN     STD_LOGIC;    
	\xmem_write_enable*\: OUT    STD_LOGIC;    
	\xmemack1*\: OUT    STD_LOGIC;    
	\xmemack2*\: OUT    STD_LOGIC;    
	\xmemreq2*\: IN     STD_LOGIC;    
	\xmemspace*\: IN     STD_LOGIC;    
	\xmodsel*\: IN     STD_LOGIC;    
	\xreq1*\:  OUT    STD_LOGIC;    
	\xreq2*\:  OUT    STD_LOGIC;    
	\xsel1*\:  IN     STD_LOGIC;    
	\xsel2*\:  IN     STD_LOGIC;    
	\xsimm_en-\: OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	XTESTMEM1: IN     STD_LOGIC;    
	XTESTMEM2: IN     STD_LOGIC);
end XMEMFIFOT;
