// generated by newgenasym  Fri Oct 10 11:45:08 2014


module ports2 (burst_trig, clock100_outh, clock100_outl, clock200_outh,
        clock200_outl, combo_trig, exttrig, prescale_trig,
        rawtrigs, smellie_delay_in, smellie_delay_out,
        smellie_pulse_out, tellie_delay_in, tellie_delay_out,
        tellie_pulse_out, tub_clk_in, tubii_gt);
    output burst_trig;
    output clock100_outh;
    output clock100_outl;
    output clock200_outh;
    output clock200_outl;
    output combo_trig;
    output [15:0] exttrig;
    output prescale_trig;
    output [3:0] rawtrigs;
    output smellie_delay_in;
    output smellie_delay_out;
    output smellie_pulse_out;
    output tellie_delay_in;
    output tellie_delay_out;
    output tellie_pulse_out;
    output tub_clk_in;
    output tubii_gt;


    initial
        begin
        end

endmodule
