// generated by newgenasym  Wed Feb 25 10:35:50 2015


module ports2 (clk100_out_n, clk100_out_p, clk200_out_n, clk200_out_p,
        exttrig, rawtrigs, smellie_delay_in, smellie_delay_out,
        smellie_pulse_out, tellie_delay_in, tellie_delay_out,
        tellie_pulse_out, tub_clk_in, tubii_rt);
    output clk100_out_n;
    output clk100_out_p;
    output clk200_out_n;
    output clk200_out_p;
    output [15:0] exttrig;
    output [3:0] rawtrigs;
    output smellie_delay_in;
    output smellie_delay_out;
    output smellie_pulse_out;
    output tellie_delay_in;
    output tellie_delay_out;
    output tellie_pulse_out;
    output tub_clk_in;
    output tubii_rt;


    initial
        begin
        end

endmodule
