// generated by newgenasym  Fri Oct 17 13:58:14 2014


module ports2 (clock100_outh, clock100_outl, clock200_outh,
        clock200_outl, exttrig, rawtrigs, smellie_delay_in,
        smellie_delay_out, smellie_pulse_out, tellie_delay_in,
        tellie_delay_out, tellie_pulse_out, tub_clk_in, tubii_rt);
    output clock100_outh;
    output clock100_outl;
    output clock200_outh;
    output clock200_outl;
    output [15:0] exttrig;
    output [3:0] rawtrigs;
    output smellie_delay_in;
    output smellie_delay_out;
    output smellie_pulse_out;
    output tellie_delay_in;
    output tellie_delay_out;
    output tellie_pulse_out;
    output tub_clk_in;
    output tubii_rt;


    initial
        begin
        end

endmodule
