`timescale 1ns/1ns

module \ecl-ttl  (ecl_in, ttl_out );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:15 2015
// from tubii_lib/ECL-TTL/sch_1

  inout  ecl_in;
  inout  ttl_out;
  // global signal glbl.gnd;
  // global signal glbl.vtt;

  wire  unnamed_1_10e116_i26_b;
  wire  unnamed_1_10e116_i26_y;
  wire  unnamed_1_10h125_i1_b;

  wire  gnd;
  wire  page1_gnd;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  \10h125  page1_i1  (.a(unnamed_1_10e116_i26_y),
	.\b* (unnamed_1_10h125_i1_b),
	.v(unnamed_1_10h125_i1_b),
	.y(ttl_out));
  defparam page1_i1.size = 1;

  rsmd0805 page1_i13  (.a({glbl.vtt}),
	.b(ecl_in));

  rsmd0805 page1_i17  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i26_y));

  \10e116  page1_i26  (.a(ecl_in),
	.\b* (unnamed_1_10e116_i26_b),
	.ref(unnamed_1_10e116_i26_b),
	.y(unnamed_1_10e116_i26_y),
	.\y* (/* unconnected */));
  defparam page1_i26.size = 1;

  csmd0805 page1_i27  (.a(unnamed_1_10e116_i26_b),
	.b({glbl.gnd}));

  csmd0805 page1_i29  (.a({glbl.gnd}),
	.b(unnamed_1_10h125_i1_b));

endmodule // \ecl-ttl (sch_1) 
