-- generated by newgenasym Tue Mar 29 12:00:36 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MMBTH81LT1 is
    port (    
	B:         IN     STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end MMBTH81LT1;
