-- generated by newgenasym Tue Mar 29 11:56:43 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD842 is
    port (    
	NIN:       INOUT  STD_LOGIC;    
	NVSS:      IN     STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	PIN:       INOUT  STD_LOGIC;    
	PVSS:      IN     STD_LOGIC);
end AD842;
