// generated by newgenasym  Thu Oct 16 18:57:11 2014


module \10ep90  (d, \d* , q, \q* );
    input d;
    input \d* ;
    output q;
    output \q* ;


    initial
        begin
        end

endmodule
