-- generated by newgenasym Thu Oct 16 18:57:11 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10ep90\ is
    port (    
	D:         IN     STD_LOGIC;    
	\d*\:      IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC);
end \10ep90\;
