// generated by newgenasym  Tue Mar 29 11:58:39 2011


module res_l (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
