-- generated by newgenasym Tue Mar 29 12:00:01 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity JUMPER is
    port (    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end JUMPER;
