// generated by newgenasym  Fri Oct 03 15:57:27 2014


module ellie_talk (delay_in, delay_out, pulse_out);
    output delay_in;
    input delay_out;
    input pulse_out;


    initial
        begin
        end

endmodule
