-- generated by newgenasym Fri Oct 03 15:57:27 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ellie_talk is
    port (    
	DELAY_IN:  OUT    STD_LOGIC;    
	DELAY_OUT: IN     STD_LOGIC;    
	PULSE_OUT: IN     STD_LOGIC);
end ellie_talk;
