`timescale 1ns/1ns

module tubii_time (bckp_clk, clk100_outh, clk100_outl, data, data_rdy, default_clk, le, missedclock, sr_clk 
    );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:19 2015
// from tubii_lib/TUBII_TIME/sch_1

  inout  bckp_clk;
  inout  clk100_outh;
  inout  clk100_outl;
  inout  data;
  inout  data_rdy;
  inout  default_clk;
  inout  le;
  inout  missedclock;
  inout  sr_clk;
  // global signal glbl.gnd;
  // global signal glbl.mstreset_ecl;
  // global signal glbl.vcc;
  // global signal glbl.vih;
  // global signal glbl.vtt;

  wire  bckpclock100h;
  wire  bckpclock100l;
  wire  bckpclock2h;
  wire  bckpclock2l;
  wire  clock100h;
  wire  clock100l;
  wire  clockgood;
  wire  ecl_reset;
  wire  ttl_reset;
  wire  vbb;
  wire [7:0] count_val;
  wire  unnamed_1_100el05_i64_in1;
  wire  unnamed_1_100el05_i64_in1_1;
  wire  unnamed_1_100el05_i64_in2;
  wire  unnamed_1_100el05_i64_in2_1;
  wire  unnamed_1_100el05_i64_out;
  wire  unnamed_1_100el05_i64_out_1;
  wire  unnamed_1_100el05_i94_in2;
  wire  unnamed_1_100el05_i94_in2_1;
  wire  unnamed_1_100el05_i94_out;
  wire  unnamed_1_100el05_i95_in1;
  wire  unnamed_1_100el05_i95_in1_1;
  wire  unnamed_1_100el05_i95_out;
  wire  unnamed_1_100el34_i130_out2;
  wire  unnamed_1_100el34_i130_out2_1;
  wire  unnamed_1_100el34_i130_out4;
  wire  unnamed_1_100el34_i130_out4_1;
  wire  unnamed_1_100el34_i130_out8;
  wire  unnamed_1_100el34_i130_out8_1;
  wire  unnamed_1_10e016_i58_ce;
  wire  unnamed_1_10e016_i58_clk;
  wire  unnamed_1_10e016_i58_pe;
  wire  unnamed_1_10e016_i58_tc;
  wire  unnamed_1_10e101_i111_y;
  wire  unnamed_1_10e101_i111_y_1;
  wire  unnamed_1_10e101_i123_b;
  wire  unnamed_1_10e101_i123_d;
  wire  unnamed_1_10e101_i123_y;
  wire  unnamed_1_10e101_i123_y_1;
  wire  unnamed_1_10e101_i79_d;
  wire  unnamed_1_10e101_i79_y;
  wire  unnamed_1_10e116_i107_a;
  wire  unnamed_1_10e116_i107_b;
  wire  unnamed_1_10e116_i107_y;
  wire  unnamed_1_10e116_i107_y_1;
  wire  unnamed_1_10e116_i119_a;
  wire  unnamed_1_10e116_i119_b;
  wire  unnamed_1_10e116_i74_y;
  wire  unnamed_1_10e116_i87_y;
  wire  unnamed_1_10e131_i71_q;
  wire  unnamed_1_10h116_i214_b;
  wire  unnamed_1_10h125_i38_a;
  wire  unnamed_1_10h125_i38_b;
  wire  unnamed_1_10h125_i38_y;
  wire  unnamed_1_74f164_i182_q0;
  wire  unnamed_1_74f164_i182_q1;
  wire  unnamed_1_74f164_i182_q2;
  wire  unnamed_1_74f164_i182_q3;
  wire  unnamed_1_74f164_i182_q4;
  wire  unnamed_1_74f164_i182_q5;
  wire  unnamed_1_74f164_i182_q6;
  wire  unnamed_1_74f164_i182_q7;
  wire  unnamed_1_8merge_i183_a;
  wire  unnamed_1_8merge_i183_b;
  wire  unnamed_1_8merge_i183_c;
  wire  unnamed_1_8merge_i183_d;
  wire  unnamed_1_8merge_i183_e;
  wire  unnamed_1_8merge_i183_f;
  wire  unnamed_1_8merge_i183_g;
  wire  unnamed_1_8merge_i183_h;
  wire  unnamed_1_csmd0805_i148_b;
  wire  unnamed_1_f273_i50_cp;
  wire  unnamed_1_ledl_i204_a;
  wire  unnamed_1_ledl_i205_a;
  wire  unnamed_1_ledl_i206_a;
  wire  unnamed_1_ledl_i207_a;
  wire  unnamed_1_rsmd0805_i52_a;

  wire  gnd;
  wire  page1_gnd;
  wire  mstreset_ecl;
  wire  page1_mstreset_ecl;
  wire  vcc;
  wire  page1_vcc;
  wire  vih;
  wire  page1_vih;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign mstreset_ecl = glbl.mstreset_ecl;
  assign page1_mstreset_ecl = mstreset_ecl;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vih = glbl.vih;
  assign page1_vih = vih;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;
  assign unnamed_1_8merge_i183_a = count_val[7:7];
  assign unnamed_1_8merge_i183_b = count_val[6:6];
  assign unnamed_1_8merge_i183_c = count_val[5:5];
  assign unnamed_1_8merge_i183_d = count_val[4:4];
  assign unnamed_1_8merge_i183_e = count_val[3:3];
  assign unnamed_1_8merge_i183_f = count_val[2:2];
  assign unnamed_1_8merge_i183_g = count_val[1:1];
  assign unnamed_1_8merge_i183_h = count_val[0:0];

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  rsmd0805 page1_i27  (.a({glbl.vtt}),
	.b(clock100l));

  rsmd0805 page1_i28  (.a({glbl.vtt}),
	.b(clock100h));

  \10h125  page1_i38  (.a(unnamed_1_10h125_i38_a),
	.\b* (unnamed_1_10h125_i38_b),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i38_y));
  defparam page1_i38.size = 1;

  rsmd0805 page1_i39  (.a({glbl.vtt}),
	.b(unnamed_1_10h125_i38_a));

  rsmd0805 page1_i40  (.a({glbl.vtt}),
	.b(unnamed_1_10h125_i38_b));

  hct123 page1_i41  (.c(glbl.gnd),
	.\c/r (unnamed_1_csmd0805_i148_b),
	.\cl* (glbl.vcc),
	.clock(unnamed_1_10h125_i38_y),
	.\clock* (glbl.gnd),
	.q(clockgood),
	.\q* (unnamed_1_f273_i50_cp));

  rsmd0805 page1_i48  (.a(clockgood),
	.b(unnamed_1_ledl_i207_a));

  testpoint_l page1_i49  (.a(clockgood));

  f273 page1_i50  (.cl(ttl_reset),
	.cp(unnamed_1_f273_i50_cp),
	.d(glbl.vcc),
	.q(unnamed_1_rsmd0805_i52_a));

  rsmd0805 page1_i52  (.a(unnamed_1_rsmd0805_i52_a),
	.b(unnamed_1_ledl_i206_a));

  testpoint_l page1_i55  (.a(unnamed_1_rsmd0805_i52_a));

  testpoint_l page1_i56  (.a(unnamed_1_f273_i50_cp));

  \10e016  page1_i58  (.\ce* (unnamed_1_10e016_i58_ce),
	.clk(unnamed_1_10e016_i58_clk),
	.mr(glbl.mstreset_ecl),
	.p(count_val[7:0]),
	.\pe* (unnamed_1_10e016_i58_pe),
	.q(/* unconnected */),
	.\tc* (unnamed_1_10e016_i58_tc),
	.tcld(glbl.vih));

  rsmd0805 page1_i61  (.a({glbl.vtt}),
	.b(unnamed_1_10e016_i58_pe));

  \100el05  page1_i64  (.in1(unnamed_1_100el05_i64_in1_1),
	.\in1* (unnamed_1_100el05_i64_in1),
	.in2(unnamed_1_100el05_i64_in2_1),
	.\in2* (unnamed_1_100el05_i64_in2),
	.out(unnamed_1_100el05_i64_out),
	.\out* (unnamed_1_100el05_i64_out_1));

  rsmd0805 page1_i65  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i64_in2));

  rsmd0805 page1_i66  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i64_in2_1));

  rsmd0805 page1_i67  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i64_in1));

  rsmd0805 page1_i68  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i64_in1_1));

  rsmd0805 page1_i69  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i64_out));

  \10e131  page1_i71  (.clk(/* unconnected */),
	.d({glbl.vih}),
	.en(unnamed_1_10e116_i74_y),
	.q(/* unconnected */),
	.\q* (unnamed_1_10e131_i71_q),
	.r(unnamed_1_10e101_i79_y),
	.s(/* unconnected */));
  defparam page1_i71.size = 1;

  \10e116  page1_i72  (.a(unnamed_1_100el05_i64_out),
	.\b* (unnamed_1_100el05_i64_out_1),
	.ref(vbb),
	.y(unnamed_1_10e016_i58_clk),
	.\y* (/* unconnected */));
  defparam page1_i72.size = 1;

  \10e116  page1_i74  (.a(unnamed_1_100el05_i64_out),
	.\b* (unnamed_1_100el05_i64_out_1),
	.ref(vbb),
	.y(unnamed_1_10e116_i74_y),
	.\y* (/* unconnected */));
  defparam page1_i74.size = 1;

  rsmd0805 page1_i75  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i64_out_1));

  rsmd0805 page1_i76  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i74_y));

  rsmd0805 page1_i77  (.a({glbl.vtt}),
	.b(unnamed_1_10e016_i58_clk));

  \10e116  page1_i78  (.a(unnamed_1_10e016_i58_tc),
	.\b* (vbb),
	.ref(vbb),
	.y(/* unconnected */),
	.\y* (unnamed_1_10e101_i79_d));
  defparam page1_i78.size = 1;

  \10e101  page1_i79  (.a({glbl.mstreset_ecl}),
	.b(/* unconnected */),
	.c(/* unconnected */),
	.d(unnamed_1_10e101_i79_d),
	.y(unnamed_1_10e101_i79_y),
	.\y* (/* unconnected */));
  defparam page1_i79.size = 1;

  rsmd0805 page1_i80  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i79_y));

  csmd0805 page1_i81  (.a({glbl.gnd}),
	.b(vbb));

  rsmd0805 page1_i83  (.a({glbl.vtt}),
	.b(unnamed_1_10e016_i58_ce));

  rsmd0805 page1_i84  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i79_d));

  rsmd0805 page1_i85  (.a({glbl.vtt}),
	.b(unnamed_1_10e131_i71_q));

  rsmd0805 page1_i86  (.a({glbl.vtt}),
	.b(unnamed_1_10e016_i58_tc));

  \10e116  page1_i87  (.a(vbb),
	.\b* (unnamed_1_10e016_i58_tc),
	.ref(vbb),
	.y(unnamed_1_10e116_i87_y),
	.\y* (/* unconnected */));
  defparam page1_i87.size = 1;

  csmd0805 page1_i88  (.a(vbb),
	.b({glbl.gnd}));

  \10e131  page1_i90  (.clk(/* unconnected */),
	.d({glbl.vih}),
	.en(unnamed_1_10e116_i87_y),
	.q(unnamed_1_10e116_i107_a),
	.\q* (unnamed_1_10e116_i107_b),
	.r(ecl_reset),
	.s(/* unconnected */));
  defparam page1_i90.size = 1;

  rsmd0805 page1_i91  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i87_y));

  \10e116  page1_i93  (.a(unnamed_1_100el05_i64_in2_1),
	.\b* (unnamed_1_100el05_i64_in2),
	.ref(vbb),
	.y(bckpclock100h),
	.\y* (bckpclock100l));
  defparam page1_i93.size = 1;

  \100el05  page1_i94  (.in1(bckpclock100h),
	.\in1* (bckpclock100l),
	.in2(unnamed_1_100el05_i94_in2_1),
	.\in2* (unnamed_1_100el05_i94_in2),
	.out(unnamed_1_100el05_i94_out),
	.\out* (/* unconnected */));

  \100el05  page1_i95  (.in1(unnamed_1_100el05_i95_in1_1),
	.\in1* (unnamed_1_100el05_i95_in1),
	.in2(clock100h),
	.\in2* (clock100l),
	.out(unnamed_1_100el05_i95_out),
	.\out* (/* unconnected */));

  \10e116  page1_i96  (.a(unnamed_1_10e116_i107_a),
	.\b* (unnamed_1_10e116_i107_b),
	.ref(vbb),
	.y(unnamed_1_100el05_i94_in2_1),
	.\y* (unnamed_1_100el05_i94_in2));
  defparam page1_i96.size = 1;

  \10e116  page1_i97  (.a(unnamed_1_10e116_i107_b),
	.\b* (unnamed_1_10e116_i107_a),
	.ref(vbb),
	.y(unnamed_1_100el05_i95_in1_1),
	.\y* (unnamed_1_100el05_i95_in1));
  defparam page1_i97.size = 1;

  rsmd0805 page1_i98  (.a({glbl.vtt}),
	.b(clock100l));

  rsmd0805 page1_i99  (.a({glbl.vtt}),
	.b(clock100h));

  rsmd0805 page1_i100  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i95_in1_1));

  rsmd0805 page1_i101  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i95_in1));

  rsmd0805 page1_i103  (.a({glbl.vtt}),
	.b(bckpclock100h));

  rsmd0805 page1_i104  (.a({glbl.vtt}),
	.b(bckpclock100l));

  rsmd0805 page1_i105  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i94_in2));

  rsmd0805 page1_i106  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i94_in2_1));

  \10e116  page1_i107  (.a(unnamed_1_10e116_i107_a),
	.\b* (unnamed_1_10e116_i107_b),
	.ref(vbb),
	.y(unnamed_1_10e116_i107_y),
	.\y* (unnamed_1_10e116_i107_y_1));
  defparam page1_i107.size = 1;

  rsmd0805 page1_i108  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i107_b));

  rsmd0805 page1_i109  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i107_a));

  \10e116  page1_i110  (.a(unnamed_1_100el05_i64_in2_1),
	.\b* (unnamed_1_100el05_i64_in2),
	.ref(vbb),
	.y(bckpclock2h),
	.\y* (bckpclock2l));
  defparam page1_i110.size = 1;

  \10e101  page1_i111  (.a(unnamed_1_100el05_i95_out),
	.b(/* unconnected */),
	.c(/* unconnected */),
	.d(unnamed_1_100el05_i94_out),
	.y(unnamed_1_10e101_i111_y),
	.\y* (unnamed_1_10e101_i111_y_1));
  defparam page1_i111.size = 1;

  rsmd0805 page1_i112  (.a(unnamed_1_100el05_i94_out),
	.b(unnamed_1_ledl_i205_a));

  rsmd0805 page1_i113  (.a(unnamed_1_100el05_i95_out),
	.b(unnamed_1_ledl_i204_a));

  rsmd0805 page1_i117  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i94_out));

  rsmd0805 page1_i118  (.a({glbl.vtt}),
	.b(unnamed_1_100el05_i95_out));

  \10e116  page1_i119  (.a(unnamed_1_10e116_i119_a),
	.\b* (unnamed_1_10e116_i119_b),
	.ref(/* unconnected */),
	.y(clk100_outh),
	.\y* (clk100_outl));
  defparam page1_i119.size = 1;

  \10h125  page1_i120  (.a(unnamed_1_10e101_i123_y_1),
	.\b* (unnamed_1_10e101_i123_y),
	.v(/* unconnected */),
	.y(ttl_reset));
  defparam page1_i120.size = 1;

  \10e101  page1_i123  (.a({glbl.mstreset_ecl}),
	.b(unnamed_1_10e101_i123_b),
	.c(/* unconnected */),
	.d(unnamed_1_10e101_i123_d),
	.y(unnamed_1_10e101_i123_y_1),
	.\y* (unnamed_1_10e101_i123_y));
  defparam page1_i123.size = 1;

  rsmd0805 page1_i125  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i123_b));

  \10e116  page1_i126  (.a(unnamed_1_10e101_i123_y_1),
	.\b* (unnamed_1_10e101_i123_y),
	.ref(/* unconnected */),
	.y(ecl_reset),
	.\y* (/* unconnected */));
  defparam page1_i126.size = 1;

  rsmd0805 page1_i127  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i123_y));

  rsmd0805 page1_i128  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i123_y_1));

  rsmd0805 page1_i129  (.a({glbl.vtt}),
	.b(ecl_reset));

  \100el34  page1_i130  (.clk(clock100h),
	.\clk* (clock100l),
	.\en* (glbl.gnd),
	.mr(/* unconnected */),
	.nc(/* unconnected */),
	.out2(unnamed_1_100el34_i130_out2),
	.\out2* (unnamed_1_100el34_i130_out2_1),
	.out4(unnamed_1_100el34_i130_out4_1),
	.\out4* (unnamed_1_100el34_i130_out4),
	.out8(unnamed_1_100el34_i130_out8_1),
	.\out8* (unnamed_1_100el34_i130_out8),
	.vbb(/* unconnected */));

  testpoint_l page1_i131  (.a(unnamed_1_10e101_i123_d));

  testpoint_l page1_i132  (.a(unnamed_1_10e116_i119_a));

  testpoint_l page1_i133  (.a(unnamed_1_10e116_i119_b));

  testpoint_l page1_i137  (.a(unnamed_1_10e101_i111_y_1));

  testpoint_l page1_i138  (.a(clock100h));

  testpoint_l page1_i139  (.a(unnamed_1_10e101_i111_y));

  testpoint_l page1_i140  (.a(bckpclock2h));

  testpoint_l page1_i143  (.a(glbl.vih));

  rsmd0805 page1_i147  (.a({glbl.vcc}),
	.b(unnamed_1_csmd0805_i148_b));

  csmd0805 page1_i148  (.a({glbl.gnd}),
	.b(unnamed_1_csmd0805_i148_b));

  \10h125  page1_i149  (.a(unnamed_1_10e116_i107_y),
	.\b* (unnamed_1_10e116_i107_y_1),
	.v(/* unconnected */),
	.y(missedclock));
  defparam page1_i149.size = 1;

  rsmd0805 page1_i154  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i111_y_1));

  rsmd0805 page1_i155  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i111_y));

  rsmd0805 page1_i156  (.a({glbl.vtt}),
	.b(bckpclock2l));

  rsmd0805 page1_i157  (.a({glbl.vtt}),
	.b(bckpclock2h));

  rsmd0805 page1_i160  (.a({glbl.vtt}),
	.b(bckpclock100l));

  rsmd0805 page1_i161  (.a({glbl.vtt}),
	.b(bckpclock100h));

  csmd0805 page1_i163  (.a({glbl.gnd}),
	.b(unnamed_1_10h116_i214_b));

  csmd0805 page1_i165  (.a({glbl.gnd}),
	.b(unnamed_1_10h116_i214_b));

  testpoint_l page1_i166  (.a(unnamed_1_100el34_i130_out2));

  testpoint_l page1_i167  (.a(unnamed_1_100el34_i130_out2_1));

  testpoint_l page1_i168  (.a(unnamed_1_100el34_i130_out4_1));

  testpoint_l page1_i169  (.a(unnamed_1_100el34_i130_out4));

  testpoint_l page1_i170  (.a(unnamed_1_100el34_i130_out8_1));

  testpoint_l page1_i171  (.a(unnamed_1_100el34_i130_out8));

  testpoint_l page1_i172  (.a(unnamed_1_10h125_i38_a));

  testpoint_l page1_i173  (.a(unnamed_1_10h125_i38_b));

  \74f164  page1_i182  (.cp(sr_clk),
	.dsa(data),
	.dsb(le),
	.\mr* (/* unconnected */),
	.q0(unnamed_1_74f164_i182_q0),
	.q1(unnamed_1_74f164_i182_q1),
	.q2(unnamed_1_74f164_i182_q2),
	.q3(unnamed_1_74f164_i182_q3),
	.q4(unnamed_1_74f164_i182_q4),
	.q5(unnamed_1_74f164_i182_q5),
	.q6(unnamed_1_74f164_i182_q6),
	.q7(unnamed_1_74f164_i182_q7),
	.q(/* unconnected */));

  testpoint_l page1_i184  (.a(unnamed_1_74f164_i182_q0));

  testpoint_l page1_i185  (.a(unnamed_1_74f164_i182_q1));

  testpoint_l page1_i186  (.a(unnamed_1_74f164_i182_q2));

  testpoint_l page1_i187  (.a(unnamed_1_74f164_i182_q3));

  testpoint_l page1_i188  (.a(unnamed_1_74f164_i182_q4));

  testpoint_l page1_i189  (.a(unnamed_1_74f164_i182_q5));

  testpoint_l page1_i190  (.a(unnamed_1_74f164_i182_q6));

  testpoint_l page1_i191  (.a(unnamed_1_74f164_i182_q7));

  mc10h104 page1_i192  (.a(unnamed_1_10e016_i58_tc),
	.b(unnamed_1_10e131_i71_q),
	.y(unnamed_1_10e016_i58_ce));

  mc10h124 page1_i193  (.common(glbl.vcc),
	.in(unnamed_1_f273_i50_cp),
	.out(unnamed_1_100el05_i64_in1_1),
	.\out* (unnamed_1_100el05_i64_in1));

  mc10h124 page1_i194  (.common(glbl.vcc),
	.in(unnamed_1_74f164_i182_q7),
	.out(unnamed_1_8merge_i183_h),
	.\out* (/* unconnected */));

  mc10h124 page1_i195  (.common(glbl.vcc),
	.in(unnamed_1_74f164_i182_q0),
	.out(unnamed_1_8merge_i183_a),
	.\out* (/* unconnected */));

  mc10h124 page1_i196  (.common(glbl.vcc),
	.in(unnamed_1_74f164_i182_q1),
	.out(unnamed_1_8merge_i183_b),
	.\out* (/* unconnected */));

  mc10h124 page1_i197  (.common(glbl.vcc),
	.in(unnamed_1_74f164_i182_q2),
	.out(unnamed_1_8merge_i183_c),
	.\out* (/* unconnected */));

  mc10h124 page1_i198  (.common(glbl.vcc),
	.in(unnamed_1_74f164_i182_q3),
	.out(unnamed_1_8merge_i183_d),
	.\out* (/* unconnected */));

  mc10h124 page1_i199  (.common(glbl.vcc),
	.in(unnamed_1_74f164_i182_q4),
	.out(unnamed_1_8merge_i183_e),
	.\out* (/* unconnected */));

  mc10h124 page1_i200  (.common(glbl.vcc),
	.in(unnamed_1_74f164_i182_q5),
	.out(unnamed_1_8merge_i183_f),
	.\out* (/* unconnected */));

  mc10h124 page1_i201  (.common(glbl.vcc),
	.in(unnamed_1_74f164_i182_q6),
	.out(unnamed_1_8merge_i183_g),
	.\out* (/* unconnected */));

  mc10h124 page1_i202  (.common(glbl.vcc),
	.in(data_rdy),
	.out(/* unconnected */),
	.\out* (unnamed_1_10e016_i58_pe));

  mc10h124 page1_i203  (.common(glbl.vcc),
	.in(clockgood),
	.out(unnamed_1_10e101_i123_b),
	.\out* (/* unconnected */));

  led_l page1_i204  (.a(unnamed_1_ledl_i204_a),
	.b(glbl.gnd));

  led_l page1_i205  (.a(unnamed_1_ledl_i205_a),
	.b(glbl.gnd));

  led_l page1_i206  (.a(unnamed_1_ledl_i206_a),
	.b(glbl.gnd));

  led_l page1_i207  (.a(unnamed_1_ledl_i207_a),
	.b(glbl.gnd));

  testpoint_l page1_i209  (.a(unnamed_1_10h125_i38_b));

  testpoint_l page1_i210  (.a(unnamed_1_10h125_i38_b));

  testpoint_l page1_i211  (.a(unnamed_1_10h125_i38_a));

  testpoint_l page1_i212  (.a(unnamed_1_10h125_i38_a));

  \10h116  page1_i214  (.a(default_clk),
	.\b* (unnamed_1_10h116_i214_b),
	.v(unnamed_1_10h116_i214_b),
	.y(clock100h),
	.\y* (clock100l));
  defparam page1_i214.section = 1;
  defparam page1_i214.size = 1;

  \10h116  page1_i215  (.a(bckp_clk),
	.\b* (unnamed_1_10h116_i214_b),
	.v(unnamed_1_10h116_i214_b),
	.y(unnamed_1_100el05_i64_in2_1),
	.\y* (unnamed_1_100el05_i64_in2));
  defparam page1_i215.section = 1;
  defparam page1_i215.size = 1;

endmodule // tubii_time(sch_1) 
