// generated by newgenasym  Tue Mar 29 11:58:31 2011


module nm93cs06 (cs, di, do, gnd, pe, pre, sk, vcc);
    input cs;
    input di;
    output do;
    inout gnd;
    input pe;
    input pre;
    input sk;
    inout vcc;


    initial
        begin
        end

endmodule
