// generated by newgenasym  Thu Aug 21 17:29:42 2014


module caen_mux (data, le, \output , sel);
    input [0:15] data;
    input le;
    output \output ;
    input [0:3] sel;


    initial
        begin
        end

endmodule
