-- generated by newgenasym Thu Aug 21 17:29:42 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_mux is
    port (    
	DATA:      IN     STD_LOGIC_VECTOR (0 TO 15);    
	LE:        IN     STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC;    
	SEL:       IN     STD_LOGIC_VECTOR (0 TO 3));
end caen_mux;
