// generated by newgenasym  Tue Mar 29 11:56:10 2011


module \2n3904_size  (b, c, e);
    parameter    size = 1;
    inout [size-1:0] b;
    inout [size-1:0] c;
    inout [size-1:0] e;


    initial
        begin
        end

endmodule
