// generated by newgenasym  Tue Mar 29 11:57:44 2011


module lf356_l (nin, nvss, out, pin, pvss);
    input nin;
    inout nvss;
    output out;
    input pin;
    inout pvss;


    initial
        begin
        end

endmodule
