// generated by newgenasym  Fri Aug 22 18:43:50 2014


module hct374 (clk, \clr* , d, q);
    input clk;
    input \clr* ;
    input d;
    output q;


    initial
        begin
        end

endmodule
