// generated by newgenasym  Tue Mar 29 11:59:06 2011


module tlc271 (g, nin, out, pin, vdd);
    input g;
    inout nin;
    inout out;
    inout pin;
    input vdd;


    initial
        begin
        end

endmodule
