-- generated by newgenasym Tue Mar 29 11:59:06 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TLC271 is
    port (    
	G:         IN     STD_LOGIC;    
	NIN:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	PIN:       INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end TLC271;
