// generated by newgenasym  Tue Mar 29 12:00:17 2011


module ad9048 (agnd1, agnd2, ain, convert, d1, d2, d3, d4, d5, d6, d7, d8,
        dgnd1, dgnd2, nlinv, nminv, rb, rm, rt, vcc1, vcc2, vee1, vee2,
        vee3);
    inout agnd1;
    inout agnd2;
    inout ain;
    input convert;
    output d1;
    output d2;
    output d3;
    output d4;
    output d5;
    output d6;
    output d7;
    output d8;
    input dgnd1;
    input dgnd2;
    input nlinv;
    input nminv;
    input rb;
    input rm;
    input rt;
    input vcc1;
    input vcc2;
    input vee1;
    input vee2;
    input vee3;


    initial
        begin
        end

endmodule
