// generated by newgenasym  Tue Mar 29 12:00:31 2011


module max674a (\10vin , \20vin , a0, agnd, bipoff, ce, \cs* , d0, d1, d10, d11, d2,
        d3, d4, d5, d6, d7, d8, d9, dgnd, mode12_8, \rc* , refin, refout,
        sts);
    inout \10vin ;
    inout \20vin ;
    input a0;
    inout agnd;
    inout bipoff;
    input ce;
    input \cs* ;
    output d0;
    output d1;
    output d10;
    output d11;
    output d2;
    output d3;
    output d4;
    output d5;
    output d6;
    output d7;
    output d8;
    output d9;
    input dgnd;
    input mode12_8;
    input \rc* ;
    inout refin;
    inout refout;
    output sts;


    initial
        begin
        end

endmodule
