-- generated by newgenasym Tue Mar 29 12:00:31 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX674A is
    port (    
	\10vin\:   INOUT  STD_LOGIC;    
	\20vin\:   INOUT  STD_LOGIC;    
	A0:        IN     STD_LOGIC;    
	AGND:      INOUT  STD_LOGIC;    
	BIPOFF:    INOUT  STD_LOGIC;    
	CE:        IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	D0:        OUT    STD_LOGIC;    
	D1:        OUT    STD_LOGIC;    
	D10:       OUT    STD_LOGIC;    
	D11:       OUT    STD_LOGIC;    
	D2:        OUT    STD_LOGIC;    
	D3:        OUT    STD_LOGIC;    
	D4:        OUT    STD_LOGIC;    
	D5:        OUT    STD_LOGIC;    
	D6:        OUT    STD_LOGIC;    
	D7:        OUT    STD_LOGIC;    
	D8:        OUT    STD_LOGIC;    
	D9:        OUT    STD_LOGIC;    
	DGND:      IN     STD_LOGIC;    
	MODE12_8:  IN     STD_LOGIC;    
	\rc*\:     IN     STD_LOGIC;    
	REFIN:     INOUT  STD_LOGIC;    
	REFOUT:    INOUT  STD_LOGIC;    
	STS:       OUT    STD_LOGIC);
end MAX674A;
