// generated by newgenasym  Mon Oct 20 15:52:57 2014


module ports (async_delay_in, async_delay_out, async_pulse_out,
        caen_anpulse, caen_out, dgth, dgtl, ext_ped_in,
        ext_ped_out, fast_anpulse, fast_comp_outh,
        fast_comp_outl, gtrigh_ecl, gtrigl_ecl, lockout, \lockout* ,
        \mtcd_lo* , scope_out, sync24h_ecl, sync24h_lvds,
        sync24l_ecl, sync24l_lvds, sync_delay_in, sync_delay_out,
        sync_pulse_out, synch_ecl, synch_lvds, syncl_ecl,
        syncl_lvds, tune_anpulse, tune_comp_outh, tune_comp_outl);
    input async_delay_in;
    input async_delay_out;
    input async_pulse_out;
    input [11:0] caen_anpulse;
    input [7:0] caen_out;
    input dgth;
    input dgtl;
    input ext_ped_in;
    input ext_ped_out;
    input fast_anpulse;
    input fast_comp_outh;
    input fast_comp_outl;
    input gtrigh_ecl;
    input gtrigl_ecl;
    input lockout;
    input \lockout* ;
    input \mtcd_lo* ;
    input [7:0] scope_out;
    input sync24h_ecl;
    input sync24h_lvds;
    input sync24l_ecl;
    input sync24l_lvds;
    input sync_delay_in;
    input sync_delay_out;
    input sync_pulse_out;
    input synch_ecl;
    input synch_lvds;
    input syncl_ecl;
    input syncl_lvds;
    input tune_anpulse;
    input tune_comp_outh;
    input tune_comp_outl;


    initial
        begin
        end

endmodule
