// generated by newgenasym  Wed Feb 25 10:35:43 2015


module ports (async_delay_in, async_delay_out, async_pulse_out,
        caen_anpulse, caen_out, dgt_n, dgt_p, ext_ped_in,
        ext_ped_out, fast_anpulse, fast_comp_out_n,
        fast_comp_out_p, gt_ecl_n, gt_ecl_p, lockout, \lockout* ,
        \mtcd_lo* , scope_out, sync24_ecl_n, sync24_ecl_p,
        sync24_lvds_n, sync24_lvds_p, sync_delay_in,
        sync_delay_out, sync_ecl_n, sync_ecl_p, sync_lvds_n,
        sync_lvds_p, sync_pulse_out, tune_anpulse,
        tune_comp_out_n, tune_comp_out_p);
    input async_delay_in;
    input async_delay_out;
    input async_pulse_out;
    input [11:0] caen_anpulse;
    input [7:0] caen_out;
    input dgt_n;
    input dgt_p;
    input ext_ped_in;
    input ext_ped_out;
    input fast_anpulse;
    input fast_comp_out_n;
    input fast_comp_out_p;
    input gt_ecl_n;
    input gt_ecl_p;
    input lockout;
    input \lockout* ;
    input \mtcd_lo* ;
    input [7:0] scope_out;
    input sync24_ecl_n;
    input sync24_ecl_p;
    input sync24_lvds_n;
    input sync24_lvds_p;
    input sync_delay_in;
    input sync_delay_out;
    input sync_ecl_n;
    input sync_ecl_p;
    input sync_lvds_n;
    input sync_lvds_p;
    input sync_pulse_out;
    input tune_anpulse;
    input tune_comp_out_n;
    input tune_comp_out_p;


    initial
        begin
        end

endmodule
