-- generated by newgenasym Wed Feb 25 10:35:43 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ports is
    port (    
	ASYNC_DELAY_IN: IN     STD_LOGIC;    
	ASYNC_DELAY_OUT: IN     STD_LOGIC;    
	ASYNC_PULSE_OUT: IN     STD_LOGIC;    
	CAEN_ANPULSE: IN     STD_LOGIC_VECTOR (11 DOWNTO 0);    
	CAEN_OUT:  IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	DGT_N:     IN     STD_LOGIC;    
	DGT_P:     IN     STD_LOGIC;    
	EXT_PED_IN: IN     STD_LOGIC;    
	EXT_PED_OUT: IN     STD_LOGIC;    
	FAST_ANPULSE: IN     STD_LOGIC;    
	FAST_COMP_OUT_N: IN     STD_LOGIC;    
	FAST_COMP_OUT_P: IN     STD_LOGIC;    
	GT_ECL_N:  IN     STD_LOGIC;    
	GT_ECL_P:  IN     STD_LOGIC;    
	LOCKOUT:   IN     STD_LOGIC;    
	\lockout*\: IN     STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC;    
	SCOPE_OUT: IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	SYNC24_ECL_N: IN     STD_LOGIC;    
	SYNC24_ECL_P: IN     STD_LOGIC;    
	SYNC24_LVDS_N: IN     STD_LOGIC;    
	SYNC24_LVDS_P: IN     STD_LOGIC;    
	SYNC_DELAY_IN: IN     STD_LOGIC;    
	SYNC_DELAY_OUT: IN     STD_LOGIC;    
	SYNC_ECL_N: IN     STD_LOGIC;    
	SYNC_ECL_P: IN     STD_LOGIC;    
	SYNC_LVDS_N: IN     STD_LOGIC;    
	SYNC_LVDS_P: IN     STD_LOGIC;    
	SYNC_PULSE_OUT: IN     STD_LOGIC;    
	TUNE_ANPULSE: IN     STD_LOGIC;    
	TUNE_COMP_OUT_N: IN     STD_LOGIC;    
	TUNE_COMP_OUT_P: IN     STD_LOGIC);
end ports;
