-- generated by newgenasym Wed Oct 08 11:47:45 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ports is
    port (    
	ASYNC_DELAY_IN: IN     STD_LOGIC;    
	ASYNC_DELAY_OUT: IN     STD_LOGIC;    
	ASYNC_PULSE_OUT: IN     STD_LOGIC;    
	CAEN_OUT:  IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	DGTH:      IN     STD_LOGIC;    
	DGTL:      IN     STD_LOGIC;    
	EXT_PED_IN: IN     STD_LOGIC;    
	EXT_PED_OUT: IN     STD_LOGIC;    
	FAST_ANPULSE: IN     STD_LOGIC;    
	FAST_COMP_OUTH: IN     STD_LOGIC;    
	FAST_COMP_OUTL: IN     STD_LOGIC;    
	GTRIGH_ECL: IN     STD_LOGIC;    
	GTRIGL_ECL: IN     STD_LOGIC;    
	LOCKOUT:   IN     STD_LOGIC;    
	\lockout*\: IN     STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC;    
	SCOPE_OUT: IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	SYNC24H_ECL: IN     STD_LOGIC;    
	SYNC24H_LVDS: IN     STD_LOGIC;    
	SYNC24L_ECL: IN     STD_LOGIC;    
	SYNC24L_LVDS: IN     STD_LOGIC;    
	SYNC_DELAY_IN: IN     STD_LOGIC;    
	SYNC_DELAY_OUT: IN     STD_LOGIC;    
	SYNC_PULSE_OUT: IN     STD_LOGIC;    
	SYNCH_ECL: IN     STD_LOGIC;    
	SYNCH_LVDS: IN     STD_LOGIC;    
	SYNCL_ECL: IN     STD_LOGIC;    
	SYNCL_LVDS: IN     STD_LOGIC;    
	TUNE_ANPULSE: IN     STD_LOGIC;    
	TUNE_COMP_OUTH: IN     STD_LOGIC;    
	TUNE_COMP_OUTL: IN     STD_LOGIC);
end ports;
