// generated by newgenasym  Tue Mar 29 11:58:57 2011


module snoint2 (c1h, c1l, c2h, c2l, c3h, c3l, c4h, c4l, gnd, gnd1h, gnd1l,
        gnd2h, gnd2l, gnd3h, gnd3l, gnd4h, gnd4l, ing1h, ing1l, ing2h,
        ing2l, ing3h, ing3l, ing4h, ing4l, nc1, nc2, nc3, nc4, nc5, nc6,
        outsum_hi, outsum_lo, p4beh, p4bel, q1h, q1l, q2h, q2l, q3h,
        q3l, q4h, q4l, sub1, sub2, sub3, vbal1h, vbal1l, vbal2h,
        vbal2l, vbal3h, vbal3l, vbal4h, vbal4l, vcc1, vcc2, vcc3,
        vdmp1, vdmp2, vee1, vee2, vee3, xiadj1, xiadj2);
    inout c1h;
    inout c1l;
    inout c2h;
    inout c2l;
    inout c3h;
    inout c3l;
    inout c4h;
    inout c4l;
    input gnd;
    input gnd1h;
    input gnd1l;
    input gnd2h;
    input gnd2l;
    input gnd3h;
    input gnd3l;
    input gnd4h;
    input gnd4l;
    inout ing1h;
    inout ing1l;
    inout ing2h;
    inout ing2l;
    inout ing3h;
    inout ing3l;
    inout ing4h;
    inout ing4l;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout outsum_hi;
    inout outsum_lo;
    inout p4beh;
    inout p4bel;
    inout q1h;
    inout q1l;
    inout q2h;
    inout q2l;
    inout q3h;
    inout q3l;
    inout q4h;
    inout q4l;
    inout sub1;
    inout sub2;
    input sub3;
    inout vbal1h;
    inout vbal1l;
    inout vbal2h;
    inout vbal2l;
    inout vbal3h;
    inout vbal3l;
    inout vbal4h;
    inout vbal4l;
    input vcc1;
    input vcc2;
    input vcc3;
    input vdmp1;
    input vdmp2;
    input vee1;
    input vee2;
    input vee3;
    inout xiadj1;
    inout xiadj2;


    initial
        begin
        end

endmodule
