-- generated by newgenasym Fri Sep 26 11:33:39 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity latchexttrig is
    port (    
	EXTTRIG:   OUT    STD_LOGIC_VECTOR (15 DOWNTO 0));
end latchexttrig;
