// generated by newgenasym  Tue Mar 29 11:56:37 2011


module \7915s_l  (ground, \input , \output );
    inout ground;
    input \input ;
    output \output ;


    initial
        begin
        end

endmodule
