-- generated by newgenasym Tue Mar 29 11:57:40 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LDR1201_L is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC);
end LDR1201_L;
