-- generated by newgenasym Tue Mar 29 11:59:51 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HFBR_1312T is
    port (    
	ANODE:     IN     STD_LOGIC;    
	\case\:    IN     STD_LOGIC;    
	CATHODE:   IN     STD_LOGIC);
end HFBR_1312T;
