`timescale 1ns/1ns

module tubii_triggers (rawtrigs, tubii_rt );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:11 2015
// from tubii_lib/TUBII_TRIGGERS/sch_1

  inout [0:3] rawtrigs;
  inout  tubii_rt;
  // global signal glbl.gnd;
  // global signal glbl.vtt;

  wire  unnamed_1_10h125_i125_a;
  wire  unnamed_1_10h125_i125_b;
  wire  unnamed_1_10h125_i125_y;
  wire  unnamed_1_10h125_i126_a;
  wire  unnamed_1_10h125_i126_b;
  wire  unnamed_1_10h125_i126_y;
  wire  unnamed_1_10h125_i127_a;
  wire  unnamed_1_10h125_i127_b;
  wire  unnamed_1_10h125_i127_y;
  wire  unnamed_1_10h125_i128_a;
  wire  unnamed_1_10h125_i128_b;
  wire  unnamed_1_10h125_i128_y;
  wire  unnamed_1_f07_i134_y;

  wire  gnd;
  wire  page1_gnd;
  wire [0:3] page1_rawtrigs;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign page1_rawtrigs[3:3] = rawtrigs[3:3];
  assign page1_rawtrigs[2:2] = rawtrigs[2:2];
  assign page1_rawtrigs[1:1] = rawtrigs[1:1];
  assign page1_rawtrigs[0:0] = rawtrigs[0:0];
  assign page1_rawtrigs[0:3] = rawtrigs[0:3];
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;
  assign unnamed_1_10h125_i125_y = rawtrigs[3:3];
  assign unnamed_1_10h125_i126_y = rawtrigs[0:0];
  assign unnamed_1_10h125_i127_y = rawtrigs[1:1];
  assign unnamed_1_10h125_i128_y = rawtrigs[2:2];

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  csmd0805 page1_i4  (.a({glbl.gnd}),
	.b(unnamed_1_10h125_i126_b));

  testpoint_l page1_i6  (.a(unnamed_1_10h125_i126_a));

  testpoint_l page1_i7  (.a(glbl.gnd));

  rsmd0805 page1_i12  (.a({glbl.vtt}),
	.b(unnamed_1_10h125_i126_a));

  csmd0805 page1_i14  (.a({glbl.gnd}),
	.b(unnamed_1_10h125_i127_b));

  rsmd0805 page1_i21  (.a({glbl.vtt}),
	.b(unnamed_1_10h125_i127_a));

  rsmd0805 page1_i25  (.a({glbl.vtt}),
	.b(unnamed_1_10h125_i128_a));

  testpoint_l page1_i27  (.a(unnamed_1_10h125_i127_a));

  testpoint_l page1_i28  (.a(glbl.gnd));

  testpoint_l page1_i30  (.a(unnamed_1_10h125_i128_a));

  testpoint_l page1_i31  (.a(glbl.gnd));

  csmd0805 page1_i36  (.a({glbl.gnd}),
	.b(unnamed_1_10h125_i125_b));

  rsmd0805 page1_i38  (.a({glbl.vtt}),
	.b(unnamed_1_10h125_i125_a));

  testpoint_l page1_i40  (.a(unnamed_1_10h125_i125_a));

  testpoint_l page1_i41  (.a(glbl.gnd));

  testpoint_l page1_i116  (.a(glbl.gnd));

  testpoint_l page1_i122  (.a(unnamed_1_f07_i134_y));

  \10h125  page1_i125  (.a(unnamed_1_10h125_i125_a),
	.\b* (unnamed_1_10h125_i125_b),
	.v(unnamed_1_10h125_i125_b),
	.y(unnamed_1_10h125_i125_y));
  defparam page1_i125.size = 1;

  \10h125  page1_i126  (.a(unnamed_1_10h125_i126_a),
	.\b* (unnamed_1_10h125_i126_b),
	.v(unnamed_1_10h125_i126_b),
	.y(unnamed_1_10h125_i126_y));
  defparam page1_i126.size = 1;

  \10h125  page1_i127  (.a(unnamed_1_10h125_i127_a),
	.\b* (unnamed_1_10h125_i127_b),
	.v(unnamed_1_10h125_i127_b),
	.y(unnamed_1_10h125_i127_y));
  defparam page1_i127.size = 1;

  \10h125  page1_i128  (.a(unnamed_1_10h125_i128_a),
	.\b* (unnamed_1_10h125_i128_b),
	.v(unnamed_1_10h125_i128_b),
	.y(unnamed_1_10h125_i128_y));
  defparam page1_i128.size = 1;

  csmd0805 page1_i129  (.a({glbl.gnd}),
	.b(unnamed_1_10h125_i128_b));

  f07 page1_i134  (.a(tubii_rt),
	.y(unnamed_1_f07_i134_y));
  defparam page1_i134.size = 1;

  led_pulse page1_i138  (.pulse_in(tubii_rt));

endmodule // tubii_triggers(sch_1) 
