-- generated by newgenasym Tue Mar 29 11:57:06 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CONN32 is
    port (    
	P1:        OUT    STD_LOGIC;    
	P10:       OUT    STD_LOGIC;    
	P11:       OUT    STD_LOGIC;    
	P12:       OUT    STD_LOGIC;    
	P13:       OUT    STD_LOGIC;    
	P14:       OUT    STD_LOGIC;    
	P15:       OUT    STD_LOGIC;    
	P16:       OUT    STD_LOGIC;    
	P17:       OUT    STD_LOGIC;    
	P18:       OUT    STD_LOGIC;    
	P19:       OUT    STD_LOGIC;    
	P2:        OUT    STD_LOGIC;    
	P20:       OUT    STD_LOGIC;    
	P21:       OUT    STD_LOGIC;    
	P22:       OUT    STD_LOGIC;    
	P23:       OUT    STD_LOGIC;    
	P24:       OUT    STD_LOGIC;    
	P25:       OUT    STD_LOGIC;    
	P26:       OUT    STD_LOGIC;    
	P27:       OUT    STD_LOGIC;    
	P28:       OUT    STD_LOGIC;    
	P29:       OUT    STD_LOGIC;    
	P3:        OUT    STD_LOGIC;    
	P30:       OUT    STD_LOGIC;    
	P31:       OUT    STD_LOGIC;    
	P32:       OUT    STD_LOGIC;    
	P4:        OUT    STD_LOGIC;    
	P5:        OUT    STD_LOGIC;    
	P6:        OUT    STD_LOGIC;    
	P7:        OUT    STD_LOGIC;    
	P8:        OUT    STD_LOGIC;    
	P9:        OUT    STD_LOGIC);
end CONN32;
