// generated by newgenasym  Tue Aug 19 17:06:10 2014


module caen_buffer (ctrl, in, out, out_att);
    input ctrl;
    input in;
    output out;
    output out_att;


    initial
        begin
        end

endmodule
