-- generated by newgenasym Tue Aug 19 17:06:10 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_buffer is
    port (    
	CTRL:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	OUT_ATT:   OUT    STD_LOGIC);
end caen_buffer;
