-- generated by newgenasym Tue Mar 29 11:59:55 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity IDS_C14 is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN10:     INOUT  STD_LOGIC;    
	PIN11:     INOUT  STD_LOGIC;    
	PIN12:     INOUT  STD_LOGIC;    
	PIN13:     INOUT  STD_LOGIC;    
	PIN14:     INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      INOUT  STD_LOGIC;    
	PIN5:      INOUT  STD_LOGIC;    
	PIN6:      INOUT  STD_LOGIC;    
	PIN7:      INOUT  STD_LOGIC;    
	PIN8:      INOUT  STD_LOGIC;    
	PIN9:      INOUT  STD_LOGIC);
end IDS_C14;
