// generated by newgenasym  Tue Jun 28 18:18:38 2011


module ttl_progdelay (bus, delay_ie, delay_oe, ecl_clockinh, ecl_clockinl,
        ecl_pulseinh, ecl_pulseinl, ecl_pulseouth, ecl_pulseoutl,
        mstreset_ttl, ploadenable_ttl);
    input [7:0] bus;
    input delay_ie;
    input delay_oe;
    input ecl_clockinh;
    input ecl_clockinl;
    input ecl_pulseinh;
    input ecl_pulseinl;
    input ecl_pulseouth;
    input ecl_pulseoutl;
    input mstreset_ttl;
    input ploadenable_ttl;


    initial
        begin
        end

endmodule
