-- generated by newgenasym Tue Mar 29 11:57:59 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LT1364 is
    port (    
	IN1_N:     INOUT  STD_LOGIC;    
	IN1_P:     INOUT  STD_LOGIC;    
	IN2_N:     INOUT  STD_LOGIC;    
	IN2_P:     INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	V15_N:     INOUT  STD_LOGIC;    
	V15_P:     INOUT  STD_LOGIC);
end LT1364;
