`timescale 1ns/1ns

module ellie_talk (delay_in, delay_out, pulse_out );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:10 2015
// from tubii_lib/ELLIE_TALK/sch_1

  inout  delay_in;
  inout  delay_out;
  inout  pulse_out;
  // global signal glbl.vcc;
  // global signal glbl.vtt;

  wire  unnamed_1_10e116_i9_a;
  wire  unnamed_1_10e116_i9_b;
  wire  unnamed_1_10e116_i9_y;
  wire  unnamed_1_10e116_i9_y_1;
  wire  unnamed_1_mc10h124_i24_out;
  wire  unnamed_1_mc10h124_i24_out_1;
  wire  unnamed_1_mc10h124_i25_out;
  wire  unnamed_1_mc10h124_i25_out_1;

  wire  vcc;
  wire  page1_vcc;
  wire  vtt;
  wire  page1_vtt;

  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

// begin instances 

  testpoint_l page1_i3  (.a(unnamed_1_mc10h124_i24_out));

  testpoint_l page1_i4  (.a(unnamed_1_mc10h124_i24_out_1));

  testpoint_l page1_i5  (.a(unnamed_1_mc10h124_i25_out));

  testpoint_l page1_i6  (.a(unnamed_1_mc10h124_i25_out_1));

  testpoint_l page1_i7  (.a(unnamed_1_10e116_i9_a));

  testpoint_l page1_i8  (.a(unnamed_1_10e116_i9_b));

  \10e116  page1_i9  (.a(unnamed_1_10e116_i9_a),
	.\b* (unnamed_1_10e116_i9_b),
	.ref(/* unconnected */),
	.y(unnamed_1_10e116_i9_y),
	.\y* (unnamed_1_10e116_i9_y_1));
  defparam page1_i9.size = 1;

  \10h125  page1_i10  (.a(unnamed_1_10e116_i9_y),
	.\b* (unnamed_1_10e116_i9_y_1),
	.v(/* unconnected */),
	.y(delay_in));
  defparam page1_i10.size = 1;

  rsmd0805 page1_i11  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i9_y));

  rsmd0805 page1_i12  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i9_y_1));

  rsmd0805 page1_i13  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i9_b));

  rsmd0805 page1_i14  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i9_a));

  rsmd0805 page1_i15  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h124_i25_out));

  rsmd0805 page1_i16  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h124_i25_out_1));

  rsmd0805 page1_i19  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h124_i24_out_1));

  rsmd0805 page1_i20  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h124_i24_out));

  led_pulse page1_i22  (.pulse_in(delay_in));

  led_pulse page1_i23  (.pulse_in(pulse_out));

  mc10h124 page1_i24  (.common(glbl.vcc),
	.in(delay_out),
	.out(unnamed_1_mc10h124_i24_out),
	.\out* (unnamed_1_mc10h124_i24_out_1));

  mc10h124 page1_i25  (.common(glbl.vcc),
	.in(pulse_out),
	.out(unnamed_1_mc10h124_i25_out_1),
	.\out* (unnamed_1_mc10h124_i25_out));

endmodule // ellie_talk(sch_1) 
