// generated by newgenasym  Tue Mar 29 11:57:34 2011


module hc4051_l (\inh* , s, vneg, x, x0, x1, x2, x3, x4, x5, x6, x7);
    parameter    size = 1;
    input \inh* ;
    input [2:0] s;
    input vneg;
    inout [size-1:0] x;
    inout [size-1:0] x0;
    inout [size-1:0] x1;
    inout [size-1:0] x2;
    inout [size-1:0] x3;
    inout [size-1:0] x4;
    inout [size-1:0] x5;
    inout [size-1:0] x6;
    inout [size-1:0] x7;


    initial
        begin
        end

endmodule
