-- generated by newgenasym Tue Mar 29 11:57:34 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HC4051_L is
    generic (
        size:positive:= 1
            );
    port (    
	\inh*\:    IN     STD_LOGIC;    
	S:         IN     STD_LOGIC_VECTOR (2 DOWNTO 0);    
	VNEG:      IN     STD_LOGIC;    
	X:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X0:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X1:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X2:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X3:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X4:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X5:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X6:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X7:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end HC4051_L;
