// generated by newgenasym  Tue Mar 29 11:58:49 2011


module sip (p1, p2, p3, p4, p5, p6, p7, p8);
    input p1;
    input p2;
    input p3;
    input p4;
    input p5;
    input p6;
    input p7;
    input p8;


    initial
        begin
        end

endmodule
