-- generated by newgenasym Tue Mar 29 11:58:49 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SIP is
    port (    
	P1:        IN     STD_LOGIC;    
	P2:        IN     STD_LOGIC;    
	P3:        IN     STD_LOGIC;    
	P4:        IN     STD_LOGIC;    
	P5:        IN     STD_LOGIC;    
	P6:        IN     STD_LOGIC;    
	P7:        IN     STD_LOGIC;    
	P8:        IN     STD_LOGIC);
end SIP;
