-- generated by newgenasym Tue Mar 29 11:56:31 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74gtl16612\ is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\ceab*\:   IN     STD_LOGIC;    
	\ceba*\:   IN     STD_LOGIC;    
	CLKAB:     IN     STD_LOGIC;    
	CLKBA:     IN     STD_LOGIC;    
	GND01:     IN     STD_LOGIC;    
	GND02:     IN     STD_LOGIC;    
	GND03:     IN     STD_LOGIC;    
	GND04:     IN     STD_LOGIC;    
	GND05:     IN     STD_LOGIC;    
	GND06:     IN     STD_LOGIC;    
	GND07:     IN     STD_LOGIC;    
	GND08:     IN     STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	GND5:      INOUT  STD_LOGIC;    
	GND6:      INOUT  STD_LOGIC;    
	GND7:      INOUT  STD_LOGIC;    
	GND8:      INOUT  STD_LOGIC;    
	LEAB:      IN     STD_LOGIC;    
	LEBA:      IN     STD_LOGIC;    
	\oeab*\:   IN     STD_LOGIC;    
	\oeba*\:   IN     STD_LOGIC;    
	VCC3_3A:   IN     STD_LOGIC;    
	VCC3_3B:   IN     STD_LOGIC;    
	VCC5:      IN     STD_LOGIC;    
	VREF:      IN     STD_LOGIC);
end \74gtl16612\;
