// generated by newgenasym  Thu May 26 14:27:43 2011


module lvds_driver_ds10 (\1 , \4 , \5 , \in+ , \in- , \out+ , \out- );
    inout \1 ;
    inout \4 ;
    inout \5 ;
    input \in+ ;
    input \in- ;
    output \out+ ;
    output \out- ;


    initial
        begin
        end

endmodule
