-- generated by newgenasym Thu May 26 14:27:43 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lvds_driver_ds10 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\in+\:     IN     STD_LOGIC;    
	\in-\:     IN     STD_LOGIC;    
	\out+\:    OUT    STD_LOGIC;    
	\out-\:    OUT    STD_LOGIC);
end lvds_driver_ds10;
