-- generated by newgenasym Tue Mar 29 11:58:05 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX326 is
    port (    
	C1:        IN     STD_LOGIC;    
	C2:        IN     STD_LOGIC;    
	C3:        IN     STD_LOGIC;    
	C4:        IN     STD_LOGIC;    
	IN1:       IN     STD_LOGIC;    
	IN2:       IN     STD_LOGIC;    
	IN3:       IN     STD_LOGIC;    
	IN4:       IN     STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	OUT2:      OUT    STD_LOGIC;    
	OUT3:      OUT    STD_LOGIC;    
	OUT4:      OUT    STD_LOGIC;    
	VMINUS:    IN     STD_LOGIC;    
	VPLUS:     IN     STD_LOGIC);
end MAX326;
