-- generated by newgenasym Tue Mar 29 11:58:31 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity NM93CS06 is
    port (    
	CS:        IN     STD_LOGIC;    
	DI:        IN     STD_LOGIC;    
	DO:        OUT    STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	PE:        IN     STD_LOGIC;    
	PRE:       IN     STD_LOGIC;    
	SK:        IN     STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end NM93CS06;
