// generated by newgenasym  Thu May 26 14:46:19 2011


module foxclock (ed, nc, out, \out* );
    input ed;
    inout nc;
    output out;
    output \out* ;


    initial
        begin
        end

endmodule
