-- generated by newgenasym Thu May 26 14:46:19 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity foxclock is
    port (    
	ED:        IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	\out*\:    OUT    STD_LOGIC);
end foxclock;
