// generated by newgenasym  Tue Mar 29 11:59:40 2011


module \10h601  (d0, d1, d2, d3, d4, d5, d6, d7, d8, \oeecl* , \oettl* , q0, q1, q2, q3,
        q4, q5, q6, q7, q8);
    input d0;
    input d1;
    input d2;
    input d3;
    input d4;
    input d5;
    input d6;
    input d7;
    input d8;
    input \oeecl* ;
    input \oettl* ;
    output q0;
    output q1;
    output q2;
    output q3;
    output q4;
    output q5;
    output q6;
    output q7;
    output q8;


    initial
        begin
        end

endmodule
