// generated by newgenasym  Mon Sep 29 11:49:47 2014


module ecal_control (ecal_active, ext_ped_in, ext_ped_out, gtrig);
    input ecal_active;
    output ext_ped_in;
    output ext_ped_out;
    input gtrig;


    initial
        begin
        end

endmodule
