// generated by newgenasym  Wed Feb 25 12:49:25 2015


module ecal_control (ecal_active, ext_ped_in, ext_ped_out_p, gtrig);
    input ecal_active;
    output ext_ped_in;
    output ext_ped_out_p;
    input gtrig;


    initial
        begin
        end

endmodule
