-- generated by newgenasym Mon Sep 29 11:49:47 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ecal_control is
    port (    
	ECAL_ACTIVE: IN     STD_LOGIC;    
	EXT_PED_IN: OUT    STD_LOGIC;    
	EXT_PED_OUT: OUT    STD_LOGIC;    
	GTRIG:     IN     STD_LOGIC);
end ecal_control;
