-- generated by newgenasym Wed Feb 25 12:49:25 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ecal_control is
    port (    
	ECAL_ACTIVE: IN     STD_LOGIC;    
	EXT_PED_IN: OUT    STD_LOGIC;    
	EXT_PED_OUT_P: OUT    STD_LOGIC;    
	GTRIG:     IN     STD_LOGIC);
end ecal_control;
