-- generated by newgenasym Tue Mar 29 11:59:38 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h104_l\ is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	C:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	D:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Y0:        OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Y1:        OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y1*\:     OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \10h104_l\;
