// generated by newgenasym  Tue Mar 29 11:58:04 2011


module max183 (agnd, ain1, ain2, \busy* , clkin, clkout, \cs* , d0, d1, d10, d11,
        d2, d3, d4, d5, d6, d7, d8, d9, dgnd, \rd* , vdd, vref, vss);
    input agnd;
    input ain1;
    input ain2;
    output \busy* ;
    input clkin;
    input clkout;
    input \cs* ;
    output d0;
    output d1;
    output d10;
    output d11;
    output d2;
    output d3;
    output d4;
    output d5;
    output d6;
    output d7;
    output d8;
    output d9;
    input dgnd;
    input \rd* ;
    input vdd;
    input vref;
    input vss;


    initial
        begin
        end

endmodule
