-- generated by newgenasym Tue Mar 29 12:00:05 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SMLED is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end SMLED;
