// generated by newgenasym  Fri Sep 19 12:10:57 2014


module bursttrig (bursttrigs, ecal_ttl, rawtrigs);
    input [3:0] bursttrigs;
    input ecal_ttl;
    output [3:0] rawtrigs;


    initial
        begin
        end

endmodule
