-- generated by newgenasym Thu Oct 02 15:47:21 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tubii_spkr is
    port (    
	SPKR_SIGNAL: IN     STD_LOGIC);
end tubii_spkr;
