-- generated by newgenasym Tue Mar 29 11:58:35 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PFUSE is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC);
end PFUSE;
