// generated by newgenasym  Tue Mar 29 11:56:53 2011


module bregst (ba, \bcreg_reg* , bdin, bdout, \bdtack_req* , \bfiforeg_rd* ,
        bfiforeg_sel, \bfiforeg_wr* , bm2, \breg32_63_rd* ,
        \breg32_63_wr* , \breg_rd- , \breg_wr- , bregspace, \bsbread* ,
        bsbselect, bsqcreg_req, bsqreg_sel, btestmode1, cclk,
        \program* , \pwrdwn* , \rdata* , \reset* , rtrig);
    input [10:2] ba;
    output \bcreg_reg* ;
    input bdin;
    output bdout;
    output \bdtack_req* ;
    output \bfiforeg_rd* ;
    output [1:0] bfiforeg_sel;
    output \bfiforeg_wr* ;
    output bm2;
    output \breg32_63_rd* ;
    output \breg32_63_wr* ;
    output [15:0] \breg_rd- ;
    output [15:0] \breg_wr- ;
    input bregspace;
    input \bsbread* ;
    input bsbselect;
    output bsqcreg_req;
    output [2:0] bsqreg_sel;
    input btestmode1;
    input cclk;
    input \program* ;
    input \pwrdwn* ;
    output \rdata* ;
    input \reset* ;
    input rtrig;


    initial
        begin
        end

endmodule
