// generated by newgenasym  Tue Mar 29 11:59:15 2011


module upfct16245 (a, b, \eo1* , \eo2* , \eo3* , \eo4* );
    input [15:0] a;
    output [15:0] b;
    input \eo1* ;
    input \eo2* ;
    output \eo3* ;
    output \eo4* ;


    initial
        begin
        end

endmodule
