// generated by newgenasym  Tue Mar 29 11:56:57 2011


module cgt24 (bbd_cgt_hi, \bcclr* , bcgthack1, bcgthack2, bclk, \benw1* ,
        \benw3* , berr_reset, berr_synclr, berr_synclr24, bfecbusy,
        \bgtrig* , \bsynclr* , \bsynclr24* , bwrflg_memd15, cclk, din,
        dout, es24_memd, es_memd, ispare1, ispare2, m2, ospare1,
        ospare2, p20, p43, p44, \program* , \pwrdwn* , \rdata* , \reset* ,
        rtrig);
    output [7:0] bbd_cgt_hi;
    input \bcclr* ;
    input bcgthack1;
    input bcgthack2;
    input bclk;
    input \benw1* ;
    input \benw3* ;
    input berr_reset;
    output berr_synclr;
    output berr_synclr24;
    input bfecbusy;
    input \bgtrig* ;
    input \bsynclr* ;
    input \bsynclr24* ;
    input bwrflg_memd15;
    input cclk;
    input din;
    output dout;
    output es24_memd;
    output es_memd;
    input ispare1;
    input ispare2;
    output m2;
    output ospare1;
    output ospare2;
    output p20;
    output p43;
    output p44;
    input \program* ;
    input \pwrdwn* ;
    output \rdata* ;
    input \reset* ;
    input rtrig;


    initial
        begin
        end

endmodule
