-- generated by newgenasym Tue Mar 29 11:56:57 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CGT24 is
    port (    
	BBD_CGT_HI: OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\bcclr*\:  IN     STD_LOGIC;    
	BCGTHACK1: IN     STD_LOGIC;    
	BCGTHACK2: IN     STD_LOGIC;    
	BCLK:      IN     STD_LOGIC;    
	\benw1*\:  IN     STD_LOGIC;    
	\benw3*\:  IN     STD_LOGIC;    
	BERR_RESET: IN     STD_LOGIC;    
	BERR_SYNCLR: OUT    STD_LOGIC;    
	BERR_SYNCLR24: OUT    STD_LOGIC;    
	BFECBUSY:  IN     STD_LOGIC;    
	\bgtrig*\: IN     STD_LOGIC;    
	\bsynclr*\: IN     STD_LOGIC;    
	\bsynclr24*\: IN     STD_LOGIC;    
	BWRFLG_MEMD15: IN     STD_LOGIC;    
	CCLK:      IN     STD_LOGIC;    
	DIN:       IN     STD_LOGIC;    
	DOUT:      OUT    STD_LOGIC;    
	ES24_MEMD: OUT    STD_LOGIC;    
	ES_MEMD:   OUT    STD_LOGIC;    
	ISPARE1:   IN     STD_LOGIC;    
	ISPARE2:   IN     STD_LOGIC;    
	M2:        OUT    STD_LOGIC;    
	OSPARE1:   OUT    STD_LOGIC;    
	OSPARE2:   OUT    STD_LOGIC;    
	P20:       OUT    STD_LOGIC;    
	P43:       OUT    STD_LOGIC;    
	P44:       OUT    STD_LOGIC;    
	\program*\: IN     STD_LOGIC;    
	\pwrdwn*\: IN     STD_LOGIC;    
	\rdata*\:  OUT    STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	RTRIG:     IN     STD_LOGIC);
end CGT24;
