// generated by newgenasym  Tue Mar 29 11:59:16 2011


module upfct245 (a0, a1, a2, a3, a4, a5, a6, a7, b0, b1, b2, b3, b4, b5, b6, b7, dir,
        \eo* );
    inout a0;
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout b0;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    input dir;
    input \eo* ;


    initial
        begin
        end

endmodule
