// generated by newgenasym  Mon Oct 13 18:03:18 2014


module clocks (clk100_outh, clk100_outl, clock100, clock200_outh,
        clock200_outl, data, data_rdy, default_select, fox200mhz,
        le, missedclock, sr_clk, tub_clk_in);
    output clk100_outh;
    output clk100_outl;
    output clock100;
    output clock200_outh;
    output clock200_outl;
    input data;
    input data_rdy;
    output default_select;
    output fox200mhz;
    input le;
    output missedclock;
    input sr_clk;
    input tub_clk_in;


    initial
        begin
        end

endmodule
