// generated by newgenasym  Wed Feb 25 10:35:14 2015


module clocks (clk100_out_n, clk100_out_p, clk200_out_n, clk200_out_p,
        clock100, data, data_rdy, default_select, fox200mhz, le,
        missedclock, sr_clk, tub_clk_in);
    output clk100_out_n;
    output clk100_out_p;
    output clk200_out_n;
    output clk200_out_p;
    output clock100;
    input data;
    input data_rdy;
    output default_select;
    output fox200mhz;
    input le;
    output missedclock;
    input sr_clk;
    input tub_clk_in;


    initial
        begin
        end

endmodule
