-- generated by newgenasym Wed Feb 25 10:35:14 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity clocks is
    port (    
	CLK100_OUT_N: OUT    STD_LOGIC;    
	CLK100_OUT_P: OUT    STD_LOGIC;    
	CLK200_OUT_N: OUT    STD_LOGIC;    
	CLK200_OUT_P: OUT    STD_LOGIC;    
	CLOCK100:  OUT    STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	DEFAULT_SELECT: OUT    STD_LOGIC;    
	FOX200MHZ: OUT    STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	MISSEDCLOCK: OUT    STD_LOGIC;    
	SR_CLK:    IN     STD_LOGIC;    
	TUB_CLK_IN: IN     STD_LOGIC);
end clocks;
