-- generated by newgenasym Wed Jun 08 10:38:38 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DATAIN is
    port (    
	PENABLE:   OUT    STD_LOGIC;    
	REG_IN:    OUT    STD_LOGIC_VECTOR (8 DOWNTO 1));
end DATAIN;
