// generated by newgenasym  Tue Mar 29 11:57:23 2011


module dipswitch (a0, a1, a2, a3, a4, a5, a6, a7, b0, b1, b2, b3, b4, b5, b6, b7);
    input a0;
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input b0;
    input b1;
    input b2;
    input b3;
    input b4;
    input b5;
    input b6;
    input b7;


    initial
        begin
        end

endmodule
