-- generated by newgenasym Tue Mar 29 11:57:23 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DIPSWITCH is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	A6:        IN     STD_LOGIC;    
	A7:        IN     STD_LOGIC;    
	B0:        IN     STD_LOGIC;    
	B1:        IN     STD_LOGIC;    
	B2:        IN     STD_LOGIC;    
	B3:        IN     STD_LOGIC;    
	B4:        IN     STD_LOGIC;    
	B5:        IN     STD_LOGIC;    
	B6:        IN     STD_LOGIC;    
	B7:        IN     STD_LOGIC);
end DIPSWITCH;
