`timescale 1ns/1ns

module \ttl-ecl  (ecl_out, ttl_in );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:13 2015
// from tubii_lib/TTL-ECL/sch_1

  inout  ecl_out;
  inout  ttl_in;
  // global signal glbl.vcc;
  // global signal glbl.vtt;

  wire  unnamed_1_10e116_i7_a;
  wire  unnamed_1_10e116_i7_b;
  wire  unnamed_1_f07_i19_y;

  wire  vcc;
  wire  page1_vcc;
  wire  vtt;
  wire  page1_vtt;

  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

// begin instances 

  \10e116  page1_i7  (.a(unnamed_1_10e116_i7_a),
	.\b* (unnamed_1_10e116_i7_b),
	.ref(/* unconnected */),
	.y(ecl_out),
	.\y* (/* unconnected */));
  defparam page1_i7.size = 1;

  rsmd0805 page1_i12  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i7_a));

  f07 page1_i19  (.a(ttl_in),
	.y(unnamed_1_f07_i19_y));
  defparam page1_i19.size = 1;

  rsmd0805 page1_i20  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i7_b));

  rsmd0805 page1_i21  (.a(unnamed_1_f07_i19_y),
	.b({glbl.vcc}));

  mc10h124 page1_i22  (.common(glbl.vcc),
	.in(unnamed_1_f07_i19_y),
	.out(unnamed_1_10e116_i7_a),
	.\out* (unnamed_1_10e116_i7_b));

endmodule // \ttl-ecl (sch_1) 
