-- generated by newgenasym Tue Mar 29 11:56:19 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \2n3906_l\ is
    port (    
	B:         IN     STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end \2n3906_l\;
