// generated by newgenasym  Tue Mar 29 11:59:07 2011


module tlc272_l (nin, nvss, out, pin, pvss);
    input nin;
    inout nvss;
    output out;
    input pin;
    inout pvss;


    initial
        begin
        end

endmodule
