-- generated by newgenasym Tue Mar 29 11:59:07 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TLC272_L is
    port (    
	NIN:       IN     STD_LOGIC;    
	NVSS:      INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	PIN:       IN     STD_LOGIC;    
	PVSS:      INOUT  STD_LOGIC);
end TLC272_L;
