// generated by newgenasym  Wed Feb 25 10:36:17 2015


module caen_chat (gt_ecl_n, gt_ecl_p, sync24_ecl_n, sync24_ecl_p,
        sync24_lvds_n, sync24_lvds_p, sync_ecl_n, sync_ecl_p,
        sync_lvds_n, sync_lvds_p);
    input gt_ecl_n;
    input gt_ecl_p;
    input sync24_ecl_n;
    input sync24_ecl_p;
    output sync24_lvds_n;
    output sync24_lvds_p;
    input sync_ecl_n;
    input sync_ecl_p;
    output sync_lvds_n;
    output sync_lvds_p;


    initial
        begin
        end

endmodule
