// generated by newgenasym  Fri Sep 26 14:33:35 2014


module caen_chat (gtrigh_ecl, gtrigl_ecl, sync24h_ecl, sync24h_lvds,
        sync24l_ecl, synch24l_lvds, synch_ecl, synch_lvds,
        syncl_ecl, syncl_lvds);
    input gtrigh_ecl;
    input gtrigl_ecl;
    input sync24h_ecl;
    output sync24h_lvds;
    input sync24l_ecl;
    output synch24l_lvds;
    input synch_ecl;
    output synch_lvds;
    input syncl_ecl;
    output syncl_lvds;


    initial
        begin
        end

endmodule
