-- generated by newgenasym Fri Sep 26 14:33:35 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_chat is
    port (    
	GTRIGH_ECL: IN     STD_LOGIC;    
	GTRIGL_ECL: IN     STD_LOGIC;    
	SYNC24H_ECL: IN     STD_LOGIC;    
	SYNC24H_LVDS: OUT    STD_LOGIC;    
	SYNC24L_ECL: IN     STD_LOGIC;    
	SYNCH24L_LVDS: OUT    STD_LOGIC;    
	SYNCH_ECL: IN     STD_LOGIC;    
	SYNCH_LVDS: OUT    STD_LOGIC;    
	SYNCL_ECL: IN     STD_LOGIC;    
	SYNCL_LVDS: OUT    STD_LOGIC);
end caen_chat;
