-- generated by newgenasym Wed Feb 25 10:36:17 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_chat is
    port (    
	GT_ECL_N:  IN     STD_LOGIC;    
	GT_ECL_P:  IN     STD_LOGIC;    
	SYNC24_ECL_N: IN     STD_LOGIC;    
	SYNC24_ECL_P: IN     STD_LOGIC;    
	SYNC24_LVDS_N: OUT    STD_LOGIC;    
	SYNC24_LVDS_P: OUT    STD_LOGIC;    
	SYNC_ECL_N: IN     STD_LOGIC;    
	SYNC_ECL_P: IN     STD_LOGIC;    
	SYNC_LVDS_N: OUT    STD_LOGIC;    
	SYNC_LVDS_P: OUT    STD_LOGIC);
end caen_chat;
