// generated by genview  Fri Apr  4 01:24:29 1997


module f06 (a, \y* );
    parameter    size = 1;
    input  [size-1:0] a;
    output [size-1:0] \y* ;


    initial
        begin
        end

endmodule
