-- generated by genview  Fri Apr  4 01:24:30 1997

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity F06 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\y*\:      OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end F06;
