// generated by newgenasym  Thu Jun 09 10:50:17 2011


module progdelay (clock_inh, clock_inl, pulse_inh, pulse_inl, pulse_outh,
        pulse_outl);
    input clock_inh;
    input clock_inl;
    input pulse_inh;
    input pulse_inl;
    output pulse_outh;
    output pulse_outl;


    initial
        begin
        end

endmodule
