-- generated by newgenasym Thu Jun 09 10:50:17 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PROGDELAY is
    port (    
	CLOCK_INH: IN     STD_LOGIC;    
	CLOCK_INL: IN     STD_LOGIC;    
	PULSE_INH: IN     STD_LOGIC;    
	PULSE_INL: IN     STD_LOGIC;    
	PULSE_OUTH: OUT    STD_LOGIC;    
	PULSE_OUTL: OUT    STD_LOGIC);
end PROGDELAY;
