`timescale 1ns/1ns

module gt_delays (clk, data, dgth, dgtl, dgt_ttl, gtrigh, gtrigl, le_dgt, lockout, \lockout* , \mtcd_lo* , select_lo_src, 
    \ttl_lockout*  );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:17 2015
// from tubii_lib/GT_DELAYS/sch_1

  inout  clk;
  inout  data;
  inout  dgth;
  inout  dgtl;
  inout  dgt_ttl;
  inout  gtrigh;
  inout  gtrigl;
  inout  le_dgt;
  inout  lockout;
  inout  \lockout* ;
  inout  \mtcd_lo* ;
  inout  select_lo_src;
  inout  \ttl_lockout* ;
  // global signal glbl.vtt;

  wire  unnamed_1_asyncdelays_i3_ddgt;

  wire  vtt;
  wire  page1_vtt;

  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

// begin instances 

  select_lo_src page1_i2  (.\ddgt* (unnamed_1_asyncdelays_i3_ddgt),
	.lo(lockout),
	.\lo* (\lockout* ),
	.\mtcd_lo* (\mtcd_lo* ),
	.sel(select_lo_src));

  asyncdelays page1_i3  (.clk(clk),
	.\ddgt* (unnamed_1_asyncdelays_i3_ddgt),
	.delay_val(data),
	.dgth(dgth),
	.dgtl(dgtl),
	.dgt_ttl(dgt_ttl),
	.gtrigh(gtrigh),
	.gtrigl(gtrigl),
	.le_dgt(le_dgt));

  rsmd0805 page1_i8  (.a({glbl.vtt}),
	.b(dgth));

  rsmd0805 page1_i9  (.a({glbl.vtt}),
	.b(dgtl));

  rsmd0805 page1_i18  (.a({glbl.vtt}),
	.b(lockout));

  \10h125  page1_i20  (.a(\lockout* ),
	.\b* (lockout),
	.v(/* unconnected */),
	.y(\ttl_lockout* ));
  defparam page1_i20.size = 1;

  rsmd0805 page1_i21  (.a({glbl.vtt}),
	.b(\lockout* ));

endmodule // gt_delays(sch_1) 
