-- generated by newgenasym Tue Mar 29 12:00:25 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DIN3_32 is
    generic (
        size:positive:= 1
            );
    port (    
	CON_PIN:   OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end DIN3_32;
