// generated by newgenasym  Wed Oct 08 11:45:49 2014


module caen_coms (caen_out, clk, data, data_rdy, le, scope_out);
    inout [7:0] caen_out;
    input clk;
    input data;
    input data_rdy;
    input le;
    inout [7:0] scope_out;


    initial
        begin
        end

endmodule
