// generated by newgenasym  Thu Oct 09 11:59:03 2014


module caen_coms (an_pulse_in, caen_out, clk, data, data_rdy, le, scope_out);
    inout [11:0] an_pulse_in;
    inout [7:0] caen_out;
    input clk;
    input data;
    input data_rdy;
    input le;
    inout [7:0] scope_out;


    initial
        begin
        end

endmodule
