-- generated by newgenasym Wed Oct 08 11:45:49 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_coms is
    port (    
	CAEN_OUT:  INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	SCOPE_OUT: INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0));
end caen_coms;
