`timescale 1ns/1ns

module \ecl-lvds  (ecl_in, lvds_out );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:14 2015
// from tubii_lib/ECL-LVDS/sch_1

  inout  ecl_in;
  inout  lvds_out;
  // global signal glbl.gnd;
  // global signal glbl.vp3_3;
  // global signal glbl.vtt;

  wire  unnamed_1_10e116_i46_b;
  wire  unnamed_1_10e116_i46_y;
  wire  unnamed_1_10ep90_i51_d;
  wire  unnamed_1_10ep90_i51_q;
  wire  unnamed_1_lvdsdriverds10_i14_in;
  wire  unnamed_1_lvdsdriverds10_i14_in_1;
  wire  unnamed_1_max9376_i48_in2;
  wire  unnamed_1_rsmd0805_i54_a;

  wire  gnd;
  wire  page1_gnd;
  wire  vp3_3;
  wire  page1_vp3_3;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vp3_3 = glbl.vp3_3;
  assign page1_vp3_3 = vp3_3;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;

// begin instances 

  rsmd0805 page1_i12  (.a({glbl.vp3_3}),
	.b(unnamed_1_lvdsdriverds10_i14_in));

  rsmd0805 page1_i13  (.a({glbl.vp3_3}),
	.b(unnamed_1_lvdsdriverds10_i14_in_1));

  lvds_driver_ds10 page1_i14  (.\1 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\in+ (unnamed_1_lvdsdriverds10_i14_in_1),
	.\in- (unnamed_1_lvdsdriverds10_i14_in),
	.\out+ (lvds_out),
	.\out- (/* unconnected */));

  csmd0805 page1_i43  (.a(unnamed_1_10e116_i46_b),
	.b({glbl.gnd}));

  \10e116  page1_i46  (.a(ecl_in),
	.\b* (unnamed_1_10e116_i46_b),
	.ref(unnamed_1_10e116_i46_b),
	.y(unnamed_1_10e116_i46_y),
	.\y* (/* unconnected */));
  defparam page1_i46.size = 1;

  rsmd0805 page1_i47  (.a({glbl.vtt}),
	.b(ecl_in));

  max9376 page1_i48  (.in2(unnamed_1_10ep90_i51_q),
	.\in2* (unnamed_1_max9376_i48_in2),
	.out2(unnamed_1_lvdsdriverds10_i14_in_1),
	.\out2* (unnamed_1_lvdsdriverds10_i14_in),
	.out1(/* unconnected */),
	.\out1* (/* unconnected */),
	.in1(/* unconnected */),
	.\in1* (/* unconnected */));

  rsmd0805 page1_i49  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i46_y));

  rsmd0805 page1_i50  (.a({glbl.vtt}),
	.b(unnamed_1_10ep90_i51_d));

  \10ep90  page1_i51  (.d(unnamed_1_10e116_i46_y),
	.\d* (unnamed_1_10ep90_i51_d),
	.q(unnamed_1_10ep90_i51_q),
	.\q* (unnamed_1_max9376_i48_in2));

  rsmd0805 page1_i52  (.a(unnamed_1_max9376_i48_in2),
	.b({glbl.vp3_3}));

  rsmd0805 page1_i53  (.a({glbl.gnd}),
	.b(unnamed_1_max9376_i48_in2));

  rsmd0805 page1_i54  (.a(unnamed_1_rsmd0805_i54_a),
	.b({glbl.vp3_3}));

  rsmd0805 page1_i55  (.a({glbl.gnd}),
	.b(unnamed_1_rsmd0805_i54_a));

endmodule // \ecl-lvds (sch_1) 
