// generated by newgenasym  Tue Mar 29 11:57:29 2011


module fec32d_inconn (caddr, cc_in, \cs_d* , datin_d, lgisel_d, pen_d, pmt_d,
        pmtr_d, power, rmpc_d, vbal_d, virefb, virefc, vsli_d, vth_d);
    output [4:0] caddr;
    output [6:1] cc_in;
    output [8:1] \cs_d* ;
    output [8:1] datin_d;
    input [8:1] lgisel_d;
    output [8:1] pen_d;
    output [8:1] pmt_d;
    output [8:1] pmtr_d;
    input [8:1] power;
    output [4:1] rmpc_d;
    input [16:1] vbal_d;
    output [3:1] virefb;
    output [6:1] virefc;
    input [4:1] vsli_d;
    output [8:1] vth_d;


    initial
        begin
        end

endmodule
