-- generated by newgenasym Tue Mar 29 11:57:29 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity FEC32D_INCONN is
    port (    
	CADDR:     OUT    STD_LOGIC_VECTOR (4 DOWNTO 0);    
	CC_IN:     OUT    STD_LOGIC_VECTOR (6 DOWNTO 1);    
	\cs_d*\:   OUT    STD_LOGIC_VECTOR (8 DOWNTO 1);    
	DATIN_D:   OUT    STD_LOGIC_VECTOR (8 DOWNTO 1);    
	LGISEL_D:  IN     STD_LOGIC_VECTOR (8 DOWNTO 1);    
	PEN_D:     OUT    STD_LOGIC_VECTOR (8 DOWNTO 1);    
	PMT_D:     OUT    STD_LOGIC_VECTOR (8 DOWNTO 1);    
	PMTR_D:    OUT    STD_LOGIC_VECTOR (8 DOWNTO 1);    
	POWER:     IN     STD_LOGIC_VECTOR (8 DOWNTO 1);    
	RMPC_D:    OUT    STD_LOGIC_VECTOR (4 DOWNTO 1);    
	VBAL_D:    IN     STD_LOGIC_VECTOR (16 DOWNTO 1);    
	VIREFB:    OUT    STD_LOGIC_VECTOR (3 DOWNTO 1);    
	VIREFC:    OUT    STD_LOGIC_VECTOR (6 DOWNTO 1);    
	VSLI_D:    IN     STD_LOGIC_VECTOR (4 DOWNTO 1);    
	VTH_D:     OUT    STD_LOGIC_VECTOR (8 DOWNTO 1));
end FEC32D_INCONN;
