-- generated by newgenasym Tue Mar 29 12:00:09 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity XVMETRIG3T is
    port (    
	CCLK:      IN     STD_LOGIC;    
	DUMMY_OUT: OUT    STD_LOGIC;    
	M2:        OUT    STD_LOGIC;    
	\program*\: IN     STD_LOGIC;    
	\pwrdwn*\: IN     STD_LOGIC;    
	\rdata*\:  OUT    STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	RTRIG:     IN     STD_LOGIC;    
	SDIN:      IN     STD_LOGIC;    
	SDOUT:     OUT    STD_LOGIC;    
	SPARES:    IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	XBA:       IN     STD_LOGIC_VECTOR (31 DOWNTO 0);    
	XBAM:      IN     STD_LOGIC_VECTOR (5 DOWNTO 0);    
	\xbds0*\:  IN     STD_LOGIC;    
	\xbds1*\:  IN     STD_LOGIC;    
	\xbrw*\:   IN     STD_LOGIC;    
	\xdt_en*\: OUT    STD_LOGIC;    
	\xdtack*\: OUT    STD_LOGIC;    
	\xlword*\: IN     STD_LOGIC;    
	\xmemack1*\: IN     STD_LOGIC;    
	\xmemspace*\: OUT    STD_LOGIC;    
	\xmodsel*\: OUT    STD_LOGIC;    
	XREGRD_LA: OUT    STD_LOGIC_VECTOR (31 DOWNTO 0);    
	XREGWR_LA: OUT    STD_LOGIC_VECTOR (31 DOWNTO 0);    
	XVME_DIR:  OUT    STD_LOGIC);
end XVMETRIG3T;
