// generated by newgenasym  Thu Sep 18 17:30:12 2014


module \10h104  (a, b, y);
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] b;
    output [size-1:0] y;


    initial
        begin
        end

endmodule
