-- generated by newgenasym Thu Sep 18 17:30:12 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h104\ is
    generic (
        size:positive:= 1
            );
    port (    
	A:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Y:         OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \10h104\;
