-- generated by newgenasym Tue Oct 28 19:01:07 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h104\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC);
end \10h104\;
