`timescale 1ns/1ns

module vrefs (vref5m );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:20 2015
// from tubii_lib/VREFS/sch_1

  inout  vref5m;
  // global signal glbl.gnd;
  // global signal glbl.vcc15;
  // global signal glbl.vcc15m;

  wire  unnamed_1_csmd0805_i3_a;
  wire  unnamed_1_csmd0805_i4_b;
  wire  unnamed_1_csmd0805_i7_a;
  wire  unnamed_1_ref02_i1_vout;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc15;
  wire  page1_vcc15;
  wire  vcc15m;
  wire  page1_vcc15m;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc15 = glbl.vcc15;
  assign page1_vcc15 = vcc15;
  assign vcc15m = glbl.vcc15m;
  assign page1_vcc15m = vcc15m;

// begin instances 

  ref02 page1_i1  (.gnd(/* unconnected */),
	.temp(/* unconnected */),
	.trim(/* unconnected */),
	.vin(glbl.vcc15),
	.vout(unnamed_1_ref02_i1_vout));

  opa277 page1_i2  (.\in+ (glbl.gnd),
	.\in- (unnamed_1_csmd0805_i7_a),
	.out(vref5m),
	.trim_a(/* unconnected */),
	.trim_b(/* unconnected */),
	.\v+ (unnamed_1_csmd0805_i3_a),
	.\v- (unnamed_1_csmd0805_i4_b));

  csmd0805 page1_i3  (.a(unnamed_1_csmd0805_i3_a),
	.b({glbl.vcc15}));

  csmd0805 page1_i4  (.a({glbl.vcc15m}),
	.b(unnamed_1_csmd0805_i4_b));

  rsmd0805 page1_i5  (.a(unnamed_1_csmd0805_i7_a),
	.b(vref5m));

  rsmd0805 page1_i6  (.a(unnamed_1_ref02_i1_vout),
	.b(unnamed_1_csmd0805_i7_a));

  csmd0805 page1_i7  (.a(unnamed_1_csmd0805_i7_a),
	.b(vref5m));

endmodule // vrefs(sch_1) 
