-- generated by newgenasym Tue Mar 29 11:56:46 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ADREF02C_L is
    port (    
	GND:       INOUT  STD_LOGIC;    
	TRIM:      IN     STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end ADREF02C_L;
