// generated by newgenasym  Tue Mar 29 11:56:31 2011


module \74gtl16612  (a, b, \ceab* , \ceba* , clkab, clkba, gnd01, gnd02, gnd03, gnd04,
        gnd05, gnd06, gnd07, gnd08, gnd1, gnd2, gnd3, gnd4, gnd5, gnd6,
        gnd7, gnd8, leab, leba, \oeab* , \oeba* , vcc3_3a, vcc3_3b, vcc5,
        vref);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;
    input \ceab* ;
    input \ceba* ;
    input clkab;
    input clkba;
    input gnd01;
    input gnd02;
    input gnd03;
    input gnd04;
    input gnd05;
    input gnd06;
    input gnd07;
    input gnd08;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gnd7;
    inout gnd8;
    input leab;
    input leba;
    input \oeab* ;
    input \oeba* ;
    input vcc3_3a;
    input vcc3_3b;
    input vcc5;
    input vref;


    initial
        begin
        end

endmodule
