// generated by newgenasym  Tue Mar 29 11:58:10 2011


module max507 (agnd, \clr* , \cs* , d0, d1, d10, d11, d2, d3, d4, d5, d6, d7, d8, d9,
        dgnd, \ldac* , refout, rfb, rofs, vdd, vout, vss, \wr* );
    input agnd;
    input \clr* ;
    input \cs* ;
    input d0;
    input d1;
    input d10;
    input d11;
    input d2;
    input d3;
    input d4;
    input d5;
    input d6;
    input d7;
    input d8;
    input d9;
    input dgnd;
    input \ldac* ;
    output refout;
    input rfb;
    input rofs;
    input vdd;
    output vout;
    input vss;
    input \wr* ;


    initial
        begin
        end

endmodule
