// generated by newgenasym  Wed Oct 08 11:17:16 2014


module caen_channel_sel (clk, data, data_rdy, le);
    input clk;
    input data;
    input data_rdy;
    input le;


    initial
        begin
        end

endmodule
