-- generated by newgenasym Wed Oct 08 11:17:16 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_channel_sel is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	LE:        IN     STD_LOGIC);
end caen_channel_sel;
