// generated by newgenasym  Tue Mar 29 11:58:26 2011


module mic2941 (adj, ground, \input , \output , shdwn);
    inout adj;
    inout ground;
    inout \input ;
    output \output ;
    input shdwn;


    initial
        begin
        end

endmodule
