// generated by newgenasym  Tue Mar 29 11:59:32 2011


module \10e116  (a, \b* , ref, y, \y* );
    parameter    section = 1;
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] \b* ;
    output ref;
    output [size-1:0] y;
    output [size-1:0] \y* ;


    initial
        begin
        end

endmodule
