`timescale 1ns/1ns

module select_lo_src (\ddgt* , lo, \lo* , \mtcd_lo* , sel );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:17 2015
// from tubii_lib/SELECT_LO_SRC/sch_1

  inout  \ddgt* ;
  inout  lo;
  inout  \lo* ;
  inout  \mtcd_lo* ;
  inout  sel;
  // global signal glbl.gnd;
  // global signal glbl.vcc;
  // global signal glbl.vtt;

  wire  unnamed_1_10e116_i26_a;
  wire  unnamed_1_10e116_i26_b;
  wire  unnamed_1_10h116_i37_b;
  wire  unnamed_1_10h116_i37_y;
  wire  unnamed_1_ledl_i36_a;
  wire  unnamed_1_mc10h104_i33_a;
  wire  unnamed_1_mc10h104_i34_a;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  csmd0805 page1_i7  (.a({glbl.gnd}),
	.b(unnamed_1_10h116_i37_b));

  rsmd0805 page1_i11  (.a({glbl.vtt}),
	.b(unnamed_1_10h116_i37_y));

  rsmd0805 page1_i15  (.a({glbl.vtt}),
	.b(\ddgt* ));

  rsmd0805 page1_i16  (.a({glbl.vtt}),
	.b(\mtcd_lo* ));

  rsmd0805 page1_i20  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i26_a));

  rsmd0805 page1_i24  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h104_i34_a));

  rsmd0805 page1_i25  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h104_i33_a));

  \10e116  page1_i26  (.a(unnamed_1_10e116_i26_a),
	.\b* (unnamed_1_10e116_i26_b),
	.ref(unnamed_1_10e116_i26_b),
	.y(\lo* ),
	.\y* (lo));
  defparam page1_i26.size = 1;

  csmd0805 page1_i27  (.a({glbl.gnd}),
	.b(unnamed_1_10e116_i26_b));

  rsmd0805 page1_i31  (.a(unnamed_1_ledl_i36_a),
	.b(sel));

  mc10h104 page1_i33  (.a(unnamed_1_mc10h104_i33_a),
	.b(unnamed_1_10h116_i37_y),
	.y(unnamed_1_10e116_i26_a));

  mc10h104 page1_i34  (.a(unnamed_1_mc10h104_i34_a),
	.b(\ddgt* ),
	.y(unnamed_1_10e116_i26_a));

  mc10h124 page1_i35  (.common(glbl.vcc),
	.in(sel),
	.out(unnamed_1_mc10h104_i33_a),
	.\out* (unnamed_1_mc10h104_i34_a));

  led_l page1_i36  (.a(unnamed_1_ledl_i36_a),
	.b(glbl.gnd));

  \10h116  page1_i37  (.a(\mtcd_lo* ),
	.\b* (unnamed_1_10h116_i37_b),
	.v(unnamed_1_10h116_i37_b),
	.y(unnamed_1_10h116_i37_y),
	.\y* (/* unconnected */));
  defparam page1_i37.section = 1;
  defparam page1_i37.size = 1;

endmodule // select_lo_src(sch_1) 
