// generated by newgenasym  Tue Mar 29 11:58:54 2011


module snodiscg (ina1, ina2, ina3, ina4, inb1, inb2, inb3, inb4, inta1, inta2,
        inta3, inta4, intb1, intb2, intb3, intb4, intma1, intma2,
        intma3, intma4, intmb1, intmb2, intmb3, intmb4, itwk, peda,
        pedb, pen1, pen2, pen3, pen4, ramp1, ramp2, ramp3, ramp4,
        resa1, resa2, resa3, resa4, resb1, resb2, resb3, resb4, rmp,
        rmpup, sama1, sama2, sama3, sama4, samb1, samb2, samb3, samb4,
        suba1, suba2, subd1, subd2, vli, vsi, vth1, vth2, vth3, vth4);
    input ina1;
    input ina2;
    input ina3;
    input ina4;
    input inb1;
    input inb2;
    input inb3;
    input inb4;
    input inta1;
    input inta2;
    input inta3;
    input inta4;
    input intb1;
    input intb2;
    input intb3;
    input intb4;
    input intma1;
    input intma2;
    input intma3;
    input intma4;
    input intmb1;
    input intmb2;
    input intmb3;
    input intmb4;
    input itwk;
    input peda;
    input pedb;
    input pen1;
    input pen2;
    input pen3;
    input pen4;
    input ramp1;
    input ramp2;
    input ramp3;
    input ramp4;
    output resa1;
    output resa2;
    output resa3;
    output resa4;
    output resb1;
    output resb2;
    output resb3;
    input resb4;
    input rmp;
    input rmpup;
    output sama1;
    output sama2;
    output sama3;
    output sama4;
    output samb1;
    output samb2;
    output samb3;
    output samb4;
    input suba1;
    input suba2;
    input subd1;
    input subd2;
    input vli;
    input vsi;
    input vth1;
    input vth2;
    input vth3;
    input vth4;


    initial
        begin
        end

endmodule
