// generated by newgenasym  Fri Oct 03 12:15:53 2014


module pulse_scaler (allow_cnt, clr_cnt, latch_display, leading_zeroes, pulse,
        test);
    input allow_cnt;
    input clr_cnt;
    input latch_display;
    input leading_zeroes;
    input pulse;
    input test;


    initial
        begin
        end

endmodule
