-- generated by newgenasym Fri Oct 03 12:15:53 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pulse_scaler is
    port (    
	ALLOW_CNT: IN     STD_LOGIC;    
	CLR_CNT:   IN     STD_LOGIC;    
	LATCH_DISPLAY: IN     STD_LOGIC;    
	LEADING_ZEROES: IN     STD_LOGIC;    
	PULSE:     IN     STD_LOGIC;    
	TEST:      IN     STD_LOGIC);
end pulse_scaler;
