-- generated by newgenasym Tue Mar 29 11:59:01 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TESTPOINT_L is
    port (    
	A:         INOUT  STD_LOGIC);
end TESTPOINT_L;
