`timescale 1ns/1ns

module caen_ports (caen_anpulse, caen_out, sync24h_lvds, sync24l_lvds, synch_lvds, syncl_lvds );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:13 2015
// from tubii_lib/CAEN_PORTS/sch_1

  inout [11:0] caen_anpulse;
  inout [7:0] caen_out;
  inout  sync24h_lvds;
  inout  sync24l_lvds;
  inout  synch_lvds;
  inout  syncl_lvds;
  // global signal glbl.gnd;

  wire  unnamed_1_4merge_i23_a;
  wire  unnamed_1_4merge_i23_b;
  wire  unnamed_1_4merge_i23_c;
  wire  unnamed_1_4merge_i23_d;
  wire  unnamed_1_8merge_i13_a;
  wire  unnamed_1_8merge_i13_b;
  wire  unnamed_1_8merge_i13_c;
  wire  unnamed_1_8merge_i13_d;
  wire  unnamed_1_8merge_i13_e;
  wire  unnamed_1_8merge_i13_f;
  wire  unnamed_1_8merge_i13_g;
  wire  unnamed_1_8merge_i13_h;
  wire  unnamed_1_8merge_i22_a;
  wire  unnamed_1_8merge_i22_b;
  wire  unnamed_1_8merge_i22_c;
  wire  unnamed_1_8merge_i22_d;
  wire  unnamed_1_8merge_i22_e;
  wire  unnamed_1_8merge_i22_f;
  wire  unnamed_1_8merge_i22_g;
  wire  unnamed_1_8merge_i22_h;
  wire  unnamed_1_idsc10_i3_pin1;
  wire  unnamed_1_idsc10_i3_pin2;
  wire  unnamed_1_idsc10_i3_pin6;
  wire  unnamed_1_idsc10_i3_pin7;

  wire [11:0] page1_caen_anpulse;
  wire [7:0] page1_caen_out;
  wire  gnd;
  wire  page1_gnd;

  assign page1_caen_anpulse[11:8] = caen_anpulse[11:8];
  assign page1_caen_anpulse[3:0] = caen_anpulse[3:0];
  assign page1_caen_anpulse[7:0] = caen_anpulse[7:0];
  assign page1_caen_anpulse[11:4] = caen_anpulse[11:4];
  assign page1_caen_anpulse[8:8] = caen_anpulse[8:8];
  assign page1_caen_anpulse[9:9] = caen_anpulse[9:9];
  assign page1_caen_anpulse[10:10] = caen_anpulse[10:10];
  assign page1_caen_anpulse[11:11] = caen_anpulse[11:11];
  assign page1_caen_anpulse[0:0] = caen_anpulse[0:0];
  assign page1_caen_anpulse[1:1] = caen_anpulse[1:1];
  assign page1_caen_anpulse[2:2] = caen_anpulse[2:2];
  assign page1_caen_anpulse[3:3] = caen_anpulse[3:3];
  assign page1_caen_anpulse[4:4] = caen_anpulse[4:4];
  assign page1_caen_anpulse[5:5] = caen_anpulse[5:5];
  assign page1_caen_anpulse[6:6] = caen_anpulse[6:6];
  assign page1_caen_anpulse[7:7] = caen_anpulse[7:7];
  assign page1_caen_anpulse[11:0] = caen_anpulse[11:0];
  assign page1_caen_anpulse[7:0] = caen_anpulse[7:0];
  assign page1_caen_anpulse[11:8] = caen_anpulse[11:8];
  assign page1_caen_out[0:0] = caen_out[0:0];
  assign page1_caen_out[1:1] = caen_out[1:1];
  assign page1_caen_out[2:2] = caen_out[2:2];
  assign page1_caen_out[3:3] = caen_out[3:3];
  assign page1_caen_out[4:4] = caen_out[4:4];
  assign page1_caen_out[5:5] = caen_out[5:5];
  assign page1_caen_out[6:6] = caen_out[6:6];
  assign page1_caen_out[7:7] = caen_out[7:7];
  assign page1_caen_out[7:0] = caen_out[7:0];
  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign unnamed_1_4merge_i23_a = caen_anpulse[11:11];
  assign unnamed_1_4merge_i23_b = caen_anpulse[10:10];
  assign unnamed_1_4merge_i23_c = caen_anpulse[9:9];
  assign unnamed_1_4merge_i23_d = caen_anpulse[8:8];
  assign unnamed_1_8merge_i13_a = caen_out[7:7];
  assign unnamed_1_8merge_i13_b = caen_out[6:6];
  assign unnamed_1_8merge_i13_c = caen_out[5:5];
  assign unnamed_1_8merge_i13_d = caen_out[4:4];
  assign unnamed_1_8merge_i13_e = caen_out[3:3];
  assign unnamed_1_8merge_i13_f = caen_out[2:2];
  assign unnamed_1_8merge_i13_g = caen_out[1:1];
  assign unnamed_1_8merge_i13_h = caen_out[0:0];
  assign unnamed_1_8merge_i22_a = caen_anpulse[7:7];
  assign unnamed_1_8merge_i22_b = caen_anpulse[6:6];
  assign unnamed_1_8merge_i22_c = caen_anpulse[5:5];
  assign unnamed_1_8merge_i22_d = caen_anpulse[4:4];
  assign unnamed_1_8merge_i22_e = caen_anpulse[3:3];
  assign unnamed_1_8merge_i22_f = caen_anpulse[2:2];
  assign unnamed_1_8merge_i22_g = caen_anpulse[1:1];
  assign unnamed_1_8merge_i22_h = caen_anpulse[0:0];

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  assign caen_anpulse [11:8] = caen_anpulse [3:0];

  assign caen_anpulse [7:0] = caen_anpulse [11:4];

  lvds_driver_ds10 page1_i1  (.\1 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\in+ (sync24h_lvds),
	.\in- (sync24l_lvds),
	.\out+ (unnamed_1_idsc10_i3_pin6),
	.\out- (unnamed_1_idsc10_i3_pin7));

  ids_c10 page1_i3  (.pin1(unnamed_1_idsc10_i3_pin1),
	.pin2(unnamed_1_idsc10_i3_pin2),
	.pin3(glbl.gnd),
	.pin4(glbl.gnd),
	.pin5(glbl.gnd),
	.pin6(unnamed_1_idsc10_i3_pin6),
	.pin7(unnamed_1_idsc10_i3_pin7),
	.pin8(glbl.gnd),
	.pin9(glbl.gnd),
	.pin10(glbl.gnd));

  lvds_driver_ds10 page1_i4  (.\1 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\in+ (synch_lvds),
	.\in- (syncl_lvds),
	.\out+ (unnamed_1_idsc10_i3_pin1),
	.\out- (unnamed_1_idsc10_i3_pin2));

  testpoint_l page1_i5  (.a(unnamed_1_8merge_i13_h));

  testpoint_l page1_i6  (.a(unnamed_1_8merge_i13_a));

  testpoint_l page1_i7  (.a(unnamed_1_8merge_i13_b));

  testpoint_l page1_i8  (.a(unnamed_1_8merge_i13_c));

  testpoint_l page1_i9  (.a(unnamed_1_8merge_i13_d));

  testpoint_l page1_i10  (.a(unnamed_1_8merge_i13_e));

  testpoint_l page1_i11  (.a(unnamed_1_8merge_i13_f));

  testpoint_l page1_i12  (.a(unnamed_1_8merge_i13_g));

  testpoint_l page1_i14  (.a(unnamed_1_8merge_i22_a));

  testpoint_l page1_i15  (.a(unnamed_1_8merge_i22_b));

  testpoint_l page1_i16  (.a(unnamed_1_8merge_i22_c));

  testpoint_l page1_i17  (.a(unnamed_1_8merge_i22_e));

  testpoint_l page1_i18  (.a(unnamed_1_8merge_i22_f));

  testpoint_l page1_i19  (.a(unnamed_1_8merge_i22_d));

  testpoint_l page1_i20  (.a(unnamed_1_8merge_i22_h));

  testpoint_l page1_i21  (.a(unnamed_1_8merge_i22_g));

  testpoint_l page1_i25  (.a(unnamed_1_4merge_i23_a));

  testpoint_l page1_i26  (.a(unnamed_1_4merge_i23_b));

  testpoint_l page1_i27  (.a(unnamed_1_4merge_i23_c));

  testpoint_l page1_i28  (.a(unnamed_1_4merge_i23_d));

  testpoint_l page1_i29  (.a(glbl.gnd));

  testpoint_l page1_i33  (.a(glbl.gnd));

  testpoint_l page1_i34  (.a(glbl.gnd));

  testpoint_l page1_i35  (.a(glbl.gnd));

  testpoint_l page1_i41  (.a(glbl.gnd));

  testpoint_l page1_i42  (.a(glbl.gnd));

  testpoint_l page1_i43  (.a(glbl.gnd));

  testpoint_l page1_i44  (.a(glbl.gnd));

  testpoint_l page1_i50  (.a(glbl.gnd));

  testpoint_l page1_i51  (.a(glbl.gnd));

  testpoint_l page1_i55  (.a(glbl.gnd));

  testpoint_l page1_i56  (.a(glbl.gnd));

  testpoint_l page1_i58  (.a(glbl.gnd));

  testpoint_l page1_i60  (.a(glbl.gnd));

  testpoint_l page1_i62  (.a(glbl.gnd));

  testpoint_l page1_i64  (.a(glbl.gnd));

  testpoint_l page1_i66  (.a(glbl.gnd));

  testpoint_l page1_i68  (.a(glbl.gnd));

  testpoint_l page1_i70  (.a(glbl.gnd));

  testpoint_l page1_i72  (.a(glbl.gnd));

endmodule // caen_ports(sch_1) 
