// generated by newgenasym  Fri Oct 03 12:34:14 2014


module cntrl_register (clk, data, data_rdy, default_clk_select, display,
        ecal_setup, le, lo_select);
    input clk;
    input data;
    input data_rdy;
    output default_clk_select;
    output [2:0] display;
    output ecal_setup;
    input le;
    output lo_select;


    initial
        begin
        end

endmodule
