// generated by newgenasym  Tue Oct 14 14:58:22 2014


module cntrl_register (clk, data, data_out, data_rdy, default_clk_select,
        display, ecal_setup, le, lo_select, read_enable);
    input clk;
    input data;
    output data_out;
    input data_rdy;
    output default_clk_select;
    output [2:0] display;
    output ecal_setup;
    input le;
    output lo_select;
    input read_enable;


    initial
        begin
        end

endmodule
