-- generated by newgenasym Tue Oct 14 14:58:22 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cntrl_register is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_OUT:  OUT    STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	DEFAULT_CLK_SELECT: OUT    STD_LOGIC;    
	DISPLAY:   OUT    STD_LOGIC_VECTOR (2 DOWNTO 0);    
	ECAL_SETUP: OUT    STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	LO_SELECT: OUT    STD_LOGIC;    
	READ_ENABLE: IN     STD_LOGIC);
end cntrl_register;
