-- generated by newgenasym Tue Mar 29 11:58:59 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TESTPOINT_GND is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end TESTPOINT_GND;
