// generated by newgenasym  Thu Oct 09 10:50:52 2014


module generic_utilities_ports (async_delay_in, async_delay_out, async_pulse_out,
        sync_delay_in, sync_delay_out, sync_pulse_out);
    input async_delay_in;
    input async_delay_out;
    input async_pulse_out;
    input sync_delay_in;
    input sync_delay_out;
    input sync_pulse_out;


    initial
        begin
        end

endmodule
