-- generated by newgenasym Thu Oct 09 10:50:52 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity generic_utilities_ports is
    port (    
	ASYNC_DELAY_IN: IN     STD_LOGIC;    
	ASYNC_DELAY_OUT: IN     STD_LOGIC;    
	ASYNC_PULSE_OUT: IN     STD_LOGIC;    
	SYNC_DELAY_IN: IN     STD_LOGIC;    
	SYNC_DELAY_OUT: IN     STD_LOGIC;    
	SYNC_PULSE_OUT: IN     STD_LOGIC);
end generic_utilities_ports;
