-- generated by newgenasym Tue Mar 29 11:56:38 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD22100KT is
    port (    
	GNDT:      INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end AD22100KT;
