// generated by newgenasym  Tue Mar 29 12:00:19 2011


module ad96685 (grnd1, grnd2, inn, inp, ltch, qn, qp, vn, vp);
    output grnd1;
    output grnd2;
    input inn;
    input inp;
    output ltch;
    output qn;
    output qp;
    input vn;
    input vp;


    initial
        begin
        end

endmodule
