-- generated by newgenasym Tue Mar 29 12:00:19 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD96685 is
    port (    
	GRND1:     OUT    STD_LOGIC;    
	GRND2:     OUT    STD_LOGIC;    
	INN:       IN     STD_LOGIC;    
	INP:       IN     STD_LOGIC;    
	LTCH:      OUT    STD_LOGIC;    
	QN:        OUT    STD_LOGIC;    
	QP:        OUT    STD_LOGIC;    
	VN:        IN     STD_LOGIC;    
	VP:        IN     STD_LOGIC);
end AD96685;
