// generated by newgenasym  Tue Jun 28 18:00:16 2011


module ellie_comms (bus, clock200h, clock200l, ellie_ie, ellie_oe,
        ellieenable, mstreset_ttl, ploadenable_ttl,
        ttlclock3_125);
    input [31:0] bus;
    input clock200h;
    input clock200l;
    input ellie_ie;
    input ellie_oe;
    input ellieenable;
    input mstreset_ttl;
    input ploadenable_ttl;
    input ttlclock3_125;


    initial
        begin
        end

endmodule
