// generated by newgenasym  Mon Oct 20 16:18:14 2014


module microzedconnection (\100mhz_clk_in , async_delay_in, async_delay_out,
        async_pulse_out, caen_rdy, clk, clr_cnt, cnt_pulse,
        cntrl_rdy, cntrl_register_chk, comp_rdy, data, dgt,
        exttrig, fox_200mhz_in, gtrig, latch_display, load_enable,
        \lockout* , rawtrigs_in, smellie_delay_in,
        smellie_delay_out, smellie_pulse_out, spkr, sync, sync24,
        sync_delay_in, sync_delay_out, sync_pulse_out,
        tellie_delay_in, tellie_delay_out, tellie_pulse_out,
        tubii_rt_out, tubiitime_data_rdy, using_bckp);
    input \100mhz_clk_in ;
    input async_delay_in;
    input async_delay_out;
    input async_pulse_out;
    output caen_rdy;
    output clk;
    output clr_cnt;
    output cnt_pulse;
    output cntrl_rdy;
    output cntrl_register_chk;
    input comp_rdy;
    output data;
    output dgt;
    input [0:15] exttrig;
    input fox_200mhz_in;
    output gtrig;
    output latch_display;
    output [0:2] load_enable;
    output \lockout* ;
    input [3:0] rawtrigs_in;
    input smellie_delay_in;
    input smellie_delay_out;
    input smellie_pulse_out;
    input spkr;
    output sync;
    output sync24;
    input sync_delay_in;
    input sync_delay_out;
    input sync_pulse_out;
    input tellie_delay_in;
    input tellie_delay_out;
    input tellie_pulse_out;
    input tubii_rt_out;
    input tubiitime_data_rdy;
    input using_bckp;


    initial
        begin
        end

endmodule
