// generated by newgenasym  Tue Mar 29 11:59:18 2011


module vme2000 (\ack* , \aden* , am2, \as* , bc, \berr* , \d0en* , \d1en* , \ds* , \ds0* ,
        \ds1* , \dtack* , \err* , \iack* , \intack* , \modsel* , su);
    input \ack* ;
    input \aden* ;
    input am2;
    input \as* ;
    input bc;
    output \berr* ;
    output \d0en* ;
    output \d1en* ;
    output \ds* ;
    input \ds0* ;
    input \ds1* ;
    output \dtack* ;
    input \err* ;
    input \iack* ;
    input \intack* ;
    output \modsel* ;
    input su;


    initial
        begin
        end

endmodule
