-- generated by newgenasym Tue Mar 29 11:59:18 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity VME2000 is
    port (    
	\ack*\:    IN     STD_LOGIC;    
	\aden*\:   IN     STD_LOGIC;    
	AM2:       IN     STD_LOGIC;    
	\as*\:     IN     STD_LOGIC;    
	BC:        IN     STD_LOGIC;    
	\berr*\:   OUT    STD_LOGIC;    
	\d0en*\:   OUT    STD_LOGIC;    
	\d1en*\:   OUT    STD_LOGIC;    
	\ds*\:     OUT    STD_LOGIC;    
	\ds0*\:    IN     STD_LOGIC;    
	\ds1*\:    IN     STD_LOGIC;    
	\dtack*\:  OUT    STD_LOGIC;    
	\err*\:    IN     STD_LOGIC;    
	\iack*\:   IN     STD_LOGIC;    
	\intack*\: IN     STD_LOGIC;    
	\modsel*\: OUT    STD_LOGIC;    
	SU:        IN     STD_LOGIC);
end VME2000;
