// generated by newgenasym  Fri Oct 03 17:26:59 2014


module tubii_clock_select (bckp_clk, clock200_outh, clock200_outl, default_clk,
        default_select, fox200mhz, tub_clk_in);
    output bckp_clk;
    output clock200_outh;
    output clock200_outl;
    output default_clk;
    input default_select;
    output fox200mhz;
    input tub_clk_in;


    initial
        begin
        end

endmodule
