-- generated by newgenasym Tue Mar 29 11:59:49 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CLOCK100 is
    port (    
	CLKOUT:    OUT    STD_LOGIC;    
	\clkout*\: OUT    STD_LOGIC);
end CLOCK100;
