// generated by newgenasym  Fri Oct 03 17:03:07 2014


module generic_delays (async_delay_in, async_delay_out, clk, data, le);
    input async_delay_in;
    output async_delay_out;
    input clk;
    input data;
    input le;


    initial
        begin
        end

endmodule
