-- generated by newgenasym Fri Sep 05 17:11:20 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity clk_leds is
    port (    
	SEL_LED:   IN     STD_LOGIC_VECTOR (0 TO 1));
end clk_leds;
