-- generated by newgenasym Tue Mar 29 11:58:13 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX529 is
    port (    
	CLK:       IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	DIN:       IN     STD_LOGIC;    
	DOUT:      OUT    STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	REFH1:     INOUT  STD_LOGIC;    
	REFH2:     INOUT  STD_LOGIC;    
	REFL1:     INOUT  STD_LOGIC;    
	REFL2:     INOUT  STD_LOGIC;    
	\shdn*\:   IN     STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VSS:       INOUT  STD_LOGIC);
end MAX529;
