// generated by newgenasym  Tue Mar 29 11:58:15 2011


module max907 (inam, inap, inbm, inbp, outa, outb, vm, vp);
    input inam;
    input inap;
    input inbm;
    input inbp;
    output outa;
    output outb;
    input vm;
    input vp;


    initial
        begin
        end

endmodule
