`timescale 1ns/1ns

module ribbondelay ();
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:23 2015
// from tubii_lib/RIBBONDELAY/sch_1

  // global signal glbl.gnd;
  // global signal glbl.vee;
  // global signal glbl.vtt;

  wire  unnamed_1_10e116_i10_a;
  wire  unnamed_1_10e116_i10_b;
  wire  unnamed_1_10e116_i10_y;
  wire  unnamed_1_10e116_i10_y_1;
  wire  unnamed_1_10e116_i12_a;
  wire  unnamed_1_10e116_i12_b;
  wire  unnamed_1_10e116_i12_y;
  wire  unnamed_1_10e116_i12_y_1;
  wire  unnamed_1_10e116_i15_a;
  wire  unnamed_1_10e116_i15_b;
  wire  unnamed_1_10e116_i15_y;
  wire  unnamed_1_10e116_i15_y_1;
  wire  unnamed_1_10e116_i16_a;
  wire  unnamed_1_10e116_i16_b;
  wire  unnamed_1_10e116_i16_y;
  wire  unnamed_1_10e116_i16_y_1;
  wire  unnamed_1_10e116_i5_a;
  wire  unnamed_1_10e116_i5_b;
  wire  unnamed_1_10e116_i5_y;
  wire  unnamed_1_10e116_i5_y_1;
  wire  unnamed_1_10e116_i9_a;
  wire  unnamed_1_10e116_i9_b;
  wire  unnamed_1_10e116_i9_y;
  wire  unnamed_1_10e116_i9_y_1;

  wire  gnd;
  wire  page1_gnd;
  wire  vee;
  wire  page1_vee;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vee = glbl.vee;
  assign page1_vee = vee;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

// begin instances 

  ids_c10 page1_i1  (.pin1(unnamed_1_10e116_i5_y),
	.pin2(unnamed_1_10e116_i9_b),
	.pin3(unnamed_1_10e116_i9_y),
	.pin4(unnamed_1_10e116_i10_b),
	.pin5(unnamed_1_10e116_i10_y_1),
	.pin6(unnamed_1_10e116_i5_y_1),
	.pin7(unnamed_1_10e116_i9_a),
	.pin8(unnamed_1_10e116_i9_y_1),
	.pin9(unnamed_1_10e116_i10_a),
	.pin10(unnamed_1_10e116_i10_y));

  testpoint_l page1_i3  (.a(unnamed_1_10e116_i5_b));

  testpoint_l page1_i4  (.a(unnamed_1_10e116_i5_a));

  \10e116  page1_i5  (.a(unnamed_1_10e116_i5_a),
	.\b* (unnamed_1_10e116_i5_b),
	.ref(/* unconnected */),
	.y(unnamed_1_10e116_i5_y_1),
	.\y* (unnamed_1_10e116_i5_y));
  defparam page1_i5.size = 1;

  \10e116  page1_i9  (.a(unnamed_1_10e116_i9_a),
	.\b* (unnamed_1_10e116_i9_b),
	.ref(/* unconnected */),
	.y(unnamed_1_10e116_i9_y_1),
	.\y* (unnamed_1_10e116_i9_y));
  defparam page1_i9.size = 1;

  \10e116  page1_i10  (.a(unnamed_1_10e116_i10_a),
	.\b* (unnamed_1_10e116_i10_b),
	.ref(/* unconnected */),
	.y(unnamed_1_10e116_i10_y),
	.\y* (unnamed_1_10e116_i10_y_1));
  defparam page1_i10.size = 1;

  ids_c10 page1_i11  (.pin1(unnamed_1_10e116_i12_b),
	.pin2(unnamed_1_10e116_i12_y_1),
	.pin3(unnamed_1_10e116_i15_b),
	.pin4(unnamed_1_10e116_i15_y_1),
	.pin5(unnamed_1_10e116_i16_b),
	.pin6(unnamed_1_10e116_i12_a),
	.pin7(unnamed_1_10e116_i12_y),
	.pin8(unnamed_1_10e116_i15_a),
	.pin9(unnamed_1_10e116_i15_y),
	.pin10(unnamed_1_10e116_i16_a));

  \10e116  page1_i12  (.a(unnamed_1_10e116_i12_a),
	.\b* (unnamed_1_10e116_i12_b),
	.ref(/* unconnected */),
	.y(unnamed_1_10e116_i12_y),
	.\y* (unnamed_1_10e116_i12_y_1));
  defparam page1_i12.size = 1;

  \10e116  page1_i15  (.a(unnamed_1_10e116_i15_a),
	.\b* (unnamed_1_10e116_i15_b),
	.ref(/* unconnected */),
	.y(unnamed_1_10e116_i15_y),
	.\y* (unnamed_1_10e116_i15_y_1));
  defparam page1_i15.size = 1;

  \10e116  page1_i16  (.a(unnamed_1_10e116_i16_a),
	.\b* (unnamed_1_10e116_i16_b),
	.ref(/* unconnected */),
	.y(unnamed_1_10e116_i16_y_1),
	.\y* (unnamed_1_10e116_i16_y));
  defparam page1_i16.size = 1;

  testpoint_l page1_i17  (.a(unnamed_1_10e116_i16_y_1));

  testpoint_l page1_i18  (.a(unnamed_1_10e116_i16_y));

  rsmd0805 page1_i19  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i5_b));

  rsmd0805 page1_i20  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i5_a));

  rsmd0805 page1_i21  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i9_a));

  rsmd0805 page1_i22  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i10_a));

  rsmd0805 page1_i23  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i9_b));

  rsmd0805 page1_i24  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i10_b));

  rsmd0805 page1_i25  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i16_a));

  rsmd0805 page1_i26  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i12_a));

  rsmd0805 page1_i27  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i15_a));

  rsmd0805 page1_i28  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i12_b));

  rsmd0805 page1_i29  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i16_b));

  rsmd0805 page1_i30  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i15_b));

  csmd0603 page1_i31  (.a({glbl.gnd}),
	.b({glbl.vee}));

  csmd0603 page1_i32  (.a({glbl.gnd}),
	.b({glbl.vee}));

endmodule // ribbondelay(sch_1) 
