// generated by newgenasym  Tue Mar 29 11:58:07 2011


module max328 (a0, a1, a2, en, gnd, in1, in2, in3, in4, in5, in6, in7, in8, out,
        vminus, vplus);
    output a0;
    output a1;
    output a2;
    output en;
    input gnd;
    input in1;
    input in2;
    input in3;
    input in4;
    input in5;
    input in6;
    input in7;
    input in8;
    output out;
    input vminus;
    input vplus;


    initial
        begin
        end

endmodule
