-- generated by newgenasym Tue Mar 29 11:58:07 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX328 is
    port (    
	A0:        OUT    STD_LOGIC;    
	A1:        OUT    STD_LOGIC;    
	A2:        OUT    STD_LOGIC;    
	EN:        OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	IN1:       IN     STD_LOGIC;    
	IN2:       IN     STD_LOGIC;    
	IN3:       IN     STD_LOGIC;    
	IN4:       IN     STD_LOGIC;    
	IN5:       IN     STD_LOGIC;    
	IN6:       IN     STD_LOGIC;    
	IN7:       IN     STD_LOGIC;    
	IN8:       IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VMINUS:    IN     STD_LOGIC;    
	VPLUS:     IN     STD_LOGIC);
end MAX328;
