// generated by newgenasym  Tue Mar 29 11:59:51 2011


module hfbr_1312t (anode, \case , cathode);
    input anode;
    input \case ;
    input cathode;


    initial
        begin
        end

endmodule
