-- generated by newgenasym Tue Mar 29 11:57:56 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM385BZ is
    port (    
	ANODE:     INOUT  STD_LOGIC;    
	CATHODE:   INOUT  STD_LOGIC);
end LM385BZ;
