// generated by newgenasym  Tue Mar 29 12:00:39 2011


module res_lj (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
