// generated by newgenasym  Tue Mar 29 11:57:30 2011


module fec32d_outconn (card_id_d, cdata, dav_d, full_d, out, serout_d, trigsum_d);
    input [6:1] card_id_d;
    input [7:0] cdata;
    input [8:1] dav_d;
    input [8:1] full_d;
    input [3:0] out;
    input [8:1] serout_d;
    input [4:1] trigsum_d;


    initial
        begin
        end

endmodule
