-- generated by newgenasym Tue Mar 29 11:57:30 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity FEC32D_OUTCONN is
    port (    
	CARD_ID_D: IN     STD_LOGIC_VECTOR (6 DOWNTO 1);    
	CDATA:     IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	DAV_D:     IN     STD_LOGIC_VECTOR (8 DOWNTO 1);    
	FULL_D:    IN     STD_LOGIC_VECTOR (8 DOWNTO 1);    
	\out\:     IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	SEROUT_D:  IN     STD_LOGIC_VECTOR (8 DOWNTO 1);    
	TRIGSUM_D: IN     STD_LOGIC_VECTOR (4 DOWNTO 1));
end FEC32D_OUTCONN;
