// generated by newgenasym  Wed Oct 01 14:44:53 2014


module \lvds-ecl  (ecl_out, lvdsh_in, lvdsl_in);
    output ecl_out;
    input lvdsh_in;
    input lvdsl_in;


    initial
        begin
        end

endmodule
