-- generated by newgenasym Wed Oct 01 14:44:53 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \lvds-ecl\ is
    port (    
	ECL_OUT:   OUT    STD_LOGIC;    
	LVDSH_IN:  IN     STD_LOGIC;    
	LVDSL_IN:  IN     STD_LOGIC);
end \lvds-ecl\;
