// generated by newgenasym  Tue Mar 29 11:56:45 2011


module adop177g_l (nin, nvss, out, pin, pvss);
    inout nin;
    input nvss;
    inout out;
    inout pin;
    input pvss;


    initial
        begin
        end

endmodule
