// generated by newgenasym  Thu Feb 05 15:02:25 2015


module select_lo_src (\ddgt* , lo, \lo* , \mtcd_lo* , sel, \ttl_lockout* );
    input \ddgt* ;
    output lo;
    output \lo* ;
    input \mtcd_lo* ;
    input sel;
    output \ttl_lockout* ;


    initial
        begin
        end

endmodule
