// generated by newgenasym  Tue Oct 07 15:58:10 2014


module select_lo_src (\ddgt* , lo, \lo* , \mtcd_lo* , sel);
    input \ddgt* ;
    output lo;
    output \lo* ;
    input \mtcd_lo* ;
    input sel;


    initial
        begin
        end

endmodule
