-- generated by newgenasym Thu Feb 05 15:02:25 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity select_lo_src is
    port (    
	\ddgt*\:   IN     STD_LOGIC;    
	LO:        OUT    STD_LOGIC;    
	\lo*\:     OUT    STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC;    
	SEL:       IN     STD_LOGIC;    
	\ttl_lockout*\: OUT    STD_LOGIC);
end select_lo_src;
