-- generated by newgenasym Thu Feb 05 12:27:11 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity select_lo_src is
    port (    
	\ddgt*\:   IN     STD_LOGIC;    
	LO:        OUT    STD_LOGIC;    
	\lo*\:     OUT    STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC;    
	SEL:       IN     STD_LOGIC;    
	TTL_LOCKOUT: OUT    STD_LOGIC);
end select_lo_src;
