`timescale 1ns/1ns

module caen_chat (gtrigh_ecl, gtrigl_ecl, sync24h_ecl, sync24h_lvds, sync24l_ecl, sync24l_lvds, synch_ecl, 
    synch_lvds, syncl_ecl, syncl_lvds );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:18 2015
// from tubii_lib/CAEN_CHAT/sch_1

  inout  gtrigh_ecl;
  inout  gtrigl_ecl;
  inout  sync24h_ecl;
  inout  sync24h_lvds;
  inout  sync24l_ecl;
  inout  sync24l_lvds;
  inout  synch_ecl;
  inout  synch_lvds;
  inout  syncl_ecl;
  inout  syncl_lvds;
  // global signal glbl.gnd;
  // global signal glbl.vee;
  // global signal glbl.vp3_3;
  // global signal glbl.vtt;

  wire  unnamed_1_10ep90_i55_d;
  wire  unnamed_1_10ep90_i55_d_1;
  wire  unnamed_1_10ep90_i55_q;
  wire  unnamed_1_10ep90_i55_q_1;
  wire  unnamed_1_10ep90_i64_d;
  wire  unnamed_1_10ep90_i64_d_1;
  wire  unnamed_1_10ep90_i64_q;
  wire  unnamed_1_10h116_i70_y;
  wire  unnamed_1_lvdsdriverds10_i47_in;
  wire  unnamed_1_lvdsdriverds10_i47_in_1;
  wire  unnamed_1_lvdsdriverds10_i56_in;
  wire  unnamed_1_lvdsdriverds10_i56_in_1;
  wire  unnamed_1_mmbth81_i67_c;
  wire  unnamed_1_mmbth81_i67_e;
  wire  unnamed_1_rsmd0805_i59_a;

  wire  gnd;
  wire  page1_gnd;
  wire  vee;
  wire  page1_vee;
  wire  vp3_3;
  wire  page1_vp3_3;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vee = glbl.vee;
  assign page1_vee = vee;
  assign vp3_3 = glbl.vp3_3;
  assign page1_vp3_3 = vp3_3;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;

// begin instances 

  rsmd0805 page1_i4  (.a(unnamed_1_mmbth81_i67_c),
	.b({glbl.vee}));

  testpoint_l page1_i8  (.a(unnamed_1_mmbth81_i67_e));

  rsmd0805 page1_i9  (.a(unnamed_1_mmbth81_i67_e),
	.b({glbl.gnd}));

  rsmd0805 page1_i14  (.a({glbl.vtt}),
	.b(unnamed_1_10h116_i70_y));

  lvds_driver_ds10 page1_i47  (.\1 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\in+ (unnamed_1_lvdsdriverds10_i47_in_1),
	.\in- (unnamed_1_lvdsdriverds10_i47_in),
	.\out+ (sync24h_lvds),
	.\out- (sync24l_lvds));

  rsmd0805 page1_i48  (.a({glbl.vp3_3}),
	.b(unnamed_1_lvdsdriverds10_i47_in_1));

  rsmd0805 page1_i49  (.a({glbl.vp3_3}),
	.b(unnamed_1_lvdsdriverds10_i47_in));

  rsmd0805 page1_i50  (.a(unnamed_1_10ep90_i55_q_1),
	.b({glbl.vp3_3}));

  max9376 page1_i51  (.in2(unnamed_1_10ep90_i55_q),
	.\in2* (unnamed_1_10ep90_i55_q_1),
	.out2(unnamed_1_lvdsdriverds10_i47_in_1),
	.\out2* (unnamed_1_lvdsdriverds10_i47_in),
	.out1(/* unconnected */),
	.\out1* (/* unconnected */),
	.in1(/* unconnected */),
	.\in1* (/* unconnected */));

  rsmd0805 page1_i52  (.a({glbl.gnd}),
	.b(unnamed_1_10ep90_i55_q_1));

  rsmd0805 page1_i53  (.a(unnamed_1_10ep90_i55_q),
	.b({glbl.vp3_3}));

  rsmd0805 page1_i54  (.a({glbl.gnd}),
	.b(unnamed_1_10ep90_i55_q));

  \10ep90  page1_i55  (.d(unnamed_1_10ep90_i55_d),
	.\d* (unnamed_1_10ep90_i55_d_1),
	.q(unnamed_1_10ep90_i55_q),
	.\q* (unnamed_1_10ep90_i55_q_1));

  lvds_driver_ds10 page1_i56  (.\1 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\in+ (unnamed_1_lvdsdriverds10_i56_in),
	.\in- (unnamed_1_lvdsdriverds10_i56_in_1),
	.\out+ (synch_lvds),
	.\out- (syncl_lvds));

  rsmd0805 page1_i59  (.a(unnamed_1_rsmd0805_i59_a),
	.b({glbl.vp3_3}));

  max9376 page1_i60  (.in2(unnamed_1_lvdsdriverds10_i56_in),
	.\in2* (unnamed_1_lvdsdriverds10_i56_in_1),
	.out2(unnamed_1_10ep90_i64_q),
	.\out2* (unnamed_1_rsmd0805_i59_a),
	.out1(/* unconnected */),
	.\out1* (/* unconnected */),
	.in1(/* unconnected */),
	.\in1* (/* unconnected */));

  rsmd0805 page1_i61  (.a({glbl.gnd}),
	.b(unnamed_1_rsmd0805_i59_a));

  rsmd0805 page1_i62  (.a(unnamed_1_10ep90_i64_q),
	.b({glbl.vp3_3}));

  rsmd0805 page1_i63  (.a({glbl.gnd}),
	.b(unnamed_1_10ep90_i64_q));

  \10ep90  page1_i64  (.d(unnamed_1_10ep90_i64_d),
	.\d* (unnamed_1_10ep90_i64_d_1),
	.q(unnamed_1_10ep90_i64_q),
	.\q* (unnamed_1_rsmd0805_i59_a));

  rsmd0805 page1_i65  (.a(unnamed_1_lvdsdriverds10_i56_in_1),
	.b({glbl.vp3_3}));

  rsmd0805 page1_i66  (.a(unnamed_1_lvdsdriverds10_i56_in),
	.b({glbl.vp3_3}));

  mmbth81 page1_i67  (.b(unnamed_1_10h116_i70_y),
	.c(unnamed_1_mmbth81_i67_c),
	.e(unnamed_1_mmbth81_i67_e));

  \10h116  page1_i68  (.a(sync24h_ecl),
	.\b* (sync24l_ecl),
	.v(/* unconnected */),
	.y(unnamed_1_10ep90_i55_d),
	.\y* (unnamed_1_10ep90_i55_d_1));
  defparam page1_i68.section = 1;
  defparam page1_i68.size = 1;

  \10h116  page1_i69  (.a(synch_ecl),
	.\b* (syncl_ecl),
	.v(/* unconnected */),
	.y(unnamed_1_10ep90_i64_d),
	.\y* (unnamed_1_10ep90_i64_d_1));
  defparam page1_i69.section = 1;
  defparam page1_i69.size = 1;

  \10h116  page1_i70  (.a(gtrigh_ecl),
	.\b* (gtrigl_ecl),
	.v(/* unconnected */),
	.y(unnamed_1_10h116_i70_y),
	.\y* (/* unconnected */));
  defparam page1_i70.section = 1;
  defparam page1_i70.size = 1;

endmodule // caen_chat(sch_1) 
