// generated by newgenasym  Tue Mar 29 11:59:48 2011


module ad9500 (cs, d, \ecl#20com , \ecl#20ref , le, \off#20adj , q, \q* , \qr* , reset,
        \reset* , rs, trig, \trig* );
    input cs;
    input [7:0] d;
    input \ecl#20com ;
    output \ecl#20ref ;
    input le;
    input \off#20adj ;
    output q;
    output \q* ;
    output \qr* ;
    input reset;
    input \reset* ;
    input rs;
    input trig;
    input \trig* ;


    initial
        begin
        end

endmodule
