`timescale 1ns/1ns

module cntrl_register (clk, data, data_out, data_rdy, default_clk_select, display, ecal_setup, le, lo_select, 
    read_enable );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:19 2015
// from tubii_lib/CNTRL_REGISTER/sch_1

  inout  clk;
  inout  data;
  inout  data_out;
  inout  data_rdy;
  inout  default_clk_select;
  inout [2:0] display;
  inout  ecal_setup;
  inout  le;
  inout  lo_select;
  inout  read_enable;
  // global signal glbl.gnd;
  // global signal glbl.vcc;

  wire  unnamed_1_74f164_i1_q0;
  wire  unnamed_1_74f164_i1_q1;
  wire  unnamed_1_74f164_i1_q2;
  wire  unnamed_1_74f164_i1_q3;
  wire  unnamed_1_74f164_i1_q4;
  wire  unnamed_1_74f164_i1_q5;
  wire  unnamed_1_74f164_i1_q6;
  wire  unnamed_1_74f164_i1_q7;
  wire  unnamed_1_74hct165_i16_ce;
  wire  unnamed_1_hct374_i5_q;
  wire  unnamed_1_hct374_i6_q;
  wire  unnamed_1_hct374_i7_q;
  wire  unnamed_1_hct374_i8_q;
  wire  unnamed_1_hct374_i9_q;

  wire [2:0] page1_display;
  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;

  assign page1_display[0:0] = display[0:0];
  assign page1_display[1:1] = display[1:1];
  assign page1_display[2:2] = display[2:2];
  assign page1_display[2:0] = display[2:0];
  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign unnamed_1_hct374_i5_q = display[2:2];
  assign unnamed_1_hct374_i6_q = display[1:1];
  assign unnamed_1_hct374_i7_q = display[0:0];

// begin instances 

  \74f164  page1_i1  (.cp(clk),
	.dsa(data),
	.dsb(le),
	.\mr* (glbl.vcc),
	.q0(unnamed_1_74f164_i1_q0),
	.q1(unnamed_1_74f164_i1_q1),
	.q2(unnamed_1_74f164_i1_q2),
	.q3(unnamed_1_74f164_i1_q3),
	.q4(unnamed_1_74f164_i1_q4),
	.q5(unnamed_1_74f164_i1_q5),
	.q6(unnamed_1_74f164_i1_q6),
	.q7(unnamed_1_74f164_i1_q7),
	.q(/* unconnected */));

  hct374 page1_i2  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i1_q0),
	.q(default_clk_select));

  hct374 page1_i3  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i1_q1),
	.q(lo_select));

  hct374 page1_i4  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i1_q2),
	.q(ecal_setup));

  hct374 page1_i5  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i1_q3),
	.q(unnamed_1_hct374_i5_q));

  hct374 page1_i6  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i1_q4),
	.q(unnamed_1_hct374_i6_q));

  hct374 page1_i7  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i1_q5),
	.q(unnamed_1_hct374_i7_q));

  hct374 page1_i8  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i1_q6),
	.q(unnamed_1_hct374_i8_q));

  hct374 page1_i9  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i1_q7),
	.q(unnamed_1_hct374_i9_q));

  testpoint_l page1_i12  (.a(unnamed_1_hct374_i8_q));

  testpoint_l page1_i14  (.a(unnamed_1_hct374_i9_q));

  \74hct165  page1_i16  (.\ce* (unnamed_1_74hct165_i16_ce),
	.cp(clk),
	.d0(unnamed_1_74f164_i1_q0),
	.d1(unnamed_1_74f164_i1_q1),
	.d2(unnamed_1_74f164_i1_q2),
	.d3(unnamed_1_74f164_i1_q3),
	.d4(unnamed_1_74f164_i1_q4),
	.d5(unnamed_1_74f164_i1_q5),
	.d6(unnamed_1_74f164_i1_q6),
	.d7(unnamed_1_74f164_i1_q7),
	.ds(data_out),
	.\pl* (read_enable),
	.q7(data_out),
	.\q7* (/* unconnected */));

  testpoint_l page1_i17  (.a(unnamed_1_74f164_i1_q0));

  testpoint_l page1_i18  (.a(unnamed_1_74f164_i1_q1));

  testpoint_l page1_i19  (.a(unnamed_1_74f164_i1_q2));

  testpoint_l page1_i20  (.a(unnamed_1_74f164_i1_q3));

  testpoint_l page1_i21  (.a(unnamed_1_74f164_i1_q4));

  testpoint_l page1_i22  (.a(unnamed_1_74f164_i1_q5));

  testpoint_l page1_i23  (.a(unnamed_1_74f164_i1_q6));

  testpoint_l page1_i24  (.a(unnamed_1_74f164_i1_q7));

  f06 page1_i25  (.a(read_enable),
	.\y* (unnamed_1_74hct165_i16_ce),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i25.size = 1;

  rsmd0805 page1_i26  (.a({glbl.vcc}),
	.b(unnamed_1_74hct165_i16_ce));

  csmd0603 page1_i27  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  csmd0603 page1_i28  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  csmd0603 page1_i29  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  csmd0603 page1_i30  (.a({glbl.gnd}),
	.b({glbl.vcc}));

endmodule // cntrl_register(sch_1) 
