// generated by newgenasym  Tue Mar 29 11:59:46 2011


module \10h605  (clk, \clk* , d, \d* , mr, q, ref);
    parameter    size = 1;
    input clk;
    input \clk* ;
    input [size-1:0] d;
    input [size-1:0] \d* ;
    input mr;
    output [size-1:0] q;
    output ref;


    initial
        begin
        end

endmodule
