// generated by newgenasym  Tue Mar 29 11:56:46 2011


module adref02c_l (gnd, trim, vin, vout);
    inout gnd;
    input trim;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
