-- generated by newgenasym Thu May 28 17:04:15 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LED_L is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end LED_L;
