-- generated by newgenasym Thu Oct 30 17:03:46 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_l is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end led_l;
