// generated by newgenasym  Tue Mar 29 11:58:25 2011


module mic2937a33 (ground, \input , \output );
    inout ground;
    input \input ;
    output \output ;


    initial
        begin
        end

endmodule
