-- generated by newgenasym Tue Mar 29 11:58:42 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SEQ96NEWT is
    port (    
	ADC_DONE:  OUT    STD_LOGIC;    
	CCLK:      IN     STD_LOGIC;    
	M2:        OUT    STD_LOGIC;    
	\program*\: IN     STD_LOGIC;    
	\pwrdwn*\: IN     STD_LOGIC;    
	\rdata*\:  OUT    STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	RTRIG:     IN     STD_LOGIC;    
	SDIN:      IN     STD_LOGIC;    
	SDOUT:     OUT    STD_LOGIC;    
	SPAREIN:   IN     STD_LOGIC_VECTOR (2 DOWNTO 0);    
	SPAREOUT:  OUT    STD_LOGIC_VECTOR (2 DOWNTO 0);    
	\sqadc_busy*\: IN     STD_LOGIC;    
	SQCADD_ENABLE: OUT    STD_LOGIC;    
	SQCHIP_SEL_EN: OUT    STD_LOGIC;    
	\sqchold*\: OUT    STD_LOGIC;    
	SQCLK:     IN     STD_LOGIC;    
	\sqconvert_start*\: OUT    STD_LOGIC;    
	SQCREG_REQ: IN     STD_LOGIC;    
	SQCREG_SEL: OUT    STD_LOGIC;    
	SQD:       INOUT  STD_LOGIC_VECTOR (31 DOWNTO 0);    
	SQDAV:     IN     STD_LOGIC_VECTOR (32 DOWNTO 1);    
	SQDAV32OR: OUT    STD_LOGIC;    
	\sqenw-\:  OUT    STD_LOGIC_VECTOR (3 DOWNTO 1);    
	SQFECBUSY: OUT    STD_LOGIC;    
	SQLATCH:   OUT    STD_LOGIC_VECTOR (4 DOWNTO 1);    
	\sqmemory_ack*\: IN     STD_LOGIC;    
	\sqmemory_request*\: OUT    STD_LOGIC;    
	\sqrd_strobe*\: OUT    STD_LOGIC;    
	SQTAG:     OUT    STD_LOGIC_VECTOR (4 DOWNTO 0);    
	\sqxreg_rd*\: IN     STD_LOGIC;    
	SQXREG_SEL: IN     STD_LOGIC_VECTOR (2 DOWNTO 0);    
	\sqxreg_wr*\: IN     STD_LOGIC);
end SEQ96NEWT;
