-- generated by newgenasym Tue Mar 29 11:58:32 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PCAP is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC);
end PCAP;
