-- generated by newgenasym Tue Mar 29 12:00:56 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MRF5943_J is
    port (    
	B:         IN     STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end MRF5943_J;
