-- generated by newgenasym Tue Mar 29 11:57:42 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LED_L is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end LED_L;
