// generated by newgenasym  Mon Sep 08 14:08:58 2014


module opa2277 (\+in_a , \+in_b , \-in_a , \-in_b , out_a, out_b);
    inout \+in_a ;
    inout \+in_b ;
    inout \-in_a ;
    inout \-in_b ;
    inout out_a;
    inout out_b;


    initial
        begin
        end

endmodule
