// generated by newgenasym  Wed Oct 22 13:48:56 2014


module opa2277 (\+in_a , \+in_b , \-in_a , \-in_b , out_a, out_b, \v+ , \v- );
    inout \+in_a ;
    inout \+in_b ;
    inout \-in_a ;
    inout \-in_b ;
    inout out_a;
    inout out_b;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
