-- generated by newgenasym Mon Sep 08 14:08:58 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa2277 is
    port (    
	\+in_a\:   INOUT  STD_LOGIC;    
	\+in_b\:   INOUT  STD_LOGIC;    
	\-in_a\:   INOUT  STD_LOGIC;    
	\-in_b\:   INOUT  STD_LOGIC;    
	OUT_A:     INOUT  STD_LOGIC;    
	OUT_B:     INOUT  STD_LOGIC);
end opa2277;
