// generated by newgenasym  Tue Mar 29 12:00:26 2011


module he721c0510 (in_1, in_2, out_1, out_2, s1, s2);
    inout in_1;
    inout in_2;
    inout out_1;
    inout out_2;
    input s1;
    input s2;


    initial
        begin
        end

endmodule
