-- generated by newgenasym Tue Mar 29 12:00:26 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HE721C0510 is
    port (    
	IN_1:      INOUT  STD_LOGIC;    
	IN_2:      INOUT  STD_LOGIC;    
	OUT_1:     INOUT  STD_LOGIC;    
	OUT_2:     INOUT  STD_LOGIC;    
	S1:        IN     STD_LOGIC;    
	S2:        IN     STD_LOGIC);
end HE721C0510;
