// generated by newgenasym  Tue Mar 29 12:00:58 2011


module opjrk (nin, nvss, out, pin, pvss);
    input nin;
    inout nvss;
    output out;
    input pin;
    inout pvss;


    initial
        begin
        end

endmodule
