-- generated by newgenasym Tue Mar 29 12:00:58 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OPJRK is
    port (    
	NIN:       IN     STD_LOGIC;    
	NVSS:      INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	PIN:       IN     STD_LOGIC;    
	PVSS:      INOUT  STD_LOGIC);
end OPJRK;
