// generated by newgenasym  Tue Mar 29 11:59:43 2011


module \10h603  (d, len, mr, \oeecl* , q);
    parameter    size = 1;
    input [size-1:0] d;
    input len;
    input mr;
    input \oeecl* ;
    output [size-1:0] q;


    initial
        begin
        end

endmodule
