// generated by newgenasym  Tue Mar 29 12:00:44 2011


module smbconn (pin1, pin2, pin3, pin4, pin5);
    inout pin1;
    inout pin2;
    inout pin3;
    inout pin4;
    inout pin5;


    initial
        begin
        end

endmodule
