-- generated by newgenasym Tue Mar 29 12:00:44 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SMBCONN is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      INOUT  STD_LOGIC;    
	PIN5:      INOUT  STD_LOGIC);
end SMBCONN;
