// generated by newgenasym  Tue Mar 29 11:56:30 2011


module \4067b_l  (\inh* , s, x, x0, x1, x10, x11, x12, x13, x14, x15, x2, x3, x4, x5,
        x6, x7, x8, x9);
    parameter    size = 1;
    input \inh* ;
    input [3:0] s;
    inout [size-1:0] x;
    inout [size-1:0] x0;
    inout [size-1:0] x1;
    inout [size-1:0] x10;
    inout [size-1:0] x11;
    inout [size-1:0] x12;
    inout [size-1:0] x13;
    inout [size-1:0] x14;
    inout [size-1:0] x15;
    inout [size-1:0] x2;
    inout [size-1:0] x3;
    inout [size-1:0] x4;
    inout [size-1:0] x5;
    inout [size-1:0] x6;
    inout [size-1:0] x7;
    inout [size-1:0] x8;
    inout [size-1:0] x9;


    initial
        begin
        end

endmodule
