-- generated by newgenasym Fri Mar 18 17:11:32 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74f06\ is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	\y0*\:     OUT    STD_LOGIC;    
	\y1*\:     OUT    STD_LOGIC;    
	\y2*\:     OUT    STD_LOGIC;    
	\y3*\:     OUT    STD_LOGIC;    
	\y4*\:     OUT    STD_LOGIC;    
	\y5*\:     OUT    STD_LOGIC);
end \74f06\;
