`timescale 1ns/1ns

module comparator_ports (fast_anpulse, fast_comp_outh, fast_comp_outl, tune_anpulse, tune_comp_outh, tune_comp_outl 
    );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:13 2015
// from tubii_lib/COMPARATOR_PORTS/sch_1

  inout  fast_anpulse;
  inout  fast_comp_outh;
  inout  fast_comp_outl;
  inout  tune_anpulse;
  inout  tune_comp_outh;
  inout  tune_comp_outl;
  // global signal glbl.gnd;

  wire  gnd;
  wire  page1_gnd;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  testpoint_l page1_i1  (.a(tune_comp_outh));

  testpoint_l page1_i2  (.a(tune_comp_outl));

  testpoint_l page1_i3  (.a(fast_comp_outh));

  testpoint_l page1_i4  (.a(fast_comp_outl));

  testpoint_l page1_i5  (.a(fast_anpulse));

  testpoint_l page1_i6  (.a(glbl.gnd));

  testpoint_l page1_i9  (.a(tune_anpulse));

  testpoint_l page1_i10  (.a(glbl.gnd));

endmodule // comparator_ports(sch_1) 
