-- generated by newgenasym Tue Mar 29 11:57:35 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HVCAP is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end HVCAP;
