// generated by newgenasym  Tue Mar 29 11:59:03 2011


module thm81000 (a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, \cas* , dq0, dq1, dq2, dq3,
        dq4, dq5, dq6, dq7, \ras* , \we* );
    input a0;
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input \cas* ;
    inout dq0;
    inout dq1;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    input \ras* ;
    input \we* ;


    initial
        begin
        end

endmodule
