// generated by newgenasym  Tue Mar 29 11:59:59 2011


module idt7282 (da, db, \efa* , \efb* , \ffa* , \ffb* , \fla/rta* , \flb/rtb* , qa, qb,
        \ra* , \rb* , \rsa* , \rsb* , \wa* , \wb* , \xia* , \xib* , \xoa/hfa* , \xob/hfb* );
    parameter    size = 1;
    input [size-1:0] da;
    input [size-1:0] db;
    output \efa* ;
    output \efb* ;
    output \ffa* ;
    output \ffb* ;
    input \fla/rta* ;
    input \flb/rtb* ;
    output [size-1:0] qa;
    output [size-1:0] qb;
    input \ra* ;
    input \rb* ;
    input \rsa* ;
    input \rsb* ;
    input \wa* ;
    input \wb* ;
    input \xia* ;
    input \xib* ;
    output \xoa/hfa* ;
    output \xob/hfb* ;


    initial
        begin
        end

endmodule
