// generated by newgenasym  Tue Mar 29 11:58:01 2011


module max120 (agnd, ain, \busy* , clkin, \conv* , \cs* , d0, d1, d10, d11, d2, d3,
        d4, d5, d6, d7, d8, d9, dgnd, mode, \rd* , vdd, vref, vss);
    input agnd;
    inout ain;
    output \busy* ;
    input clkin;
    input \conv* ;
    input \cs* ;
    output d0;
    output d1;
    output d10;
    output d11;
    output d2;
    output d3;
    output d4;
    output d5;
    output d6;
    output d7;
    output d8;
    output d9;
    input dgnd;
    input mode;
    input \rd* ;
    input vdd;
    inout vref;
    input vss;


    initial
        begin
        end

endmodule
