-- generated by newgenasym Tue Mar 29 11:56:04 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1n914sz\ is
    generic (
        size:positive:= 1
            );
    port (    
	AN:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	CAT:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \1n914sz\;
