// generated by newgenasym  Wed Feb 25 10:36:12 2015


module gt_delays_ports (dgt_n, dgt_p, lockout, \lockout* , \mtcd_lo* );
    input dgt_n;
    input dgt_p;
    input lockout;
    input \lockout* ;
    input \mtcd_lo* ;


    initial
        begin
        end

endmodule
