// generated by newgenasym  Thu Oct 09 11:07:09 2014


module gt_delays_ports (dgth, dgtl, lockout, \lockout* , \mtcd_lo* );
    input dgth;
    input dgtl;
    input lockout;
    input \lockout* ;
    input \mtcd_lo* ;


    initial
        begin
        end

endmodule
