-- generated by newgenasym Wed Feb 25 10:36:12 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity gt_delays_ports is
    port (    
	DGT_N:     IN     STD_LOGIC;    
	DGT_P:     IN     STD_LOGIC;    
	LOCKOUT:   IN     STD_LOGIC;    
	\lockout*\: IN     STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC);
end gt_delays_ports;
