-- generated by newgenasym Thu Oct 09 11:07:09 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity gt_delays_ports is
    port (    
	DGTH:      IN     STD_LOGIC;    
	DGTL:      IN     STD_LOGIC;    
	LOCKOUT:   IN     STD_LOGIC;    
	\lockout*\: IN     STD_LOGIC;    
	\mtcd_lo*\: IN     STD_LOGIC);
end gt_delays_ports;
