// generated by newgenasym  Tue Mar 29 11:57:32 2011


module fifo_ctrl (badd_out, bd, \bmem_read* , \bmem_write* , \bread_add_sel* ,
        \bread_enable* , \bwrite_add_sel* , \bwrite_enable* ,
        bxreg_add, \bxreg_rd* , \bxreg_wr* , cclk, m2, p10, p11, p28, p30,
        p34, p36, p38, p44, p46, p48, p52, p53, p7, p75, p76, p78, p8,
        \program* , \pwrdwn* , \rdata* , \reset* , rtrig, sdin, sdout);
    inout [19:0] badd_out;
    inout [19:0] bd;
    input \bmem_read* ;
    input \bmem_write* ;
    input \bread_add_sel* ;
    output \bread_enable* ;
    input \bwrite_add_sel* ;
    output \bwrite_enable* ;
    input [1:0] bxreg_add;
    input \bxreg_rd* ;
    input \bxreg_wr* ;
    input cclk;
    output m2;
    inout p10;
    inout p11;
    inout p28;
    inout p30;
    inout p34;
    inout p36;
    inout p38;
    inout p44;
    inout p46;
    inout p48;
    inout p52;
    inout p53;
    inout p7;
    inout p75;
    inout p76;
    inout p78;
    inout p8;
    input \program* ;
    input \pwrdwn* ;
    output \rdata* ;
    input \reset* ;
    input rtrig;
    input sdin;
    output sdout;


    initial
        begin
        end

endmodule
