-- generated by newgenasym Tue Mar 29 11:57:32 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity FIFO_CTRL is
    port (    
	BADD_OUT:  INOUT  STD_LOGIC_VECTOR (19 DOWNTO 0);    
	BD:        INOUT  STD_LOGIC_VECTOR (19 DOWNTO 0);    
	\bmem_read*\: IN     STD_LOGIC;    
	\bmem_write*\: IN     STD_LOGIC;    
	\bread_add_sel*\: IN     STD_LOGIC;    
	\bread_enable*\: OUT    STD_LOGIC;    
	\bwrite_add_sel*\: IN     STD_LOGIC;    
	\bwrite_enable*\: OUT    STD_LOGIC;    
	BXREG_ADD: IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\bxreg_rd*\: IN     STD_LOGIC;    
	\bxreg_wr*\: IN     STD_LOGIC;    
	CCLK:      IN     STD_LOGIC;    
	M2:        OUT    STD_LOGIC;    
	P10:       INOUT  STD_LOGIC;    
	P11:       INOUT  STD_LOGIC;    
	P28:       INOUT  STD_LOGIC;    
	P30:       INOUT  STD_LOGIC;    
	P34:       INOUT  STD_LOGIC;    
	P36:       INOUT  STD_LOGIC;    
	P38:       INOUT  STD_LOGIC;    
	P44:       INOUT  STD_LOGIC;    
	P46:       INOUT  STD_LOGIC;    
	P48:       INOUT  STD_LOGIC;    
	P52:       INOUT  STD_LOGIC;    
	P53:       INOUT  STD_LOGIC;    
	P7:        INOUT  STD_LOGIC;    
	P75:       INOUT  STD_LOGIC;    
	P76:       INOUT  STD_LOGIC;    
	P78:       INOUT  STD_LOGIC;    
	P8:        INOUT  STD_LOGIC;    
	\program*\: IN     STD_LOGIC;    
	\pwrdwn*\: IN     STD_LOGIC;    
	\rdata*\:  OUT    STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	RTRIG:     IN     STD_LOGIC;    
	SDIN:      IN     STD_LOGIC;    
	SDOUT:     OUT    STD_LOGIC);
end FIFO_CTRL;
