-- generated by newgenasym Tue Mar 29 11:56:30 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \4067b_l\ is
    generic (
        size:positive:= 1
            );
    port (    
	\inh*\:    IN     STD_LOGIC;    
	S:         IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	X:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X0:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X1:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X10:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X11:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X12:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X13:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X14:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X15:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X2:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X3:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X4:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X5:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X6:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X7:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X8:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	X9:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \4067b_l\;
