`timescale 1ns/1ns

module \ecl-nim  (ecl_in, nim_out );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:13 2015
// from tubii_lib/ECL-NIM/sch_1

  inout  ecl_in;
  inout  nim_out;
  // global signal glbl.gnd;
  // global signal glbl.vee;
  // global signal glbl.vtt;

  wire  unnamed_1_10e116_i22_b;
  wire  unnamed_1_10e116_i22_y;
  wire  unnamed_1_mpsh81_i4_c;

  wire  gnd;
  wire  page1_gnd;
  wire  vee;
  wire  page1_vee;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vee = glbl.vee;
  assign page1_vee = vee;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;

// begin instances 

  mpsh81 page1_i4  (.b(unnamed_1_10e116_i22_y),
	.c(unnamed_1_mpsh81_i4_c),
	.e(nim_out));

  rsmd0805 page1_i6  (.a({glbl.vee}),
	.b(unnamed_1_mpsh81_i4_c));

  rsmd0805 page1_i16  (.a({glbl.vtt}),
	.b(ecl_in));

  \10e116  page1_i22  (.a(ecl_in),
	.\b* (unnamed_1_10e116_i22_b),
	.ref(unnamed_1_10e116_i22_b),
	.y(unnamed_1_10e116_i22_y),
	.\y* (/* unconnected */));
  defparam page1_i22.size = 1;

  rsmd0805 page1_i27  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i22_y));

  csmd0805 page1_i30  (.a(unnamed_1_10e116_i22_b),
	.b({glbl.gnd}));

endmodule // \ecl-nim (sch_1) 
