-- generated by newgenasym Tue Mar 29 11:59:17 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity UPFTC16245 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (15 DOWNTO 0);    
	\eo1*\:    IN     STD_LOGIC;    
	\eo2*\:    IN     STD_LOGIC;    
	\eo3*\:    OUT    STD_LOGIC;    
	\eo4*\:    OUT    STD_LOGIC;    
	Y:         OUT    STD_LOGIC_VECTOR (15 DOWNTO 0));
end UPFTC16245;
