// generated by newgenasym  Tue Mar 29 11:57:58 2011


module lt1185 (fb, ground, ref, vin, vout);
    output fb;
    inout ground;
    inout ref;
    input vin;
    output vout;


    initial
        begin
        end

endmodule
