-- generated by newgenasym Tue Mar 29 11:57:58 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LT1185 is
    port (    
	FB:        OUT    STD_LOGIC;    
	GROUND:    INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC);
end LT1185;
