// generated by newgenasym  Tue Mar 29 11:58:30 2011


module mx584 (com, p10, p5, vsp);
    output com;
    input p10;
    input p5;
    input vsp;


    initial
        begin
        end

endmodule
