-- generated by newgenasym Tue Mar 29 11:58:30 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MX584 is
    port (    
	COM:       OUT    STD_LOGIC;    
	P10:       IN     STD_LOGIC;    
	P5:        IN     STD_LOGIC;    
	VSP:       IN     STD_LOGIC);
end MX584;
