`timescale 1ns/1ns

module gt_delays_ports (dgth, dgtl, lockout, \lockout* , \mtcd_lo*  );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:12 2015
// from tubii_lib/GT_DELAYS_PORTS/sch_1

  inout  dgth;
  inout  dgtl;
  inout  lockout;
  inout  \lockout* ;
  inout  \mtcd_lo* ;
  // global signal glbl.gnd;
  // global signal glbl.vtt;

  wire  unnamed_1_10h116_i15_y;
  wire  unnamed_1_10h116_i6_y;
  wire  unnamed_1_10h116_i6_y_1;

  wire  gnd;
  wire  page1_gnd;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  testpoint_l page1_i1  (.a(unnamed_1_10h116_i6_y));

  testpoint_l page1_i2  (.a(unnamed_1_10h116_i6_y_1));

  testpoint_l page1_i3  (.a(unnamed_1_10h116_i15_y));

  testpoint_l page1_i4  (.a(glbl.gnd));

  \10h116  page1_i6  (.a(dgth),
	.\b* (dgtl),
	.v(/* unconnected */),
	.y(unnamed_1_10h116_i6_y_1),
	.\y* (unnamed_1_10h116_i6_y));
  defparam page1_i6.size = 1;

  rsmd0805 page1_i8  (.a({glbl.vtt}),
	.b(dgth));

  rsmd0805 page1_i9  (.a({glbl.vtt}),
	.b(dgtl));

  testpoint_l page1_i10  (.a(\mtcd_lo* ));

  testpoint_l page1_i11  (.a(glbl.gnd));

  rsmd0805 page1_i12  (.a({glbl.vtt}),
	.b(lockout));

  rsmd0805 page1_i13  (.a({glbl.vtt}),
	.b(\lockout* ));

  \10h116  page1_i15  (.a(\lockout* ),
	.\b* (lockout),
	.v(/* unconnected */),
	.y(unnamed_1_10h116_i15_y),
	.\y* (/* unconnected */));
  defparam page1_i15.section = 1;
  defparam page1_i15.size = 1;

endmodule // gt_delays_ports(sch_1) 
