`timescale 1ns/1ns

module \lvds-ecl  (ecl_out, lvdsh_in, lvdsl_in );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:15 2015
// from tubii_lib/LVDS-ECL/sch_1

  inout  ecl_out;
  inout  lvdsh_in;
  inout  lvdsl_in;
  // global signal glbl.gnd;
  // global signal glbl.vp3_3;

  wire  unnamed_1_el91l_i42_in;
  wire  unnamed_1_el91l_i42_in_1;
  wire  unnamed_1_lvdsdriverds10_i25_out;
  wire  unnamed_1_lvdsdriverds10_i25_out_1;

  wire  gnd;
  wire  page1_gnd;
  wire  vp3_3;
  wire  page1_vp3_3;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vp3_3 = glbl.vp3_3;
  assign page1_vp3_3 = vp3_3;

// begin instances 

  lvds_driver_ds10 page1_i25  (.\1 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (/* unconnected */),
	.\in+ (lvdsh_in),
	.\in- (lvdsl_in),
	.\out+ (unnamed_1_lvdsdriverds10_i25_out_1),
	.\out- (unnamed_1_lvdsdriverds10_i25_out));

  max9376 page1_i41  (.in1(unnamed_1_lvdsdriverds10_i25_out_1),
	.\in1* (unnamed_1_lvdsdriverds10_i25_out),
	.out1(unnamed_1_el91l_i42_in),
	.\out1* (unnamed_1_el91l_i42_in_1),
	.out2(/* unconnected */),
	.\out2* (/* unconnected */),
	.in2(/* unconnected */),
	.\in2* (/* unconnected */));

  el91l page1_i42  (.in(unnamed_1_el91l_i42_in),
	.\in* (unnamed_1_el91l_i42_in_1),
	.out(ecl_out),
	.\out* (/* unconnected */),
	.vbb(/* unconnected */),
	.vbb2(/* unconnected */));

  rsmd0805 page1_i43  (.a(unnamed_1_el91l_i42_in_1),
	.b({glbl.vp3_3}));

  rsmd0805 page1_i44  (.a({glbl.gnd}),
	.b(unnamed_1_el91l_i42_in_1));

  rsmd0805 page1_i45  (.a(unnamed_1_el91l_i42_in),
	.b({glbl.vp3_3}));

  rsmd0805 page1_i46  (.a({glbl.gnd}),
	.b(unnamed_1_el91l_i42_in));

endmodule // \lvds-ecl (sch_1) 
