`timescale 1ns/1ns

module caen_coms (an_pulse_in, caen_out, clk, data, data_rdy, le, scope_out );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:18 2015
// from tubii_lib/CAEN_COMS/sch_1

  inout [11:0] an_pulse_in;
  inout [7:0] caen_out;
  inout  clk;
  inout  data;
  inout  data_rdy;
  inout  le;
  inout [7:0] scope_out;
  // global signal glbl.gnd;
  // global signal glbl.vcc;

  wire  unnamed_1_74f164_i56_q0;
  wire  unnamed_1_74f164_i56_q1;
  wire  unnamed_1_74f164_i56_q2;
  wire  unnamed_1_74f164_i56_q3;
  wire  unnamed_1_74f164_i56_q7;
  wire  unnamed_1_74f164_i66_q0;
  wire  unnamed_1_74f164_i66_q1;
  wire  unnamed_1_74f164_i66_q2;
  wire  unnamed_1_74f164_i66_q3;
  wire  unnamed_1_74f164_i66_q4;
  wire  unnamed_1_74f164_i66_q5;
  wire  unnamed_1_74f164_i66_q6;
  wire  unnamed_1_74f164_i66_q7;
  wire  unnamed_1_caenbuffer_i64_ctrl;
  wire  unnamed_1_caenbuffer_i67_ctrl;
  wire  unnamed_1_caenbuffer_i68_ctrl;
  wire  unnamed_1_caenbuffer_i69_ctrl;
  wire  unnamed_1_caenbuffer_i70_ctrl;
  wire  unnamed_1_caenbuffer_i71_ctrl;
  wire  unnamed_1_caenbuffer_i72_ctrl;
  wire  unnamed_1_caenbuffer_i73_ctrl;
  wire  unnamed_1_f07_i33_a;
  wire  unnamed_1_f07_i33_y;
  wire  unnamed_1_f07_i35_a;
  wire  unnamed_1_f07_i35_y;
  wire  unnamed_1_f07_i36_a;
  wire  unnamed_1_f07_i36_y;
  wire  unnamed_1_f07_i37_a;
  wire  unnamed_1_f07_i37_y;
  wire  unnamed_1_ledl_i82_a;
  wire  unnamed_1_ledl_i83_a;
  wire  unnamed_1_ledl_i84_a;
  wire  unnamed_1_ledl_i85_a;
  wire  unnamed_1_prma1c05b_i10_ctrlin;
  wire  unnamed_1_prma1c05b_i10_in;
  wire  unnamed_1_prma1c05b_i13_ctrlin;
  wire  unnamed_1_prma1c05b_i13_in;
  wire  unnamed_1_prma1c05b_i14_ctrlin;
  wire  unnamed_1_prma1c05b_i14_in;
  wire  unnamed_1_prma1c05b_i9_ctrlin;
  wire  unnamed_1_prma1c05b_i9_in;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;

  assign gnd  = glbl.gnd;

// begin instances 

  prma1c05b page1_i9  (.ctrl_in(unnamed_1_prma1c05b_i9_ctrlin),
	.ctrl_out(glbl.vcc),
	.in(unnamed_1_prma1c05b_i9_in),
	.in_cpy(/* unconnected */),
	.out1(an_pulse_in[0]),
	.out2(an_pulse_in[1]));

  prma1c05b page1_i10  (.ctrl_in(unnamed_1_prma1c05b_i10_ctrlin),
	.ctrl_out(glbl.vcc),
	.in(unnamed_1_prma1c05b_i10_in),
	.in_cpy(/* unconnected */),
	.out1(an_pulse_in[4]),
	.out2(an_pulse_in[5]));

  prma1c05b page1_i13  (.ctrl_in(unnamed_1_prma1c05b_i13_ctrlin),
	.ctrl_out(glbl.vcc),
	.in(unnamed_1_prma1c05b_i13_in),
	.in_cpy(/* unconnected */),
	.out1(an_pulse_in[2]),
	.out2(an_pulse_in[3]));

  prma1c05b page1_i14  (.ctrl_in(unnamed_1_prma1c05b_i14_ctrlin),
	.ctrl_out(glbl.vcc),
	.in(unnamed_1_prma1c05b_i14_in),
	.in_cpy(/* unconnected */),
	.out1(an_pulse_in[6]),
	.out2(an_pulse_in[7]));

  f07 page1_i33  (.a(unnamed_1_f07_i33_a),
	.y(unnamed_1_f07_i33_y));
  defparam page1_i33.size = 1;

  f07 page1_i35  (.a(unnamed_1_f07_i35_a),
	.y(unnamed_1_f07_i35_y));
  defparam page1_i35.size = 1;

  f07 page1_i36  (.a(unnamed_1_f07_i36_a),
	.y(unnamed_1_f07_i36_y));
  defparam page1_i36.size = 1;

  f07 page1_i37  (.a(unnamed_1_f07_i37_a),
	.y(unnamed_1_f07_i37_y));
  defparam page1_i37.size = 1;

  hct374 page1_i55  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i56_q0),
	.q(unnamed_1_f07_i33_a));

  \74f164  page1_i56  (.cp(clk),
	.dsa(data),
	.dsb(le),
	.\mr* (/* unconnected */),
	.q0(unnamed_1_74f164_i56_q0),
	.q1(unnamed_1_74f164_i56_q1),
	.q2(unnamed_1_74f164_i56_q2),
	.q3(unnamed_1_74f164_i56_q3),
	.q4(/* unconnected */),
	.q5(/* unconnected */),
	.q6(/* unconnected */),
	.q7(unnamed_1_74f164_i56_q7),
	.q(/* unconnected */));

  hct374 page1_i57  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i56_q1),
	.q(unnamed_1_f07_i35_a));

  hct374 page1_i58  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i56_q2),
	.q(unnamed_1_f07_i36_a));

  hct374 page1_i59  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i56_q3),
	.q(unnamed_1_f07_i37_a));

  caen_buffer page1_i64  (.ctrl(unnamed_1_caenbuffer_i64_ctrl),
	.in(unnamed_1_prma1c05b_i9_in),
	.out(caen_out[0]),
	.out_att(scope_out[0]));

  \74f164  page1_i66  (.cp(clk),
	.dsa(unnamed_1_74f164_i56_q7),
	.dsb(le),
	.\mr* (/* unconnected */),
	.q0(unnamed_1_74f164_i66_q0),
	.q1(unnamed_1_74f164_i66_q1),
	.q2(unnamed_1_74f164_i66_q2),
	.q3(unnamed_1_74f164_i66_q3),
	.q4(unnamed_1_74f164_i66_q4),
	.q5(unnamed_1_74f164_i66_q5),
	.q6(unnamed_1_74f164_i66_q6),
	.q7(unnamed_1_74f164_i66_q7),
	.q(/* unconnected */));

  caen_buffer page1_i67  (.ctrl(unnamed_1_caenbuffer_i67_ctrl),
	.in(unnamed_1_prma1c05b_i13_in),
	.out(caen_out[1]),
	.out_att(scope_out[1]));

  caen_buffer page1_i68  (.ctrl(unnamed_1_caenbuffer_i68_ctrl),
	.in(unnamed_1_prma1c05b_i10_in),
	.out(caen_out[2]),
	.out_att(scope_out[2]));

  caen_buffer page1_i69  (.ctrl(unnamed_1_caenbuffer_i69_ctrl),
	.in(unnamed_1_prma1c05b_i14_in),
	.out(caen_out[3]),
	.out_att(scope_out[3]));

  caen_buffer page1_i70  (.ctrl(unnamed_1_caenbuffer_i70_ctrl),
	.in(an_pulse_in[8]),
	.out(caen_out[4]),
	.out_att(scope_out[4]));

  caen_buffer page1_i71  (.ctrl(unnamed_1_caenbuffer_i71_ctrl),
	.in(an_pulse_in[9]),
	.out(caen_out[5]),
	.out_att(scope_out[5]));

  caen_buffer page1_i72  (.ctrl(unnamed_1_caenbuffer_i72_ctrl),
	.in(an_pulse_in[10]),
	.out(caen_out[6]),
	.out_att(scope_out[6]));

  caen_buffer page1_i73  (.ctrl(unnamed_1_caenbuffer_i73_ctrl),
	.in(an_pulse_in[11]),
	.out(caen_out[7]),
	.out_att(scope_out[7]));

  hct374 page1_i74  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i66_q0),
	.q(unnamed_1_caenbuffer_i64_ctrl));

  hct374 page1_i75  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i66_q2),
	.q(unnamed_1_caenbuffer_i68_ctrl));

  hct374 page1_i76  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i66_q3),
	.q(unnamed_1_caenbuffer_i69_ctrl));

  hct374 page1_i77  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i66_q4),
	.q(unnamed_1_caenbuffer_i70_ctrl));

  hct374 page1_i78  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i66_q5),
	.q(unnamed_1_caenbuffer_i71_ctrl));

  hct374 page1_i79  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i66_q6),
	.q(unnamed_1_caenbuffer_i72_ctrl));

  hct374 page1_i80  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i66_q7),
	.q(unnamed_1_caenbuffer_i73_ctrl));

  hct374 page1_i81  (.clk(data_rdy),
	.\clr* (glbl.vcc),
	.d(unnamed_1_74f164_i66_q1),
	.q(unnamed_1_caenbuffer_i67_ctrl));

  led_l page1_i82  (.a(unnamed_1_ledl_i82_a),
	.b(glbl.gnd));

  led_l page1_i83  (.a(unnamed_1_ledl_i83_a),
	.b(glbl.gnd));

  led_l page1_i84  (.a(unnamed_1_ledl_i84_a),
	.b(glbl.gnd));

  led_l page1_i85  (.a(unnamed_1_ledl_i85_a),
	.b(glbl.gnd));

  rsmd0805 page1_i86  (.a(unnamed_1_f07_i33_a),
	.b(unnamed_1_ledl_i82_a));

  rsmd0805 page1_i88  (.a(unnamed_1_f07_i36_a),
	.b(unnamed_1_ledl_i84_a));

  rsmd0805 page1_i89  (.a(unnamed_1_f07_i37_a),
	.b(unnamed_1_ledl_i85_a));

  rsmd0805 page1_i90  (.a(unnamed_1_f07_i35_a),
	.b(unnamed_1_ledl_i83_a));

  testpoint_l page1_i91  (.a(unnamed_1_74f164_i66_q2));

  testpoint_l page1_i92  (.a(unnamed_1_74f164_i66_q3));

  testpoint_l page1_i93  (.a(unnamed_1_74f164_i66_q4));

  testpoint_l page1_i94  (.a(unnamed_1_74f164_i66_q5));

  testpoint_l page1_i95  (.a(unnamed_1_74f164_i66_q6));

  testpoint_l page1_i96  (.a(unnamed_1_74f164_i66_q7));

  testpoint_l page1_i97  (.a(unnamed_1_74f164_i66_q1));

  testpoint_l page1_i98  (.a(unnamed_1_74f164_i66_q0));

  csmd0603 page1_i99  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  csmd0603 page1_i100  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  csmd0603 page1_i101  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  csmd0603 page1_i102  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  csmd0603 page1_i103  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  rsmd0805 page1_i104  (.a(unnamed_1_f07_i33_y),
	.b(unnamed_1_prma1c05b_i9_ctrlin));

  rsmd0805 page1_i105  (.a(unnamed_1_f07_i35_y),
	.b(unnamed_1_prma1c05b_i13_ctrlin));

  rsmd0805 page1_i106  (.a(unnamed_1_f07_i36_y),
	.b(unnamed_1_prma1c05b_i10_ctrlin));

  rsmd0805 page1_i107  (.a(unnamed_1_f07_i37_y),
	.b(unnamed_1_prma1c05b_i14_ctrlin));

endmodule // caen_coms(sch_1) 
