// generated by newgenasym  Wed Oct 01 11:41:46 2014


module ad96685 (inn, inp, ltch, qn, qp);
    input inn;
    input inp;
    output ltch;
    output qn;
    output qp;


    initial
        begin
        end

endmodule
