-- generated by newgenasym Wed Oct 01 11:41:46 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad96685 is
    port (    
	INN:       IN     STD_LOGIC;    
	INP:       IN     STD_LOGIC;    
	LTCH:      OUT    STD_LOGIC;    
	QN:        OUT    STD_LOGIC;    
	QP:        OUT    STD_LOGIC);
end ad96685;
