// generated by newgenasym  Tue Mar 29 11:58:22 2011


module mic29201 (error, ground, \input , \output , shutdown);
    input error;
    inout ground;
    inout \input ;
    output \output ;
    inout shutdown;


    initial
        begin
        end

endmodule
