-- generated by newgenasym Tue Mar 29 11:58:22 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MIC29201 is
    port (    
	ERROR:     IN     STD_LOGIC;    
	GROUND:    INOUT  STD_LOGIC;    
	INPUT:     INOUT  STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC;    
	SHUTDOWN:  INOUT  STD_LOGIC);
end MIC29201;
