`timescale 1ns/1ns

module caen (an_pulse_in, caen_out, clk, data, data_rdy, gtrigh_ecl, gtrigl_ecl, le, scope_out, sync24h_ecl, 
    sync24h_lvds, sync24l_ecl, sync24l_lvds, synch_ecl, synch_lvds, syncl_ecl, syncl_lvds );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:19 2015
// from tubii_lib/CAEN/sch_1

  inout [11:0] an_pulse_in;
  inout [7:0] caen_out;
  inout  clk;
  inout  data;
  inout  data_rdy;
  inout  gtrigh_ecl;
  inout  gtrigl_ecl;
  inout  le;
  inout [7:0] scope_out;
  inout  sync24h_ecl;
  inout  sync24h_lvds;
  inout  sync24l_ecl;
  inout  sync24l_lvds;
  inout  synch_ecl;
  inout  synch_lvds;
  inout  syncl_ecl;
  inout  syncl_lvds;

// begin instances 

  caen_chat page1_i1  (.gtrigh_ecl(gtrigh_ecl),
	.gtrigl_ecl(gtrigl_ecl),
	.sync24h_ecl(sync24h_ecl),
	.sync24h_lvds(sync24h_lvds),
	.sync24l_ecl(sync24l_ecl),
	.sync24l_lvds(sync24l_lvds),
	.synch_ecl(synch_ecl),
	.synch_lvds(synch_lvds),
	.syncl_ecl(syncl_ecl),
	.syncl_lvds(syncl_lvds));

  caen_coms page1_i3  (.an_pulse_in(an_pulse_in[11:0]),
	.caen_out(caen_out[7:0]),
	.clk(clk),
	.data(data),
	.data_rdy(data_rdy),
	.le(le),
	.scope_out(scope_out[7:0]));

endmodule // caen(sch_1) 
