// generated by newgenasym  Tue Mar 29 11:58:43 2011


module seq96t (adc_done, cclk, m2, \program* , \pwrdwn* , \rdata* , \reset* ,
        rtrig, sdin, sdout, sparein, spareout, \sqadc_busy* ,
        sqcadd_enable, sqchip_sel_en, \sqchold* , sqclk,
        \sqconvert_start* , sqcreg_req, sqcreg_sel, sqd, sqdav,
        sqdav32or, \sqenw- , sqfecbusy, sqlatch, \sqmemory_ack* ,
        \sqmemory_request* , \sqrd_strobe* , sqtag, \sqxreg_rd* ,
        sqxreg_sel, \sqxreg_wr* );
    output adc_done;
    input cclk;
    output m2;
    input \program* ;
    input \pwrdwn* ;
    output \rdata* ;
    input \reset* ;
    input rtrig;
    input sdin;
    output sdout;
    input [2:0] sparein;
    output [2:0] spareout;
    input \sqadc_busy* ;
    output sqcadd_enable;
    output sqchip_sel_en;
    output \sqchold* ;
    input sqclk;
    output \sqconvert_start* ;
    input sqcreg_req;
    output sqcreg_sel;
    inout [31:0] sqd;
    input [32:1] sqdav;
    output sqdav32or;
    output [3:1] \sqenw- ;
    output sqfecbusy;
    output [4:1] sqlatch;
    input \sqmemory_ack* ;
    output \sqmemory_request* ;
    output \sqrd_strobe* ;
    output [4:0] sqtag;
    input \sqxreg_rd* ;
    input [2:0] sqxreg_sel;
    input \sqxreg_wr* ;


    initial
        begin
        end

endmodule
