-- generated by newgenasym Tue Mar 29 11:58:15 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX907 is
    port (    
	INAM:      IN     STD_LOGIC;    
	INAP:      IN     STD_LOGIC;    
	INBM:      IN     STD_LOGIC;    
	INBP:      IN     STD_LOGIC;    
	OUTA:      OUT    STD_LOGIC;    
	OUTB:      OUT    STD_LOGIC;    
	VM:        IN     STD_LOGIC;    
	VP:        IN     STD_LOGIC);
end MAX907;
