-- generated by newgenasym Tue Mar 29 11:59:04 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TK11630 is
    port (    
	COM:       IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      IN     STD_LOGIC);
end TK11630;
