// generated by newgenasym  Tue Mar 29 11:58:45 2011


module sequencer32 (\badc_convert* , bcad_en, bchip_sel_en, \bchold* , bclk,
        bclka, bconv_done, bcreg_req, bcregsel, bdavail, bfecbusy,
        blatch, \bmemack2* , \bmemreq2* , bn_enw, brd_strobe,
        bseq_reset, btag, bxdt, \bxreg_rd* , bxreg_sel, \bxreg_wr* ,
        cclk, m2, p1, p104, p106, p107, p114, p115, p118, p119, p120,
        p125, p131, p132, p133, p138, p143, p144, p151, p154, p2, p21,
        p3, p37, p38, p39, p44, p50, p51, p6, p7, p70, p71, p74, p75, p76,
        p81, p82, p83, p85, p94, p95, \program* , \pwrdwn* , \rdata* ,
        \reset* , rtrig, sdin, sdout);
    output \badc_convert* ;
    output bcad_en;
    output bchip_sel_en;
    output \bchold* ;
    input bclk;
    input bclka;
    output bconv_done;
    input bcreg_req;
    output bcregsel;
    inout [32:1] bdavail;
    output bfecbusy;
    output [4:1] blatch;
    input \bmemack2* ;
    output \bmemreq2* ;
    output [3:1] bn_enw;
    output brd_strobe;
    input bseq_reset;
    output [4:0] btag;
    inout [31:0] bxdt;
    input \bxreg_rd* ;
    input [2:0] bxreg_sel;
    input \bxreg_wr* ;
    input cclk;
    output m2;
    inout p1;
    inout p104;
    inout p106;
    inout p107;
    inout p114;
    inout p115;
    inout p118;
    inout p119;
    inout p120;
    inout p125;
    inout p131;
    inout p132;
    inout p133;
    inout p138;
    inout p143;
    inout p144;
    inout p151;
    inout p154;
    inout p2;
    inout p21;
    inout p3;
    inout p37;
    inout p38;
    inout p39;
    inout p44;
    inout p50;
    inout p51;
    inout p6;
    inout p7;
    inout p70;
    inout p71;
    inout p74;
    inout p75;
    inout p76;
    inout p81;
    inout p82;
    inout p83;
    inout p85;
    inout p94;
    inout p95;
    input \program* ;
    input \pwrdwn* ;
    output \rdata* ;
    input \reset* ;
    input rtrig;
    input sdin;
    output sdout;


    initial
        begin
        end

endmodule
