`timescale 1ns/1ns

module trigger_utility_board_mkii (async_delay_in, async_delay_out, async_pulse_out, caen_anpulse, caen_out, clock100_outh, 
    clock100_outl, clock200_outh, clock200_outl, dgth, dgtl, exttrig, ext_ped_in, ext_ped_out, fast_anpulse, 
    fast_comp_outh, fast_comp_outl, gtrigh_ecl, gtrigl_ecl, gtrig_ttl, lockout, \lockout* , \mtcd_lo* , 
    rawtrigs, scope_out, smellie_delay_in, smellie_delay_out, smellie_pulse_out, sync24h_ecl, 
    sync24h_lvds, sync24l_ecl, sync24l_lvds, sync24_ttl, synch_ecl, synch_lvds, syncl_ecl, syncl_lvds, 
    sync_delay_in, sync_delay_out, sync_pulse_out, sync_ttl, tellie_delay_in, tellie_delay_out, 
    tellie_pulse_out, tubii_rt_out, tub_clk_in, tune_anpulse, tune_comp_outh, tune_comp_outl 
    );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:25 2015
// from tubii_lib/TRIGGER_UTILITY_BOARD_MKII/sch_1

  inout  async_delay_in;
  inout  async_delay_out;
  inout  async_pulse_out;
  inout [11:0] caen_anpulse;
  inout [7:0] caen_out;
  inout  clock100_outh;
  inout  clock100_outl;
  inout  clock200_outh;
  inout  clock200_outl;
  inout  dgth;
  inout  dgtl;
  inout [15:0] exttrig;
  inout  ext_ped_in;
  inout  ext_ped_out;
  inout  fast_anpulse;
  inout  fast_comp_outh;
  inout  fast_comp_outl;
  inout  gtrigh_ecl;
  inout  gtrigl_ecl;
  inout  gtrig_ttl;
  inout  lockout;
  inout  \lockout* ;
  inout  \mtcd_lo* ;
  inout [3:0] rawtrigs;
  inout [7:0] scope_out;
  inout  smellie_delay_in;
  inout  smellie_delay_out;
  inout  smellie_pulse_out;
  inout  sync24h_ecl;
  inout  sync24h_lvds;
  inout  sync24l_ecl;
  inout  sync24l_lvds;
  inout  sync24_ttl;
  inout  synch_ecl;
  inout  synch_lvds;
  inout  syncl_ecl;
  inout  syncl_lvds;
  inout  sync_delay_in;
  inout  sync_delay_out;
  inout  sync_pulse_out;
  inout  sync_ttl;
  inout  tellie_delay_in;
  inout  tellie_delay_out;
  inout  tellie_pulse_out;
  inout  tubii_rt_out;
  inout  tub_clk_in;
  inout  tune_anpulse;
  inout  tune_comp_outh;
  inout  tune_comp_outl;
  // global signal glbl.gnd;
  // global signal glbl.vcc;

  wire [0:2] addr;
  wire [0:2] scaler;
  wire  unnamed_1_3merge_i6_a;
  wire  unnamed_1_3merge_i6_b;
  wire  unnamed_1_3merge_i6_c;
  wire  unnamed_1_3merge_i8_a;
  wire  unnamed_1_3merge_i8_b;
  wire  unnamed_1_3merge_i8_c;
  wire  unnamed_1_caen_i3_clk;
  wire  unnamed_1_caen_i3_data;
  wire  unnamed_1_caen_i3_datardy;
  wire  unnamed_1_caen_i3_le;
  wire  unnamed_1_clocks_i15_clock100;
  wire  unnamed_1_clocks_i15_datardy;
  wire  unnamed_1_clocks_i15_defaultselect;
  wire  unnamed_1_clocks_i15_fox200mhz;
  wire  unnamed_1_clocks_i15_le;
  wire  unnamed_1_clocks_i15_missedclock;
  wire  unnamed_1_cntrlregister_i2_dataout;
  wire  unnamed_1_cntrlregister_i2_datardy;
  wire  unnamed_1_cntrlregister_i2_ecalsetup;
  wire  unnamed_1_cntrlregister_i2_le;
  wire  unnamed_1_cntrlregister_i2_loselect;
  wire  unnamed_1_cntrlregister_i2_readenable;
  wire  unnamed_1_comparators_i13_datardy;
  wire  unnamed_1_comparators_i13_letune;
  wire  unnamed_1_genericutilities_i11_asyncdelayin;
  wire  unnamed_1_genericutilities_i11_asyncpulsein;
  wire  unnamed_1_genericutilities_i11_clrcnt;
  wire  unnamed_1_genericutilities_i11_latchdisplay;
  wire  unnamed_1_genericutilities_i11_leasyncdelay;
  wire  unnamed_1_genericutilities_i11_leasyncpulse;
  wire  unnamed_1_genericutilities_i11_pulse;
  wire  unnamed_1_gtdelays_i4_dgtttl;
  wire  unnamed_1_gtdelays_i4_ledgt;
  wire  unnamed_1_gtdelays_i4_ttllockout;
  wire  unnamed_1_microzedconnection_i10_spkr;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign unnamed_1_3merge_i6_a = addr[0:0];
  assign unnamed_1_3merge_i6_b = addr[1:1];
  assign unnamed_1_3merge_i6_c = addr[2:2];
  assign unnamed_1_3merge_i8_a = scaler[0:0];
  assign unnamed_1_3merge_i8_b = scaler[1:1];
  assign unnamed_1_3merge_i8_c = scaler[2:2];

// begin instances 

  base_mon page1_i1  ();

  cntrl_register page1_i2  (.clk(unnamed_1_caen_i3_clk),
	.data(unnamed_1_caen_i3_data),
	.data_out(unnamed_1_cntrlregister_i2_dataout),
	.data_rdy(unnamed_1_cntrlregister_i2_datardy),
	.default_clk_select(unnamed_1_clocks_i15_defaultselect),
	.display(scaler[0:2]),
	.ecal_setup(unnamed_1_cntrlregister_i2_ecalsetup),
	.le(unnamed_1_cntrlregister_i2_le),
	.lo_select(unnamed_1_cntrlregister_i2_loselect),
	.read_enable(unnamed_1_cntrlregister_i2_readenable));

  caen page1_i3  (.an_pulse_in(caen_anpulse[11:0]),
	.caen_out(caen_out[7:0]),
	.clk(unnamed_1_caen_i3_clk),
	.data(unnamed_1_caen_i3_data),
	.data_rdy(unnamed_1_caen_i3_datardy),
	.gtrigh_ecl(gtrigh_ecl),
	.gtrigl_ecl(gtrigl_ecl),
	.le(unnamed_1_caen_i3_le),
	.scope_out(scope_out[7:0]),
	.sync24h_ecl(sync24h_ecl),
	.sync24h_lvds(sync24h_lvds),
	.sync24l_ecl(sync24l_ecl),
	.sync24l_lvds(sync24l_lvds),
	.synch_ecl(synch_ecl),
	.synch_lvds(synch_lvds),
	.syncl_ecl(syncl_ecl),
	.syncl_lvds(syncl_lvds));

  gt_delays page1_i4  (.clk(unnamed_1_caen_i3_clk),
	.data(unnamed_1_caen_i3_data),
	.dgth(dgth),
	.dgtl(dgtl),
	.dgt_ttl(unnamed_1_gtdelays_i4_dgtttl),
	.gtrigh(gtrigh_ecl),
	.gtrigl(gtrigl_ecl),
	.le_dgt(unnamed_1_gtdelays_i4_ledgt),
	.lockout(lockout),
	.\lockout* (\lockout* ),
	.\mtcd_lo* (\mtcd_lo* ),
	.select_lo_src(unnamed_1_cntrlregister_i2_loselect),
	.\ttl_lockout* (unnamed_1_gtdelays_i4_ttllockout));

  hct238 page1_i5  (.a0(unnamed_1_3merge_i6_a),
	.a1(unnamed_1_3merge_i6_b),
	.a2(unnamed_1_3merge_i6_c),
	.e1(glbl.gnd),
	.e2(glbl.gnd),
	.e3(glbl.vcc),
	.y0(unnamed_1_caen_i3_le),
	.y1(unnamed_1_gtdelays_i4_ledgt),
	.y2(unnamed_1_cntrlregister_i2_le),
	.y3(unnamed_1_cntrlregister_i2_readenable),
	.y4(unnamed_1_comparators_i13_letune),
	.y5(unnamed_1_clocks_i15_le),
	.y6(unnamed_1_genericutilities_i11_leasyncdelay),
	.y7(unnamed_1_genericutilities_i11_leasyncpulse));

  ecal_control page1_i7  (.ecal_active(unnamed_1_cntrlregister_i2_ecalsetup),
	.ext_ped_in(ext_ped_in),
	.ext_ped_out(ext_ped_out),
	.gtrig(gtrigh_ecl));

  tubii_spkr page1_i9  (.spkr_signal(unnamed_1_microzedconnection_i10_spkr));

  microzedconnection page1_i10  (.\100mhz_clk_in (unnamed_1_clocks_i15_clock100),
	.async_delay_in(async_delay_in),
	.async_delay_out(unnamed_1_genericutilities_i11_asyncdelayin),
	.async_pulse_out(unnamed_1_genericutilities_i11_asyncpulsein),
	.caen_rdy(unnamed_1_caen_i3_datardy),
	.clk(unnamed_1_caen_i3_clk),
	.clr_cnt(unnamed_1_genericutilities_i11_clrcnt),
	.cntrl_rdy(unnamed_1_cntrlregister_i2_datardy),
	.cntrl_register_chk(unnamed_1_cntrlregister_i2_dataout),
	.cnt_pulse(unnamed_1_genericutilities_i11_pulse),
	.comp_rdy(unnamed_1_comparators_i13_datardy),
	.data(unnamed_1_caen_i3_data),
	.dgt(unnamed_1_gtdelays_i4_dgtttl),
	.exttrig(exttrig[15:0]),
	.fox_200mhz_in(unnamed_1_clocks_i15_fox200mhz),
	.gtrig(gtrig_ttl),
	.latch_display(unnamed_1_genericutilities_i11_latchdisplay),
	.load_enable(addr[0:2]),
	.\lockout* (unnamed_1_gtdelays_i4_ttllockout),
	.rawtrigs_in(rawtrigs[3:0]),
	.smellie_delay_in(smellie_delay_in),
	.smellie_delay_out(smellie_delay_out),
	.smellie_pulse_out(smellie_pulse_out),
	.spkr(unnamed_1_microzedconnection_i10_spkr),
	.sync(sync_ttl),
	.sync24(sync24_ttl),
	.sync_delay_in(sync_delay_in),
	.sync_delay_out(sync_delay_out),
	.sync_pulse_out(sync_pulse_out),
	.tellie_delay_in(tellie_delay_in),
	.tellie_delay_out(tellie_delay_out),
	.tellie_pulse_out(tellie_pulse_out),
	.tubiitime_data_rdy(unnamed_1_clocks_i15_datardy),
	.tubii_rt_out(tubii_rt_out),
	.using_bckp(unnamed_1_clocks_i15_missedclock));

  generic_utilities page1_i11  (.allow_count(unnamed_1_3merge_i8_a),
	.async_delay_in(unnamed_1_genericutilities_i11_asyncdelayin),
	.async_delay_out(async_delay_out),
	.async_pulse_in(unnamed_1_genericutilities_i11_asyncpulsein),
	.async_pulse_out(async_pulse_out),
	.clk(unnamed_1_caen_i3_clk),
	.clr_cnt(unnamed_1_genericutilities_i11_clrcnt),
	.data(unnamed_1_caen_i3_data),
	.display_zeroes(unnamed_1_3merge_i8_c),
	.latch_display(unnamed_1_genericutilities_i11_latchdisplay),
	.le_async_delay(unnamed_1_genericutilities_i11_leasyncdelay),
	.le_async_pulse(unnamed_1_genericutilities_i11_leasyncpulse),
	.pulse(unnamed_1_genericutilities_i11_pulse),
	.test_display(unnamed_1_3merge_i8_b));

  comparators page1_i13  (.clk(unnamed_1_caen_i3_clk),
	.data(unnamed_1_caen_i3_data),
	.data_rdy(unnamed_1_comparators_i13_datardy),
	.dgth(dgth),
	.fast_comp_outh(fast_comp_outh),
	.fast_comp_outl(fast_comp_outl),
	.fast_pulse(fast_anpulse),
	.gtrig(gtrigh_ecl),
	.le_tune(unnamed_1_comparators_i13_letune),
	.\lockout* (\lockout* ),
	.tune_comp_outh(tune_comp_outl),
	.tune_comp_outl(tune_comp_outh),
	.tune_pulse(tune_anpulse));

  powers page1_i14  (.power(/* unconnected */));

  clocks page1_i15  (.clk100_outh(clock100_outh),
	.clk100_outl(clock100_outl),
	.clock100(unnamed_1_clocks_i15_clock100),
	.clock200_outh(clock200_outh),
	.clock200_outl(clock200_outl),
	.data(unnamed_1_caen_i3_data),
	.data_rdy(unnamed_1_clocks_i15_datardy),
	.default_select(unnamed_1_clocks_i15_defaultselect),
	.fox200mhz(unnamed_1_clocks_i15_fox200mhz),
	.le(unnamed_1_clocks_i15_le),
	.missedclock(unnamed_1_clocks_i15_missedclock),
	.sr_clk(unnamed_1_caen_i3_clk),
	.tub_clk_in(tub_clk_in));

endmodule // trigger_utility_board_mkii(sch_1) 
