-- generated by newgenasym Tue Mar 29 11:59:34 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10el34\ is
    port (    
	CLK:       IN     STD_LOGIC;    
	\clk*\:    IN     STD_LOGIC;    
	\en*\:     IN     STD_LOGIC;    
	MR:        IN     STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	\q0*\:     OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	\q1*\:     OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	\q2*\:     OUT    STD_LOGIC;    
	VBB:       OUT    STD_LOGIC);
end \10el34\;
