// generated by newgenasym  Mon Apr 04 12:55:34 2011


module ids_c10 (pin1, pin10, pin2, pin3, pin4, pin5, pin6, pin7, pin8, pin9);
    inout pin1;
    inout pin10;
    inout pin2;
    inout pin3;
    inout pin4;
    inout pin5;
    inout pin6;
    inout pin7;
    inout pin8;
    inout pin9;


    initial
        begin
        end

endmodule
