-- generated by newgenasym Tue Mar 29 11:56:14 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \2n3904sz\ is
    generic (
        size:positive:= 1
            );
    port (    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	C:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	E:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \2n3904sz\;
