// generated by newgenasym  Tue Mar 29 12:00:42 2011


module simfifo4 (badd_out, bd, bxreg_add, bxreg_rd, bxreg_wr, fifo_reset,
        \globalreset* , \mem_read* , \mem_write* , \read_add_sel* ,
        read_enable, \write_add_sel* , write_enable);
    inout [19:0] badd_out;
    inout [19:0] bd;
    input [1:0] bxreg_add;
    input bxreg_rd;
    input bxreg_wr;
    input fifo_reset;
    input \globalreset* ;
    input \mem_read* ;
    input \mem_write* ;
    input \read_add_sel* ;
    output read_enable;
    input \write_add_sel* ;
    output write_enable;


    initial
        begin
        end

endmodule
