-- generated by newgenasym Tue Mar 29 12:00:42 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SIMFIFO4 is
    port (    
	BADD_OUT:  INOUT  STD_LOGIC_VECTOR (19 DOWNTO 0);    
	BD:        INOUT  STD_LOGIC_VECTOR (19 DOWNTO 0);    
	BXREG_ADD: IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	BXREG_RD:  IN     STD_LOGIC;    
	BXREG_WR:  IN     STD_LOGIC;    
	FIFO_RESET: IN     STD_LOGIC;    
	\globalreset*\: IN     STD_LOGIC;    
	\mem_read*\: IN     STD_LOGIC;    
	\mem_write*\: IN     STD_LOGIC;    
	\read_add_sel*\: IN     STD_LOGIC;    
	READ_ENABLE: OUT    STD_LOGIC;    
	\write_add_sel*\: IN     STD_LOGIC;    
	WRITE_ENABLE: OUT    STD_LOGIC);
end SIMFIFO4;
