`timescale 1ns/1ns

module ports2 (clock100_outh, clock100_outl, clock200_outh, clock200_outl, exttrig, rawtrigs, smellie_delay_in, 
    smellie_delay_out, smellie_pulse_out, tellie_delay_in, tellie_delay_out, tellie_pulse_out, 
    tubii_rt, tub_clk_in );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:12 2015
// from tubii_lib/PORTS2/sch_1

  inout  clock100_outh;
  inout  clock100_outl;
  inout  clock200_outh;
  inout  clock200_outl;
  inout [15:0] exttrig;
  inout [3:0] rawtrigs;
  inout  smellie_delay_in;
  inout  smellie_delay_out;
  inout  smellie_pulse_out;
  inout  tellie_delay_in;
  inout  tellie_delay_out;
  inout  tellie_pulse_out;
  inout  tubii_rt;
  inout  tub_clk_in;
  // global signal glbl.gnd;
  // global signal glbl.vtt;

  wire  unnamed_1_10e101_i2_a;
  wire  unnamed_1_10e101_i2_d;
  wire  unnamed_1_10e101_i2_y;
  wire  unnamed_1_10h116_i27_a;
  wire  unnamed_1_10h116_i27_b;
  wire  unnamed_1_10h116_i28_a;
  wire  unnamed_1_10h116_i28_b;

  wire  gnd;
  wire  page1_gnd;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  testpoint_l page1_i1  (.a(unnamed_1_10e101_i2_y));

  \10e101  page1_i2  (.a(unnamed_1_10e101_i2_a),
	.b(/* unconnected */),
	.c(/* unconnected */),
	.d(unnamed_1_10e101_i2_d),
	.y(tub_clk_in),
	.\y* (unnamed_1_10e101_i2_y));
  defparam page1_i2.size = 1;

  rsmd0805 page1_i3  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i2_y));

  rsmd0805 page1_i4  (.a({glbl.vtt}),
	.b(tub_clk_in));

  rsmd0805 page1_i5  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i2_a));

  rsmd0805 page1_i6  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i2_d));

  csmd0805 page1_i9  (.a({glbl.gnd}),
	.b(unnamed_1_10h116_i27_b));

  rsmd0805 page1_i11  (.a({glbl.vtt}),
	.b(unnamed_1_10h116_i27_a));

  rsmd0805 page1_i12  (.a({glbl.vtt}),
	.b(unnamed_1_10h116_i28_a));

  rsmd0805 page1_i13  (.a({glbl.vtt}),
	.b(unnamed_1_10h116_i28_b));

  testpoint_l page1_i14  (.a(unnamed_1_10h116_i27_a));

  testpoint_l page1_i15  (.a(glbl.gnd));

  testpoint_l page1_i16  (.a(unnamed_1_10h116_i28_a));

  testpoint_l page1_i17  (.a(unnamed_1_10h116_i28_b));

  testpoint_l page1_i18  (.a(clock200_outh));

  testpoint_l page1_i19  (.a(clock200_outl));

  latchexttrig page1_i20  (.exttrig(exttrig[15:0]));

  tubii_triggers page1_i21  (.rawtrigs(rawtrigs[3:0]),
	.tubii_rt(tubii_rt));

  ellie page1_i22  (.smellie_delay_in(smellie_delay_in),
	.smellie_delay_out(smellie_delay_out),
	.smellie_pulse_out(smellie_pulse_out),
	.tellie_delay_in(tellie_delay_in),
	.tellie_delay_out(tellie_delay_out),
	.tellie_pulse_out(tellie_pulse_out));

  testpoint_l page1_i23  (.a(glbl.gnd));

  testpoint_l page1_i25  (.a(clock100_outh));

  testpoint_l page1_i26  (.a(clock100_outl));

  \10h116  page1_i27  (.a(unnamed_1_10h116_i27_a),
	.\b* (unnamed_1_10h116_i27_b),
	.v(unnamed_1_10h116_i27_b),
	.y(unnamed_1_10e101_i2_a),
	.\y* (/* unconnected */));
  defparam page1_i27.section = 1;
  defparam page1_i27.size = 1;

  \10h116  page1_i28  (.a(unnamed_1_10h116_i28_a),
	.\b* (unnamed_1_10h116_i28_b),
	.v(/* unconnected */),
	.y(unnamed_1_10e101_i2_d),
	.\y* (/* unconnected */));
  defparam page1_i28.section = 1;
  defparam page1_i28.size = 1;

endmodule // ports2(sch_1) 
