// generated by newgenasym  Fri Feb 20 13:36:47 2015


module nim_ecl_translation (ecl_in, ecl_out, nim_in, nim_out);
    input ecl_in;
    output ecl_out;
    input nim_in;
    output nim_out;


    initial
        begin
        end

endmodule
