-- generated by newgenasym Fri Feb 20 13:36:47 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity nim_ecl_translation is
    port (    
	ECL_IN:    IN     STD_LOGIC;    
	ECL_OUT:   OUT    STD_LOGIC;    
	NIM_IN:    IN     STD_LOGIC;    
	NIM_OUT:   OUT    STD_LOGIC);
end nim_ecl_translation;
