// generated by newgenasym  Tue Mar 29 12:00:11 2011


module \10h600  (d, enecl, enttl, q);
    parameter    size = 1;
    input [size-1:0] d;
    input enecl;
    input enttl;
    output [size-1:0] q;


    initial
        begin
        end

endmodule
