// generated by newgenasym  Tue Mar 29 11:58:09 2011


module max506 (a0, a1, agnd, d0, d1, d2, d3, d4, d5, d6, d7, dgnd, vdd, vouta,
        voutb, voutc, voutd, vref, vss, \wr* );
    input a0;
    input a1;
    input agnd;
    input d0;
    input d1;
    input d2;
    input d3;
    input d4;
    input d5;
    input d6;
    input d7;
    input dgnd;
    input vdd;
    output vouta;
    output voutb;
    output voutc;
    output voutd;
    input vref;
    input vss;
    input \wr* ;


    initial
        begin
        end

endmodule
