-- generated by newgenasym Tue Mar 29 11:58:09 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX506 is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	AGND:      IN     STD_LOGIC;    
	D0:        IN     STD_LOGIC;    
	D1:        IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	D5:        IN     STD_LOGIC;    
	D6:        IN     STD_LOGIC;    
	D7:        IN     STD_LOGIC;    
	DGND:      IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VOUTA:     OUT    STD_LOGIC;    
	VOUTB:     OUT    STD_LOGIC;    
	VOUTC:     OUT    STD_LOGIC;    
	VOUTD:     OUT    STD_LOGIC;    
	VREF:      IN     STD_LOGIC;    
	VSS:       IN     STD_LOGIC;    
	\wr*\:     IN     STD_LOGIC);
end MAX506;
