-- generated by newgenasym Thu Aug 21 17:34:31 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_select is
    port (    
	LE:        IN     STD_LOGIC;    
	SEL:       IN     STD_LOGIC_VECTOR (0 TO 39));
end caen_select;
