// generated by newgenasym  Fri Oct 03 12:34:15 2014


module generic_utilities (allow_count, async_delay_in, async_delay_out,
        async_pulse_in, async_pulse_out, clk, clr_cnt, data,
        display_zeroes, latch_display, le_async_delay,
        le_async_pulse, pulse, test_display);
    output allow_count;
    input async_delay_in;
    output async_delay_out;
    input async_pulse_in;
    input async_pulse_out;
    input clk;
    output clr_cnt;
    input data;
    output display_zeroes;
    output latch_display;
    input le_async_delay;
    input le_async_pulse;
    output pulse;
    output test_display;


    initial
        begin
        end

endmodule
