`timescale 1ns/1ns

module generic_utilities (allow_count, async_delay_in, async_delay_out, async_pulse_in, async_pulse_out, 
    clk, clr_cnt, data, display_zeroes, latch_display, le_async_delay, le_async_pulse, pulse, test_display 
    );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:24 2015
// from tubii_lib/GENERIC_UTILITIES/sch_1

  inout  allow_count;
  inout  async_delay_in;
  inout  async_delay_out;
  inout  async_pulse_in;
  inout  async_pulse_out;
  inout  clk;
  inout  clr_cnt;
  inout  data;
  inout  display_zeroes;
  inout  latch_display;
  inout  le_async_delay;
  inout  le_async_pulse;
  inout  pulse;
  inout  test_display;

// begin instances 

  generic_pulse page1_i1  (.async_pulse_in(async_pulse_in),
	.async_pulse_out(async_pulse_out),
	.clk(clk),
	.data(data),
	.le_async_pulse(le_async_pulse));

  generic_delays page1_i2  (.async_delay_in(async_delay_in),
	.async_delay_out(async_delay_out),
	.clk(clk),
	.data(data),
	.le(le_async_delay));

  pulse_inverter page1_i3  ();

  ribbondelay page1_i12  ();

  pulse_scaler page1_i13  (.allow_cnt(allow_count),
	.clr_cnt(clr_cnt),
	.latch_display(latch_display),
	.leading_zeroes(display_zeroes),
	.pulse(pulse),
	.test(test_display));

endmodule // generic_utilities(sch_1) 
