// generated by newgenasym  Tue Mar 29 11:58:52 2011


module snodisc1 (discrn1, discrn2, discrn3, discrn4, discrp1, discrp2,
        discrp3, discrp4, ina1, ina2, ina3, ina4, inb1, inb2, inb3,
        inb4, itwk, outqhi1, outqhi2, outqhi3, outqhi4, outqlo1,
        outqlo2, outqlo3, outqlo4, pedn, pedp, pen1, pen2, pen3, pen4,
        qhiref1, qhiref2, qhiref3, qhiref4, qloref1, qloref2,
        qloref3, qloref4, ramp1, ramp2, ramp3, ramp4, rmpc1, rmpc2,
        sampn1, sampn2, sampn3, sampn4, sampp1, sampp2, sampp3,
        sampp4, suba1, suba2, subd1, subd2, vli, vsi, vth1, vth2, vth3,
        vth4);
    output discrn1;
    output discrn2;
    output discrn3;
    output discrn4;
    output discrp1;
    output discrp2;
    output discrp3;
    input discrp4;
    input ina1;
    input ina2;
    input ina3;
    input ina4;
    input inb1;
    input inb2;
    input inb3;
    input inb4;
    input itwk;
    input outqhi1;
    input outqhi2;
    input outqhi3;
    input outqhi4;
    input outqlo1;
    input outqlo2;
    input outqlo3;
    input outqlo4;
    input pedn;
    input pedp;
    input pen1;
    input pen2;
    input pen3;
    input pen4;
    input qhiref1;
    input qhiref2;
    input qhiref3;
    input qhiref4;
    input qloref1;
    input qloref2;
    input qloref3;
    input qloref4;
    input ramp1;
    input ramp2;
    input ramp3;
    input ramp4;
    input rmpc1;
    input rmpc2;
    output sampn1;
    output sampn2;
    output sampn3;
    output sampn4;
    output sampp1;
    output sampp2;
    output sampp3;
    output sampp4;
    input suba1;
    input suba2;
    input subd1;
    input subd2;
    input vli;
    input vsi;
    input vth1;
    input vth2;
    input vth3;
    input vth4;


    initial
        begin
        end

endmodule
