// generated by newgenasym  Mon Jan 19 16:42:04 2015


module tuncomp (anpulsein, clk, data, data_rdy, dgt_gate, gtrig, le, \lo* ,
        posneg, trig_outh, trig_outl, vbb_comp);
    input anpulsein;
    input clk;
    input data;
    input data_rdy;
    inout dgt_gate;
    inout gtrig;
    input le;
    inout \lo* ;
    input posneg;
    output trig_outh;
    output trig_outl;
    input vbb_comp;


    initial
        begin
        end

endmodule
