// generated by newgenasym  Wed Jan 07 18:45:01 2015


module tuncomp (anpulsein, clk, data, data_rdy, dgt_gate, gtrig, le, \lo* ,
        posneg, trig_outh, trig_outl);
    input anpulsein;
    input clk;
    input data;
    input data_rdy;
    inout dgt_gate;
    inout gtrig;
    input le;
    inout \lo* ;
    input posneg;
    output trig_outh;
    output trig_outl;


    initial
        begin
        end

endmodule
