// generated by newgenasym  Wed Feb 25 10:33:26 2015


module tuncomp (anpulsein, clk, data, data_rdy, dgt_gate, gtrig, le, \lo* ,
        posneg, trig_out_n, trig_out_p, vbb_comp);
    input anpulsein;
    input clk;
    input data;
    input data_rdy;
    inout dgt_gate;
    inout gtrig;
    input le;
    inout \lo* ;
    input posneg;
    output trig_out_n;
    output trig_out_p;
    input vbb_comp;


    initial
        begin
        end

endmodule
