-- generated by newgenasym Mon Jan 19 16:42:04 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tuncomp is
    port (    
	ANPULSEIN: IN     STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	DGT_GATE:  INOUT  STD_LOGIC;    
	GTRIG:     INOUT  STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	\lo*\:     INOUT  STD_LOGIC;    
	POSNEG:    IN     STD_LOGIC;    
	TRIG_OUTH: OUT    STD_LOGIC;    
	TRIG_OUTL: OUT    STD_LOGIC;    
	VBB_COMP:  IN     STD_LOGIC);
end tuncomp;
