-- generated by newgenasym Fri Oct 17 15:15:11 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tuncomp is
    port (    
	ANPULSEIN: IN     STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	DATA_RDY:  IN     STD_LOGIC;    
	DGTH:      INOUT  STD_LOGIC;    
	GTRIG:     INOUT  STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	\lockout*\: INOUT  STD_LOGIC;    
	POSNEG:    IN     STD_LOGIC;    
	TRIG_OUTH: OUT    STD_LOGIC;    
	TRIG_OUTL: OUT    STD_LOGIC);
end tuncomp;
