`timescale 1ns/1ns

module tubii_clks (bckp_clk, clock200_outh, clock200_outl, default_clk, default_select, fox200mhz, tub_clk_in 
    );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:20 2015
// from tubii_lib/TUBII_CLKS/sch_1

  inout  bckp_clk;
  inout  clock200_outh;
  inout  clock200_outl;
  inout  default_clk;
  inout  default_select;
  inout  fox200mhz;
  inout  tub_clk_in;
  // global signal glbl.gnd;
  // global signal glbl.vcc;
  // global signal glbl.vp3_3;
  // global signal glbl.vtt;

  wire  unnamed_1_100el34_i36_clk;
  wire  unnamed_1_100el34_i36_clk_1;
  wire  unnamed_1_100el34_i36_out2;
  wire  unnamed_1_100el34_i36_out2_1;
  wire  unnamed_1_10h116_i62_a;
  wire  unnamed_1_10h116_i62_b;
  wire  unnamed_1_el91l_i2_in;
  wire  unnamed_1_el91l_i2_in_1;
  wire  unnamed_1_mc10h104_i64_b;
  wire  unnamed_1_mc10h104_i65_b;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;
  wire  vp3_3;
  wire  page1_vp3_3;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vp3_3 = glbl.vp3_3;
  assign page1_vp3_3 = vp3_3;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;

// begin instances 

  el91l page1_i2  (.in(unnamed_1_el91l_i2_in),
	.\in* (unnamed_1_el91l_i2_in_1),
	.out(unnamed_1_10h116_i62_a),
	.\out* (unnamed_1_10h116_i62_b),
	.vbb(/* unconnected */),
	.vbb2(/* unconnected */));

  rsmd0805 page1_i3  (.a(unnamed_1_el91l_i2_in_1),
	.b({glbl.vp3_3}));

  rsmd0805 page1_i4  (.a(unnamed_1_el91l_i2_in),
	.b({glbl.vp3_3}));

  foxclock page1_i5  (.ed(/* unconnected */),
	.nc(/* unconnected */),
	.out(unnamed_1_el91l_i2_in),
	.\out* (unnamed_1_el91l_i2_in_1));

  rsmd0805 page1_i6  (.a({glbl.gnd}),
	.b(unnamed_1_el91l_i2_in_1));

  rsmd0805 page1_i7  (.a({glbl.gnd}),
	.b(unnamed_1_el91l_i2_in));

  rsmd0805 page1_i13  (.a({glbl.vtt}),
	.b(unnamed_1_100el34_i36_clk));

  rsmd0805 page1_i14  (.a({glbl.vtt}),
	.b(unnamed_1_100el34_i36_clk_1));

  rsmd0805 page1_i15  (.a({glbl.vtt}),
	.b(unnamed_1_10h116_i62_a));

  rsmd0805 page1_i16  (.a({glbl.vtt}),
	.b(unnamed_1_10h116_i62_b));

  \10h125  page1_i34  (.a(unnamed_1_10h116_i62_a),
	.\b* (unnamed_1_10h116_i62_b),
	.v(/* unconnected */),
	.y(fox200mhz));
  defparam page1_i34.size = 1;

  \100el34  page1_i36  (.clk(unnamed_1_100el34_i36_clk),
	.\clk* (unnamed_1_100el34_i36_clk_1),
	.\en* (glbl.gnd),
	.mr(/* unconnected */),
	.nc(/* unconnected */),
	.out2(unnamed_1_100el34_i36_out2),
	.\out2* (unnamed_1_100el34_i36_out2_1),
	.out4(/* unconnected */),
	.\out4* (/* unconnected */),
	.out8(/* unconnected */),
	.\out8* (/* unconnected */),
	.vbb(/* unconnected */));

  testpoint_l page1_i43  (.a(unnamed_1_100el34_i36_out2_1));

  rsmd0805 page1_i49  (.a({glbl.vtt}),
	.b(unnamed_1_100el34_i36_out2));

  rsmd0805 page1_i50  (.a({glbl.vtt}),
	.b(unnamed_1_100el34_i36_out2_1));

  rsmd0805 page1_i51  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h104_i64_b));

  rsmd0805 page1_i52  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h104_i65_b));

  rsmd0805 page1_i53  (.a({glbl.vtt}),
	.b(default_clk));

  rsmd0805 page1_i54  (.a({glbl.vtt}),
	.b(bckp_clk));

  testpoint_l page1_i55  (.a(default_select));

  mc10h124 page1_i60  (.common(glbl.vcc),
	.in(default_select),
	.out(unnamed_1_mc10h104_i64_b),
	.\out* (unnamed_1_mc10h104_i65_b));

  \10h116  page1_i62  (.a(unnamed_1_10h116_i62_a),
	.\b* (unnamed_1_10h116_i62_b),
	.v(/* unconnected */),
	.y(clock200_outh),
	.\y* (clock200_outl));
  defparam page1_i62.section = 1;
  defparam page1_i62.size = 1;

  \10h116  page1_i63  (.a(unnamed_1_10h116_i62_a),
	.\b* (unnamed_1_10h116_i62_b),
	.v(/* unconnected */),
	.y(unnamed_1_100el34_i36_clk),
	.\y* (unnamed_1_100el34_i36_clk_1));
  defparam page1_i63.section = 1;
  defparam page1_i63.size = 1;

  mc10h104 page1_i64  (.a(unnamed_1_100el34_i36_out2),
	.b(unnamed_1_mc10h104_i64_b),
	.y(default_clk));

  mc10h104 page1_i65  (.a(tub_clk_in),
	.b(unnamed_1_mc10h104_i65_b),
	.y(default_clk));

  mc10h104 page1_i66  (.a(unnamed_1_100el34_i36_out2),
	.b(unnamed_1_mc10h104_i65_b),
	.y(bckp_clk));

  mc10h104 page1_i67  (.a(tub_clk_in),
	.b(unnamed_1_mc10h104_i64_b),
	.y(bckp_clk));

endmodule // tubii_clks(sch_1) 
