// generated by newgenasym  Fri Aug 22 17:43:40 2014


module load_caen_selection (clk, data, sel);
    input clk;
    input data;
    output [0:39] sel;


    initial
        begin
        end

endmodule
