-- generated by newgenasym Fri Aug 22 17:43:40 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity load_caen_selection is
    port (    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	SEL:       OUT    STD_LOGIC_VECTOR (0 TO 39));
end load_caen_selection;
