-- generated by newgenasym Tue Mar 29 11:57:55 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM35DM is
    port (    
	GND:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC;    
	VS:        INOUT  STD_LOGIC);
end LM35DM;
