-- generated by newgenasym Tue Mar 29 11:59:58 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity IDT7201A_L is
    port (    
	D:         IN     STD_LOGIC_VECTOR (8 DOWNTO 0);    
	\ef*\:     OUT    STD_LOGIC;    
	\ff*\:     OUT    STD_LOGIC;    
	\fl/rt*\:  IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (8 DOWNTO 0);    
	\r*\:      IN     STD_LOGIC;    
	\rs*\:     IN     STD_LOGIC;    
	\w*\:      IN     STD_LOGIC;    
	\xi*\:     IN     STD_LOGIC;    
	\xo/hf*\:  OUT    STD_LOGIC);
end IDT7201A_L;
