`timescale 1ns/1ns

module generic_utilities_ports (async_delay_in, async_delay_out, async_pulse_out, sync_delay_in, sync_delay_out, 
    sync_pulse_out );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:12 2015
// from tubii_lib/GENERIC_UTILITIES_PORTS/sch_1

  inout  async_delay_in;
  inout  async_delay_out;
  inout  async_pulse_out;
  inout  sync_delay_in;
  inout  sync_delay_out;
  inout  sync_pulse_out;
  // global signal glbl.gnd;
  // global signal glbl.vcc;

  wire  unnamed_1_10h125_i2_a;
  wire  unnamed_1_10h125_i2_b;
  wire  unnamed_1_10h125_i3_a;
  wire  unnamed_1_10h125_i3_b;
  wire  unnamed_1_mc10h124_i26_out;
  wire  unnamed_1_mc10h124_i27_out;
  wire  unnamed_1_mc10h124_i28_out;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  csmd0805 page1_i1  (.a({glbl.gnd}),
	.b(unnamed_1_10h125_i2_b));

  \10h125  page1_i2  (.a(unnamed_1_10h125_i2_a),
	.\b* (unnamed_1_10h125_i2_b),
	.v(unnamed_1_10h125_i2_b),
	.y(sync_delay_in));
  defparam page1_i2.size = 1;

  \10h125  page1_i3  (.a(unnamed_1_10h125_i3_a),
	.\b* (unnamed_1_10h125_i3_b),
	.v(unnamed_1_10h125_i3_b),
	.y(async_delay_in));
  defparam page1_i3.size = 1;

  csmd0805 page1_i5  (.a(/* unconnected */),
	.b(unnamed_1_10h125_i3_b));

  testpoint_l page1_i7  (.a(unnamed_1_mc10h124_i28_out));

  testpoint_l page1_i8  (.a(glbl.gnd));

  testpoint_l page1_i10  (.a(async_delay_out));

  testpoint_l page1_i12  (.a(glbl.gnd));

  testpoint_l page1_i14  (.a(unnamed_1_10h125_i2_a));

  testpoint_l page1_i17  (.a(glbl.gnd));

  testpoint_l page1_i18  (.a(unnamed_1_10h125_i3_a));

  testpoint_l page1_i19  (.a(glbl.gnd));

  testpoint_l page1_i20  (.a(unnamed_1_mc10h124_i26_out));

  testpoint_l page1_i21  (.a(glbl.gnd));

  testpoint_l page1_i23  (.a(unnamed_1_mc10h124_i27_out));

  testpoint_l page1_i24  (.a(glbl.gnd));

  mc10h124 page1_i26  (.common(glbl.vcc),
	.in(sync_pulse_out),
	.out(unnamed_1_mc10h124_i26_out),
	.\out* (/* unconnected */));

  mc10h124 page1_i27  (.common(glbl.vcc),
	.in(async_pulse_out),
	.out(unnamed_1_mc10h124_i27_out),
	.\out* (/* unconnected */));

  mc10h124 page1_i28  (.common(glbl.vcc),
	.in(sync_delay_out),
	.out(unnamed_1_mc10h124_i28_out),
	.\out* (/* unconnected */));

endmodule // generic_utilities_ports(sch_1) 
