// generated by newgenasym  Mon Sep 08 13:58:16 2014


module opa4277 (\+in_a , \+in_b , \+in_c , \+in_d , \-in_a , \-in_b , \-in_c , \-in_d ,
        out_a, out_b, out_c, out_d);
    inout \+in_a ;
    inout \+in_b ;
    inout \+in_c ;
    inout \+in_d ;
    inout \-in_a ;
    inout \-in_b ;
    inout \-in_c ;
    inout \-in_d ;
    inout out_a;
    inout out_b;
    inout out_c;
    inout out_d;


    initial
        begin
        end

endmodule
