`timescale 1ns/1ns

module generic_delays (async_delay_in, async_delay_out, clk, data, le );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:22 2015
// from tubii_lib/GENERIC_DELAYS/sch_1

  inout  async_delay_in;
  inout  async_delay_out;
  inout  clk;
  inout  data;
  inout  le;
  // global signal glbl.gnd;
  // global signal glbl.vcc;
  // global signal glbl.vtt;

  wire  unnamed_1_ds102350_i46_le;
  wire  unnamed_1_ds102350_i46_out;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

// begin instances 

  f06 page1_i45  (.a(le),
	.\y* (unnamed_1_ds102350_i46_le),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i45.size = 1;

  ds102350 page1_i46  (.\clk/p1 (clk),
	.\d/p2 (data),
	.in(async_delay_in),
	.\le* (unnamed_1_ds102350_i46_le),
	.ms(glbl.gnd),
	.out(unnamed_1_ds102350_i46_out),
	.p3(/* unconnected */),
	.p4(/* unconnected */),
	.p5(/* unconnected */),
	.p6(/* unconnected */),
	.p7(/* unconnected */),
	.ps(glbl.vcc),
	.pwm(/* unconnected */),
	.\q/p0 (/* unconnected */));

  rsmd0805 page1_i47  (.a({glbl.vtt}),
	.b(async_delay_out));

  led_pulse page1_i48  (.pulse_in(unnamed_1_ds102350_i46_out));

  rsmd0805 page1_i49  (.a(unnamed_1_ds102350_i46_le),
	.b({glbl.vcc}));

  mc10h124 page1_i50  (.common(glbl.vcc),
	.in(unnamed_1_ds102350_i46_out),
	.out(async_delay_out),
	.\out* (/* unconnected */));

endmodule // generic_delays(sch_1) 
