`timescale 1ns/1ns

module lockout ();
// generated by  HDL Direct 16.3-p006 (v16-3-85F) 11/10/2009
// on Wed Jul 13 10:23:20 2011
// from tubii_lib/LOCKOUT/sch_1

  // global signal glbl.gnd;
  // global signal glbl.lockout;
  // global signal glbl.\lockout* ;
  // global signal glbl.vcc;
  // global signal glbl.vtt;

  wire  \lo* ;

  wire  gnd;
  wire  page1_gnd;
  wire  lockout;
  wire  page1_lockout;
  wire  \lockout* ;
  wire  \page1_lockout* ;
  wire  vcc;
  wire  page1_vcc;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign lockout = glbl.lockout;
  assign page1_lockout = lockout;
  assign \lockout*  = glbl.\lockout* ;
  assign \page1_lockout*  = \lockout* ;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;

// begin instances 

  testpoint_l page1_i1  (.a(\lo* ));

  testpoint_l page1_i2  (.a(glbl.gnd));

  \10h124  page1_i4  (.a(\lo* ),
	.e(glbl.vcc),
	.y({glbl.\lockout* }),
	.\y* ({glbl.lockout}));
  defparam page1_i4.size = 1;

  rsmd0805 page1_i5  (.a({glbl.vtt}),
	.b({glbl.\lockout* }));

  rsmd0805 page1_i6  (.a({glbl.vtt}),
	.b({glbl.lockout}));

endmodule // lockout(sch_1) 
