// generated by newgenasym  Tue Mar 29 11:56:54 2011


module ca741_l (nin, nvss, out, pin, pvss);
    inout nin;
    inout nvss;
    inout out;
    inout pin;
    inout pvss;


    initial
        begin
        end

endmodule
