-- generated by newgenasym Tue Mar 29 11:56:54 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CA741_L is
    port (    
	NIN:       INOUT  STD_LOGIC;    
	NVSS:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	PIN:       INOUT  STD_LOGIC;    
	PVSS:      INOUT  STD_LOGIC);
end CA741_L;
