-- generated by newgenasym Tue Mar 29 11:59:19 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity VRES is
    port (    
	A:         IN     STD_LOGIC;    
	B:         OUT    STD_LOGIC;    
	C:         INOUT  STD_LOGIC);
end VRES;
