// generated by newgenasym  Tue Mar 29 11:57:45 2011


module lm308_l (cmp1, cmp2, nin, nvss, out, pin, pvss);
    inout cmp1;
    inout cmp2;
    input nin;
    inout nvss;
    output out;
    input pin;
    inout pvss;


    initial
        begin
        end

endmodule
