-- generated by newgenasym Tue Mar 29 11:57:45 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM308_L is
    port (    
	CMP1:      INOUT  STD_LOGIC;    
	CMP2:      INOUT  STD_LOGIC;    
	NIN:       IN     STD_LOGIC;    
	NVSS:      INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	PIN:       IN     STD_LOGIC;    
	PVSS:      INOUT  STD_LOGIC);
end LM308_L;
