-- generated by newgenasym Tue Mar 29 12:00:20 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity BAS16LT1 is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC);
end BAS16LT1;
