// generated by newgenasym  Tue Jun 28 17:58:40 2011


module tubiigt (bus, clock25h, clock25l, ploadenable_ttl, pulseenable,
        ttlclock3_125, tubiigt_ie, tubiigt_oe, tubiigth, tubiigtl);
    input [23:0] bus;
    input clock25h;
    input clock25l;
    input ploadenable_ttl;
    input pulseenable;
    output ttlclock3_125;
    input tubiigt_ie;
    input tubiigt_oe;
    output tubiigth;
    output tubiigtl;


    initial
        begin
        end

endmodule
