-- generated by newgenasym Tue Jun 28 17:58:40 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TUBIIGT is
    port (    
	\bus\:     IN     STD_LOGIC_VECTOR (23 DOWNTO 0);    
	CLOCK25H:  IN     STD_LOGIC;    
	CLOCK25L:  IN     STD_LOGIC;    
	PLOADENABLE_TTL: IN     STD_LOGIC;    
	PULSEENABLE: IN     STD_LOGIC;    
	TTLCLOCK3_125: OUT    STD_LOGIC;    
	TUBIIGT_IE: IN     STD_LOGIC;    
	TUBIIGT_OE: IN     STD_LOGIC;    
	TUBIIGTH:  OUT    STD_LOGIC;    
	TUBIIGTL:  OUT    STD_LOGIC);
end TUBIIGT;
