// generated by newgenasym  Tue Mar 29 11:59:58 2011


module idt7201a_l (d, \ef* , \ff* , \fl/rt* , q, \r* , \rs* , \w* , \xi* , \xo/hf* );
    input [8:0] d;
    output \ef* ;
    output \ff* ;
    input \fl/rt* ;
    output [8:0] q;
    input \r* ;
    input \rs* ;
    input \w* ;
    input \xi* ;
    output \xo/hf* ;


    initial
        begin
        end

endmodule
