// generated by newgenasym  Wed Oct 01 15:10:41 2014


module \ecl-nim  (ecl_in_bnc, ecl_in_smb, nim_out);
    input ecl_in_bnc;
    input ecl_in_smb;
    output nim_out;


    initial
        begin
        end

endmodule
