-- generated by newgenasym Wed Oct 01 15:10:41 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ecl-nim\ is
    port (    
	ECL_IN_BNC: IN     STD_LOGIC;    
	ECL_IN_SMB: IN     STD_LOGIC;    
	NIM_OUT:   OUT    STD_LOGIC);
end \ecl-nim\;
