-- generated by newgenasym Tue Oct 14 18:35:58 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ecl-nim\ is
    port (    
	ECL_IN:    IN     STD_LOGIC;    
	NIM_OUT:   OUT    STD_LOGIC);
end \ecl-nim\;
