// generated by newgenasym  Tue Mar 29 12:00:15 2011


module ad876 (ain, clk, cml, d, refbf, refbs, reftf, refts, stby,
        three_state);
    inout ain;
    input clk;
    input cml;
    output [9:0] d;
    input refbf;
    output refbs;
    input reftf;
    output refts;
    input stby;
    input three_state;


    initial
        begin
        end

endmodule
