-- generated by newgenasym Tue Mar 29 11:58:36 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RELAY is
    port (    
	S1:        IN     STD_LOGIC;    
	S2:        IN     STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end RELAY;
