// generated by newgenasym  Tue Mar 29 11:58:06 2011


module max327 (c1, c2, c3, c4, in1, in2, in3, in4, out1, out2, out3, out4,
        vminus, vplus);
    input c1;
    input c2;
    input c3;
    input c4;
    input in1;
    input in2;
    input in3;
    input in4;
    output out1;
    output out2;
    output out3;
    output out4;
    input vminus;
    input vplus;


    initial
        begin
        end

endmodule
