// generated by newgenasym  Tue Mar 29 11:57:05 2011


module conn25to26 (pin1, pin10, pin11, pin12, pin13, pin14, pin15, pin16, pin17,
        pin18, pin19, pin2, pin20, pin21, pin22, pin23, pin24, pin25,
        pin3, pin4, pin5, pin6, pin7, pin8, pin9);
    inout pin1;
    inout pin10;
    inout pin11;
    inout pin12;
    inout pin13;
    inout pin14;
    inout pin15;
    inout pin16;
    inout pin17;
    inout pin18;
    inout pin19;
    inout pin2;
    inout pin20;
    inout pin21;
    inout pin22;
    inout pin23;
    inout pin24;
    inout pin25;
    inout pin3;
    inout pin4;
    inout pin5;
    inout pin6;
    inout pin7;
    inout pin8;
    inout pin9;


    initial
        begin
        end

endmodule
