-- generated by newgenasym Tue Mar 29 11:58:10 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX507 is
    port (    
	AGND:      IN     STD_LOGIC;    
	\clr*\:    IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	D0:        IN     STD_LOGIC;    
	D1:        IN     STD_LOGIC;    
	D10:       IN     STD_LOGIC;    
	D11:       IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	D5:        IN     STD_LOGIC;    
	D6:        IN     STD_LOGIC;    
	D7:        IN     STD_LOGIC;    
	D8:        IN     STD_LOGIC;    
	D9:        IN     STD_LOGIC;    
	DGND:      IN     STD_LOGIC;    
	\ldac*\:   IN     STD_LOGIC;    
	REFOUT:    OUT    STD_LOGIC;    
	RFB:       IN     STD_LOGIC;    
	ROFS:      IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC;    
	VSS:       IN     STD_LOGIC;    
	\wr*\:     IN     STD_LOGIC);
end MAX507;
