-- generated by newgenasym Tue Mar 29 11:58:20 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MC7952KC is
    port (    
	COM:       INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC);
end MC7952KC;
