// generated by newgenasym  Tue Mar 29 11:57:24 2011


module dramsimmb (a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, \cas0* , \cas1* , \cas2* ,
        \cas3* , dq1, dq10, dq11, dq12, dq13, dq14, dq15, dq16, dq17,
        dq18, dq19, dq2, dq20, dq21, dq22, dq23, dq24, dq25, dq26, dq27,
        dq28, dq29, dq3, dq30, dq31, dq32, dq4, dq5, dq6, dq7, dq8, dq9,
        prd1, prd2, prd3, prd4, \ras0* , \ras2* , \we* );
    input a0;
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input \cas0* ;
    input \cas1* ;
    input \cas2* ;
    input \cas3* ;
    input dq1;
    input dq10;
    input dq11;
    input dq12;
    input dq13;
    input dq14;
    input dq15;
    input dq16;
    input dq17;
    input dq18;
    input dq19;
    input dq2;
    input dq20;
    input dq21;
    input dq22;
    input dq23;
    input dq24;
    input dq25;
    input dq26;
    input dq27;
    input dq28;
    input dq29;
    input dq3;
    input dq30;
    input dq31;
    input dq32;
    input dq4;
    input dq5;
    input dq6;
    input dq7;
    input dq8;
    input dq9;
    input prd1;
    input prd2;
    input prd3;
    input prd4;
    input \ras0* ;
    input \ras2* ;
    input \we* ;


    initial
        begin
        end

endmodule
