// generated by newgenasym  Tue Mar 29 11:58:13 2011


module max529 (clk, \cs* , din, dout, out, refh1, refh2, refl1, refl2, \shdn* ,
        vdd, vss);
    input clk;
    input \cs* ;
    input din;
    output dout;
    inout [7:0] out;
    inout refh1;
    inout refh2;
    inout refl1;
    inout refl2;
    input \shdn* ;
    inout vdd;
    inout vss;


    initial
        begin
        end

endmodule
