// generated by newgenasym  Tue Mar 29 11:56:33 2011


module \7815_l  (ground, \input , \output );
    inout ground;
    input \input ;
    output \output ;


    initial
        begin
        end

endmodule
