// generated by newgenasym  Tue Mar 29 12:00:45 2011


module trimpot (a, b, c);
    parameter    size = 1;
    input [size-1:0] a;
    output [size-1:0] b;
    inout [size-1:0] c;


    initial
        begin
        end

endmodule
