// generated by newgenasym  Tue Mar 29 11:56:51 2011


module bregs96t (ba, \bcreg_reg* , \bdtack_req* , \bfiforeg_rd* , \bfiforeg_wr* ,
        \breg32_63_rd* , \breg32_63_wr* , \breg_rd- , \breg_wr- ,
        bregspace, \bsbread* , bsbselect, bsqcreg_req, btestmode1,
        cclk, din, dout, m2, \program* , \pwrdwn* , \rdata* , \reset* , rtrig,
        sparein, spareout);
    input [10:2] ba;
    output \bcreg_reg* ;
    output \bdtack_req* ;
    output \bfiforeg_rd* ;
    output \bfiforeg_wr* ;
    output \breg32_63_rd* ;
    output \breg32_63_wr* ;
    output [15:0] \breg_rd- ;
    output [15:0] \breg_wr- ;
    input bregspace;
    input \bsbread* ;
    input bsbselect;
    output bsqcreg_req;
    input btestmode1;
    input cclk;
    input din;
    output dout;
    output m2;
    input \program* ;
    input \pwrdwn* ;
    output \rdata* ;
    input \reset* ;
    input rtrig;
    input [1:0] sparein;
    output [1:0] spareout;


    initial
        begin
        end

endmodule
