// generated by newgenasym  Wed Feb 25 16:09:49 2015


module tubii_clks (bckp_clk, clk200_out_n, clk200_out_p, default_clk,
        default_select, fox200mhz, tub_clk_in);
    output bckp_clk;
    output clk200_out_n;
    output clk200_out_p;
    output default_clk;
    input default_select;
    output fox200mhz;
    input tub_clk_in;


    initial
        begin
        end

endmodule
