-- generated by newgenasym Wed Feb 25 16:09:49 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tubii_clks is
    port (    
	BCKP_CLK:  OUT    STD_LOGIC;    
	CLK200_OUT_N: OUT    STD_LOGIC;    
	CLK200_OUT_P: OUT    STD_LOGIC;    
	DEFAULT_CLK: OUT    STD_LOGIC;    
	DEFAULT_SELECT: IN     STD_LOGIC;    
	FOX200MHZ: OUT    STD_LOGIC;    
	TUB_CLK_IN: IN     STD_LOGIC);
end tubii_clks;
