-- generated by newgenasym Fri Oct 03 13:14:29 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tubii_clks is
    port (    
	BCKP_CLK:  OUT    STD_LOGIC;    
	CLOCK200_OUTH: OUT    STD_LOGIC;    
	CLOCK200_OUTL: OUT    STD_LOGIC;    
	DEFAULT_CLK: OUT    STD_LOGIC;    
	DEFAULT_SELECT: IN     STD_LOGIC;    
	FOX200MHZ: OUT    STD_LOGIC;    
	TUB_CLK_IN: IN     STD_LOGIC);
end tubii_clks;
