// generated by newgenasym  Tue Oct 28 16:05:52 2014


module asyncdelays (clk, \ddgt* , delay_val, dgt_ttl, dgth, dgtl, gtrigh, gtrigl,
        le_dgt);
    input clk;
    output \ddgt* ;
    input delay_val;
    output dgt_ttl;
    output dgth;
    output dgtl;
    input gtrigh;
    input gtrigl;
    input le_dgt;


    initial
        begin
        end

endmodule
