// generated by newgenasym  Wed Feb 04 17:22:36 2015


module asyncdelays (clk, \ddgt* , delay_val, dgt_ttl, dgth, dgtl, gtrig, le_dgt);
    input clk;
    output \ddgt* ;
    input delay_val;
    output dgt_ttl;
    output dgth;
    output dgtl;
    input gtrig;
    input le_dgt;


    initial
        begin
        end

endmodule
