// generated by newgenasym  Wed Feb 25 12:39:48 2015


module asyncdelays (clk, \ddgt* , delay_val, dgt_n, dgt_p, dgt_ttl, gtrig, le_dgt);
    input clk;
    output \ddgt* ;
    input delay_val;
    output dgt_n;
    output dgt_p;
    output dgt_ttl;
    input gtrig;
    input le_dgt;


    initial
        begin
        end

endmodule
