-- generated by newgenasym Tue Oct 28 16:05:52 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity asyncdelays is
    port (    
	CLK:       IN     STD_LOGIC;    
	\ddgt*\:   OUT    STD_LOGIC;    
	DELAY_VAL: IN     STD_LOGIC;    
	DGT_TTL:   OUT    STD_LOGIC;    
	DGTH:      OUT    STD_LOGIC;    
	DGTL:      OUT    STD_LOGIC;    
	GTRIGH:    IN     STD_LOGIC;    
	GTRIGL:    IN     STD_LOGIC;    
	LE_DGT:    IN     STD_LOGIC);
end asyncdelays;
