-- generated by newgenasym Wed Feb 25 12:39:48 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity asyncdelays is
    port (    
	CLK:       IN     STD_LOGIC;    
	\ddgt*\:   OUT    STD_LOGIC;    
	DELAY_VAL: IN     STD_LOGIC;    
	DGT_N:     OUT    STD_LOGIC;    
	DGT_P:     OUT    STD_LOGIC;    
	DGT_TTL:   OUT    STD_LOGIC;    
	GTRIG:     IN     STD_LOGIC;    
	LE_DGT:    IN     STD_LOGIC);
end asyncdelays;
