// generated by newgenasym  Tue Mar 29 11:59:33 2011


module \10e131  (clk, d, en, q, \q* , r, s);
    parameter    size = 1;
    input clk;
    input [size-1:0] d;
    input en;
    output [size-1:0] q;
    output [size-1:0] \q* ;
    input r;
    input s;


    initial
        begin
        end

endmodule
