// generated by newgenasym  Tue Mar 29 11:57:48 2011


module lm310_l (nvss, out, pin, pvss);
    inout nvss;
    output out;
    input pin;
    inout pvss;


    initial
        begin
        end

endmodule
