-- generated by newgenasym Tue Mar 29 11:57:48 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM310_L is
    port (    
	NVSS:      INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	PIN:       IN     STD_LOGIC;    
	PVSS:      INOUT  STD_LOGIC);
end LM310_L;
