// generated by newgenasym  Tue Mar 29 11:58:08 2011


module max414 (in1m, in1p, in2m, in2p, in3m, in3p, in4m, in4p, out1, out2,
        out3, out4, vminus, vplus);
    input in1m;
    input in1p;
    input in2m;
    input in2p;
    input in3m;
    input in3p;
    input in4m;
    input in4p;
    output out1;
    output out2;
    output out3;
    output out4;
    input vminus;
    input vplus;


    initial
        begin
        end

endmodule
