// generated by newgenasym  Tue Mar 29 11:58:47 2011


module sip10 (p1, p10, p2, p3, p4, p5, p6, p7, p8, p9);
    inout p1;
    inout p10;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;


    initial
        begin
        end

endmodule
