-- generated by newgenasym Tue Oct 21 16:09:03 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity powers is
    port (    
	POWER:     IN     STD_LOGIC_VECTOR (5 DOWNTO 1));
end powers;
