-- generated by newgenasym Wed Jul 13 10:23:20 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity POWERS is
    port (    
	POWER:     IN     STD_LOGIC_VECTOR (3 DOWNTO 1));
end POWERS;
