// generated by newgenasym  Fri Oct 03 15:42:45 2014


module tubii_triggers (burst_trig, combo_trig, prescale_trig, rawtrigs,
        tubii_gt);
    output burst_trig;
    output combo_trig;
    output prescale_trig;
    input [3:0] rawtrigs;
    output tubii_gt;


    initial
        begin
        end

endmodule
