-- generated by newgenasym Mon Feb 02 18:25:55 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tubii_triggers is
    port (    
	RAWTRIGS:  INOUT  std_logic_vector (0 TO 3);    
	TUBII_RT:  INOUT  std_logic);
end tubii_triggers;
