-- generated by newgenasym Fri Oct 17 14:00:45 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tubii_triggers is
    port (    
	RAWTRIGS:  IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	TUBII_RT:  OUT    STD_LOGIC);
end tubii_triggers;
