-- generated by newgenasym Fri Jan 30 18:14:53 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TUBII_TRIGGERS is
    port (    
	RAWTRIGS:  INOUT  std_logic_vector (0 TO 3);    
	TUBII_RT:  INOUT  std_logic);
end TUBII_TRIGGERS;
