// generated by newgenasym  Wed Sep 03 13:36:07 2014


module asyncdelay (clk, delay_val, le_ddgt, le_dgt);
    input clk;
    input delay_val;
    input le_ddgt;
    input le_dgt;


    initial
        begin
        end

endmodule
