-- generated by newgenasym Wed Sep 03 13:36:07 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity asyncdelay is
    port (    
	CLK:       IN     STD_LOGIC;    
	DELAY_VAL: IN     STD_LOGIC;    
	LE_DDGT:   IN     STD_LOGIC;    
	LE_DGT:    IN     STD_LOGIC);
end asyncdelay;
