`timescale 1ns/1ns

module clocks (clk100_outh, clk100_outl, clock100, clock200_outh, clock200_outl, data, data_rdy, default_select, 
    fox200mhz, le, missedclock, sr_clk, tub_clk_in );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:20 2015
// from tubii_lib/CLOCKS/sch_1

  inout  clk100_outh;
  inout  clk100_outl;
  inout  clock100;
  inout  clock200_outh;
  inout  clock200_outl;
  inout  data;
  inout  data_rdy;
  inout  default_select;
  inout  fox200mhz;
  inout  le;
  inout  missedclock;
  inout  sr_clk;
  inout  tub_clk_in;
  // global signal glbl.vtt;

  wire  unnamed_1_tubiiclks_i1_bckpclk;
  wire  unnamed_1_tubiiclks_i1_defaultclk;

  wire  vtt;
  wire  page1_vtt;

  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

// begin instances 

  tubii_clks page1_i1  (.bckp_clk(unnamed_1_tubiiclks_i1_bckpclk),
	.clock200_outh(clock200_outh),
	.clock200_outl(clock200_outl),
	.default_clk(unnamed_1_tubiiclks_i1_defaultclk),
	.default_select(default_select),
	.fox200mhz(fox200mhz),
	.tub_clk_in(tub_clk_in));

  tubii_time page1_i2  (.bckp_clk(unnamed_1_tubiiclks_i1_bckpclk),
	.clk100_outh(clk100_outh),
	.clk100_outl(clk100_outl),
	.data(data),
	.data_rdy(data_rdy),
	.default_clk(unnamed_1_tubiiclks_i1_defaultclk),
	.le(le),
	.missedclock(missedclock),
	.sr_clk(sr_clk));

  \10h125  page1_i3  (.a(clk100_outh),
	.\b* (clk100_outl),
	.v(/* unconnected */),
	.y(clock100));
  defparam page1_i3.size = 1;

  rsmd0805 page1_i4  (.a(clk100_outl),
	.b({glbl.vtt}));

  rsmd0805 page1_i5  (.a(clk100_outh),
	.b({glbl.vtt}));

endmodule // clocks(sch_1) 
