`timescale 1ns/1ns

module tubii_spkr (spkr_signal );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:16 2015
// from tubii_lib/TUBII_SPKR/sch_1

  inout  spkr_signal;
  // global signal glbl.gnd;
  // global signal glbl.vcc;

  wire  unnamed_1_csmd0805_i22_a;
  wire  unnamed_1_csmd0805_i22_b;
  wire  unnamed_1_csmd0805_i23_a;
  wire  unnamed_1_csmd0805_i23_b;
  wire  unnamed_1_csmd0805_i41_a;
  wire  unnamed_1_csmd0805_i41_b;
  wire  unnamed_1_f06_i26_a;
  wire  unnamed_1_ledl_i42_a;
  wire  unnamed_1_ledl_i43_a;
  wire  unnamed_1_rsmd0805_i13_b;
  wire  unnamed_1_rsmd0805_i17_b;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;

// begin instances 

  hct123 page1_i1  (.c(unnamed_1_csmd0805_i41_a),
	.\c/r (unnamed_1_csmd0805_i41_b),
	.\cl* (glbl.vcc),
	.clock(spkr_signal),
	.\clock* (glbl.gnd),
	.q(unnamed_1_f06_i26_a),
	.\q* (/* unconnected */));
  defparam page1_i1.pulse_width = 10000;

  testpoint_l page1_i6  (.a(unnamed_1_csmd0805_i23_b));

  testpoint_l page1_i7  (.a(unnamed_1_rsmd0805_i13_b));

  testpoint_l page1_i12  (.a(glbl.gnd));

  rsmd0805 page1_i13  (.a({glbl.vcc}),
	.b(unnamed_1_rsmd0805_i13_b));

  testpoint_l page1_i14  (.a(unnamed_1_csmd0805_i22_b));

  testpoint_l page1_i15  (.a(unnamed_1_rsmd0805_i17_b));

  testpoint_l page1_i16  (.a(glbl.gnd));

  rsmd0805 page1_i17  (.a({glbl.vcc}),
	.b(unnamed_1_rsmd0805_i17_b));

  rsmd0805 page1_i18  (.a(unnamed_1_csmd0805_i23_a),
	.b({glbl.vcc}));

  rsmd0805 page1_i19  (.a(unnamed_1_ledl_i42_a),
	.b(unnamed_1_csmd0805_i23_a));

  rsmd0805 page1_i20  (.a(unnamed_1_csmd0805_i22_a),
	.b({glbl.vcc}));

  rsmd0805 page1_i21  (.a(unnamed_1_ledl_i43_a),
	.b(unnamed_1_csmd0805_i22_a));

  csmd0805 page1_i22  (.a(unnamed_1_csmd0805_i22_a),
	.b(unnamed_1_csmd0805_i22_b));

  csmd0805 page1_i23  (.a(unnamed_1_csmd0805_i23_a),
	.b(unnamed_1_csmd0805_i23_b));

  f06 page1_i26  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i23_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i26.size = 1;

  f06 page1_i27  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i23_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i27.size = 1;

  f06 page1_i28  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i23_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i28.size = 1;

  f06 page1_i29  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i23_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i29.size = 1;

  f06 page1_i30  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i23_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i30.size = 1;

  f06 page1_i31  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i23_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i31.size = 1;

  f06 page1_i32  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i22_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i32.size = 1;

  f06 page1_i33  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i22_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i33.size = 1;

  f06 page1_i34  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i22_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i34.size = 1;

  f06 page1_i35  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i22_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i35.size = 1;

  f06 page1_i36  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i22_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i36.size = 1;

  f06 page1_i37  (.a(unnamed_1_f06_i26_a),
	.\y* (unnamed_1_csmd0805_i22_a),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i37.size = 1;

  testpoint_l page1_i38  (.a(glbl.vcc));

  testpoint_l page1_i39  (.a(glbl.gnd));

  testpoint_l page1_i40  (.a(unnamed_1_csmd0805_i41_b));

  csmd0805 page1_i41  (.a(unnamed_1_csmd0805_i41_a),
	.b(unnamed_1_csmd0805_i41_b));

  led_l page1_i42  (.a(unnamed_1_ledl_i42_a),
	.b(glbl.gnd));

  led_l page1_i43  (.a(unnamed_1_ledl_i43_a),
	.b(glbl.gnd));

  csmd0603 page1_i44  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  csmd0603 page1_i45  (.a({glbl.gnd}),
	.b({glbl.vcc}));

  csmd0603 page1_i46  (.a({glbl.gnd}),
	.b({glbl.vcc}));

endmodule // tubii_spkr(sch_1) 
