`timescale 1ns/1ns

module fastcomp (anpulsein, dgt_gate, gtrig, \lo* , posneg, trig_outh, trig_outl, vbb_comp );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:21 2015
// from tubii_lib/FASTCOMP/sch_1

  inout  anpulsein;
  inout  dgt_gate;
  inout  gtrig;
  inout  \lo* ;
  inout  posneg;
  inout  trig_outh;
  inout  trig_outl;
  inout  vbb_comp;
  // global signal glbl.gnd;
  // global signal glbl.vcc;
  // global signal glbl.vih;
  // global signal glbl.vref2m;
  // global signal glbl.vtt;

  wire  \gtrig/i ;
  wire  unnamed_1_10e101_i123_a;
  wire  unnamed_1_10e101_i123_c;
  wire  unnamed_1_10e101_i123_d;
  wire  unnamed_1_10e101_i123_y;
  wire  unnamed_1_10e101_i123_y_1;
  wire  unnamed_1_10e116_i29_a;
  wire  unnamed_1_10e116_i29_y;
  wire  unnamed_1_10e116_i9_a;
  wire  unnamed_1_10e116_i9_b;
  wire  unnamed_1_10h125_i23_y;
  wire  unnamed_1_10h131_i118_clk;
  wire  unnamed_1_10h131_i118_d;
  wire  unnamed_1_10h131_i120_s;
  wire  unnamed_1_adcmp566_i37_in;
  wire  unnamed_1_adcmp566_i37_q;
  wire  unnamed_1_adcmp566_i37_q_1;
  wire  unnamed_1_csmd0805_i105_b;
  wire  unnamed_1_csmd0805_i106_b;
  wire  unnamed_1_mc10h104_i108_a;
  wire  unnamed_1_mc10h104_i109_b;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;
  wire  vih;
  wire  page1_vih;
  wire  vref2m;
  wire  page1_vref2m;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vih = glbl.vih;
  assign page1_vih = vih;
  assign vref2m = glbl.vref2m;
  assign page1_vref2m = vref2m;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  \10e116  page1_i9  (.a(unnamed_1_10e116_i9_a),
	.\b* (unnamed_1_10e116_i9_b),
	.ref(vbb_comp),
	.y(trig_outh),
	.\y* (trig_outl));
  defparam page1_i9.size = 1;

  \10h125  page1_i23  (.a(unnamed_1_10e101_i123_y_1),
	.\b* (unnamed_1_10e101_i123_y),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i23_y));
  defparam page1_i23.size = 1;

  rsmd0805 page1_i25  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i9_b));

  rsmd0805 page1_i26  (.a({glbl.vtt}),
	.b(unnamed_1_10e116_i9_a));

  csmd0805 page1_i27  (.a({glbl.gnd}),
	.b(unnamed_1_10e116_i29_a));

  rsmd0805 page1_i28  (.a(unnamed_1_10e116_i29_a),
	.b(unnamed_1_10e116_i9_a));

  \10e116  page1_i29  (.a(unnamed_1_10e116_i29_a),
	.\b* (vbb_comp),
	.ref(vbb_comp),
	.y(unnamed_1_10e116_i29_y),
	.\y* (/* unconnected */));
  defparam page1_i29.size = 1;

  csmd0805 page1_i31  (.a({glbl.gnd}),
	.b(vbb_comp));

  adcmp566 page1_i37  (.in(anpulsein),
	.\in* (unnamed_1_adcmp566_i37_in),
	.le(glbl.vcc),
	.\le* (glbl.gnd),
	.nc(/* unconnected */),
	.nc2(/* unconnected */),
	.q(unnamed_1_adcmp566_i37_q),
	.\q* (unnamed_1_adcmp566_i37_q_1));

  rsmd0805 page1_i38  (.a({glbl.vtt}),
	.b(unnamed_1_adcmp566_i37_q_1));

  rsmd0805 page1_i40  (.a({glbl.vtt}),
	.b(unnamed_1_adcmp566_i37_q));

  rsmd0805 page1_i41  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h104_i109_b));

  rsmd0805 page1_i42  (.a({glbl.vtt}),
	.b(unnamed_1_mc10h104_i108_a));

  rsmd0805 page1_i50  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i123_d));

  rsmd0805 page1_i52  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i123_y));

  rsmd0805 page1_i53  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i123_y_1));

  testpoint_l page1_i94  (.a(unnamed_1_adcmp566_i37_in));

  led_pulse page1_i95  (.pulse_in(unnamed_1_10h125_i23_y));

  rsmd0805 page1_i103  (.a({glbl.vtt}),
	.b(unnamed_1_10e101_i123_a));

  csmd0805 page1_i105  (.a({glbl.vcc}),
	.b(unnamed_1_csmd0805_i105_b));

  csmd0805 page1_i106  (.a({glbl.vref2m}),
	.b(unnamed_1_csmd0805_i106_b));

  testpoint_l page1_i107  (.a(unnamed_1_adcmp566_i37_q));

  mc10h104 page1_i108  (.a(unnamed_1_mc10h104_i108_a),
	.b(unnamed_1_adcmp566_i37_q),
	.y(unnamed_1_10e101_i123_d));

  mc10h104 page1_i109  (.a(unnamed_1_adcmp566_i37_q_1),
	.b(unnamed_1_mc10h104_i109_b),
	.y(unnamed_1_10e101_i123_a));

  mc10h124 page1_i110  (.common(glbl.vcc),
	.in(posneg),
	.out(unnamed_1_mc10h104_i108_a),
	.\out* (unnamed_1_mc10h104_i109_b));

  testpoint_l page1_i111  (.a(unnamed_1_csmd0805_i106_b));

  testpoint_l page1_i112  (.a(unnamed_1_adcmp566_i37_in));

  testpoint_l page1_i113  (.a(unnamed_1_csmd0805_i105_b));

  rsmd0805 page1_i114  (.a(unnamed_1_10e116_i29_y),
	.b({glbl.gnd}));

  rsmd0805 page1_i116  (.a(unnamed_1_10h131_i120_s),
	.b({glbl.vtt}));

  rsmd0805 page1_i117  (.a(unnamed_1_10e101_i123_c),
	.b({glbl.vtt}));

  \10h131  page1_i118  (.clk(unnamed_1_10h131_i118_clk),
	.d(unnamed_1_10h131_i118_d),
	.en(\lo* ),
	.q(unnamed_1_10e101_i123_c),
	.\q* (/* unconnected */),
	.r(gtrig),
	.s(/* unconnected */));
  defparam page1_i118.size = 1;

  rsmd0805 page1_i119  (.a(unnamed_1_10h131_i118_d),
	.b({glbl.vtt}));

  \10h131  page1_i120  (.clk(unnamed_1_10h131_i118_clk),
	.d(/* unconnected */),
	.en(/* unconnected */),
	.q(unnamed_1_10h131_i118_d),
	.\q* (/* unconnected */),
	.r(\gtrig/i ),
	.s(unnamed_1_10h131_i120_s));
  defparam page1_i120.size = 1;

  mc10h104 page1_i121  (.a(unnamed_1_10e101_i123_d),
	.b(dgt_gate),
	.y(unnamed_1_10h131_i120_s));

  mc10h104 page1_i122  (.a(dgt_gate),
	.b(unnamed_1_10e101_i123_a),
	.y(unnamed_1_10h131_i120_s));

  \10e101  page1_i123  (.a(unnamed_1_10e101_i123_a),
	.b(/* unconnected */),
	.c(unnamed_1_10e101_i123_c),
	.d(unnamed_1_10e101_i123_d),
	.y(unnamed_1_10e101_i123_y_1),
	.\y* (unnamed_1_10e101_i123_y));
  defparam page1_i123.size = 1;

  \10h131  page1_i124  (.clk(/* unconnected */),
	.d({glbl.vih}),
	.en(unnamed_1_10e101_i123_y_1),
	.q(unnamed_1_10e116_i9_a),
	.\q* (unnamed_1_10e116_i9_b),
	.r(unnamed_1_10e116_i29_y),
	.s(/* unconnected */));
  defparam page1_i124.size = 1;

endmodule // fastcomp(sch_1) 
