// generated by newgenasym  Wed Feb 25 10:35:31 2015


module trigger_utility_board_mkii (async_delay_in, async_delay_out, async_pulse_out,
        caen_anpulse, caen_out, clk100_out_n, clk100_out_p,
        clk200_out_n, clk200_out_p, dgt_n, dgt_p, ext_ped_in,
        ext_ped_out, exttrig, fast_anpulse, fast_comp_out_n,
        fast_comp_out_p, gt_ecl_n, gt_ecl_p, gtrig_ttl, lockout,
        \lockout* , \mtcd_lo* , rawtrigs, scope_out, smellie_delay_in,
        smellie_delay_out, smellie_pulse_out, sync24_ecl_n,
        sync24_ecl_p, sync24_lvds_n, sync24_lvds_p, sync24_ttl,
        sync_delay_in, sync_delay_out, sync_ecl_n, sync_ecl_p,
        sync_lvds_n, sync_lvds_p, sync_pulse_out, sync_ttl,
        tellie_delay_in, tellie_delay_out, tellie_pulse_out,
        tub_clk_in, tubii_rt_out, tune_anpulse, tune_comp_out_n,
        tune_comp_out_p);
    output async_delay_in;
    output async_delay_out;
    output async_pulse_out;
    output [11:0] caen_anpulse;
    output [7:0] caen_out;
    input clk100_out_n;
    input clk100_out_p;
    input clk200_out_n;
    input clk200_out_p;
    output dgt_n;
    output dgt_p;
    output ext_ped_in;
    output ext_ped_out;
    input [15:0] exttrig;
    output fast_anpulse;
    output fast_comp_out_n;
    output fast_comp_out_p;
    output gt_ecl_n;
    output gt_ecl_p;
    inout gtrig_ttl;
    output lockout;
    output \lockout* ;
    output \mtcd_lo* ;
    input [3:0] rawtrigs;
    output [7:0] scope_out;
    input smellie_delay_in;
    input smellie_delay_out;
    input smellie_pulse_out;
    output sync24_ecl_n;
    output sync24_ecl_p;
    output sync24_lvds_n;
    output sync24_lvds_p;
    inout sync24_ttl;
    output sync_delay_in;
    output sync_delay_out;
    output sync_ecl_n;
    output sync_ecl_p;
    output sync_lvds_n;
    output sync_lvds_p;
    output sync_pulse_out;
    inout sync_ttl;
    input tellie_delay_in;
    input tellie_delay_out;
    input tellie_pulse_out;
    input tub_clk_in;
    input tubii_rt_out;
    output tune_anpulse;
    output tune_comp_out_n;
    output tune_comp_out_p;


    initial
        begin
        end

endmodule
