-- generated by newgenasym Tue Mar 29 12:00:27 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity IDS_C10 is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN10:     INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      INOUT  STD_LOGIC;    
	PIN5:      INOUT  STD_LOGIC;    
	PIN6:      INOUT  STD_LOGIC;    
	PIN7:      INOUT  STD_LOGIC;    
	PIN8:      INOUT  STD_LOGIC;    
	PIN9:      INOUT  STD_LOGIC);
end IDS_C10;
