`timescale 1ns/1ns

module comparators (clk, data, data_rdy, dgth, fast_comp_outh, fast_comp_outl, fast_pulse, gtrig, le_tune, 
    \lockout* , tune_comp_outh, tune_comp_outl, tune_pulse );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:21 2015
// from tubii_lib/COMPARATORS/sch_1

  inout  clk;
  inout  data;
  inout  data_rdy;
  inout  dgth;
  inout  fast_comp_outh;
  inout  fast_comp_outl;
  inout  fast_pulse;
  inout  gtrig;
  inout  le_tune;
  inout  \lockout* ;
  inout  tune_comp_outh;
  inout  tune_comp_outl;
  inout  tune_pulse;
  // global signal glbl.gnd;
  // global signal glbl.vcc;
  // global signal glbl.vcc5;
  // global signal glbl.vref2m;
  // global signal glbl.vtt;

  wire  vbb_comp;
  wire  unnamed_1_10h131_i26_q;
  wire  unnamed_1_bas16lt1_i14_cat;
  wire  unnamed_1_fastcomp_i1_anpulsein;
  wire  unnamed_1_fastcomp_i1_posneg;
  wire  unnamed_1_testpointl_i6_a;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;
  wire  vcc5;
  wire  page1_vcc5;
  wire  vref2m;
  wire  page1_vref2m;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vcc5 = glbl.vcc5;
  assign page1_vcc5 = vcc5;
  assign vref2m = glbl.vref2m;
  assign page1_vref2m = vref2m;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

// begin instances 

  fastcomp page1_i1  (.anpulsein(unnamed_1_fastcomp_i1_anpulsein),
	.dgt_gate(unnamed_1_10h131_i26_q),
	.gtrig(gtrig),
	.\lo* (\lockout* ),
	.posneg(unnamed_1_fastcomp_i1_posneg),
	.trig_outh(fast_comp_outh),
	.trig_outl(fast_comp_outl),
	.vbb_comp(vbb_comp));

  tuncomp page1_i2  (.anpulsein(unnamed_1_testpointl_i6_a),
	.clk(clk),
	.data(data),
	.data_rdy(data_rdy),
	.dgt_gate(unnamed_1_10h131_i26_q),
	.gtrig(gtrig),
	.le(le_tune),
	.\lo* (\lockout* ),
	.posneg(unnamed_1_bas16lt1_i14_cat),
	.trig_outh(tune_comp_outh),
	.trig_outl(tune_comp_outl),
	.vbb_comp(vbb_comp));

  testpoint_l page1_i3  (.a(unnamed_1_fastcomp_i1_posneg));

  testpoint_l page1_i4  (.a(glbl.vcc));

  testpoint_l page1_i5  (.a(glbl.gnd));

  testpoint_l page1_i6  (.a(unnamed_1_testpointl_i6_a));

  testpoint_l page1_i7  (.a(glbl.vcc));

  testpoint_l page1_i8  (.a(glbl.gnd));

  bas16lt1 page1_i14  (.an(glbl.vref2m),
	.cat(unnamed_1_bas16lt1_i14_cat));

  bas16lt1 page1_i17  (.an(glbl.vref2m),
	.cat(unnamed_1_fastcomp_i1_anpulsein));

  bas16lt1 page1_i21  (.an(unnamed_1_fastcomp_i1_anpulsein),
	.cat(glbl.vcc5));

  bas16lt1 page1_i22  (.an(unnamed_1_bas16lt1_i14_cat),
	.cat(glbl.vcc5));

  csmd0805 page1_i23  (.a(tune_pulse),
	.b(unnamed_1_bas16lt1_i14_cat));

  csmd0805 page1_i24  (.a(fast_pulse),
	.b(unnamed_1_fastcomp_i1_anpulsein));

  rsmd0805 page1_i25  (.a({glbl.vtt}),
	.b(unnamed_1_10h131_i26_q));

  \10h131  page1_i26  (.clk(/* unconnected */),
	.d(/* unconnected */),
	.en(/* unconnected */),
	.q(unnamed_1_10h131_i26_q),
	.\q* (/* unconnected */),
	.r(\lockout* ),
	.s(dgth));
  defparam page1_i26.size = 1;

endmodule // comparators(sch_1) 
