-- generated by newgenasym Mon Sep 08 10:45:07 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD8009 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end AD8009;
