// generated by newgenasym  Thu Oct 09 10:44:12 2014


module comparator_ports (fast_anpulse, fast_comp_outh, fast_comp_outl,
        tune_anpulse, tune_comp_outh, tune_comp_outl);
    input fast_anpulse;
    input fast_comp_outh;
    input fast_comp_outl;
    input tune_anpulse;
    input tune_comp_outh;
    input tune_comp_outl;


    initial
        begin
        end

endmodule
