// generated by newgenasym  Wed Feb 25 10:35:58 2015


module comparator_ports (fast_anpulse, fast_comp_out_n, fast_comp_out_p,
        tune_anpulse, tune_comp_out_n, tune_comp_out_p);
    input fast_anpulse;
    input fast_comp_out_n;
    input fast_comp_out_p;
    input tune_anpulse;
    input tune_comp_out_n;
    input tune_comp_out_p;


    initial
        begin
        end

endmodule
