-- generated by newgenasym Wed Feb 25 10:35:58 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity comparator_ports is
    port (    
	FAST_ANPULSE: IN     STD_LOGIC;    
	FAST_COMP_OUT_N: IN     STD_LOGIC;    
	FAST_COMP_OUT_P: IN     STD_LOGIC;    
	TUNE_ANPULSE: IN     STD_LOGIC;    
	TUNE_COMP_OUT_N: IN     STD_LOGIC;    
	TUNE_COMP_OUT_P: IN     STD_LOGIC);
end comparator_ports;
