-- generated by newgenasym Thu Oct 09 10:44:12 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity comparator_ports is
    port (    
	FAST_ANPULSE: IN     STD_LOGIC;    
	FAST_COMP_OUTH: IN     STD_LOGIC;    
	FAST_COMP_OUTL: IN     STD_LOGIC;    
	TUNE_ANPULSE: IN     STD_LOGIC;    
	TUNE_COMP_OUTH: IN     STD_LOGIC;    
	TUNE_COMP_OUTL: IN     STD_LOGIC);
end comparator_ports;
