// generated by newgenasym  Thu Sep 25 16:08:15 2014


module async_puls_gen (async_pulse_in, clk, data, le);
    output async_pulse_in;
    output clk;
    output data;
    output le;


    initial
        begin
        end

endmodule
