-- generated by newgenasym Thu Sep 25 16:08:15 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity async_puls_gen is
    port (    
	ASYNC_PULSE_IN: OUT    STD_LOGIC;    
	CLK:       OUT    STD_LOGIC;    
	DATA:      OUT    STD_LOGIC;    
	LE:        OUT    STD_LOGIC);
end async_puls_gen;
