van.exe -q -nolinks -sironly -cdslib cds.lib -module tubii_lib.glbl:tubii_cfg_package -lib tubii_lib -view tubii_cfg_package -globals tubii_lib.glbl:tubii_cfg_package
progdelay;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\progdelay\sch_1\verilog.v;2;1
fastcomp;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\fastcomp\sch_1\verilog.v;2;1
tuncomp;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\tuncomp\sch_1\verilog.v;2;1
datain;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\datain\sch_1\verilog.v;2;1
asyncdelaybig;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\asyncdelaybig\sch_1\verilog.v;2;1
asyncdelay;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\asyncdelay\sch_1\verilog.v;2;1
ribbondelay;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\ribbondelay\sch_1\verilog.v;2;1
ttl_progdelay;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\ttl_progdelay\sch_1\verilog.v;2;1
ellie_comms;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\ellie_comms\sch_1\verilog.v;2;1
tubiigt;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\tubiigt\sch_1\verilog.v;2;1
bursttrig;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\bursttrig\sch_1\verilog.v;2;1
ttl#232dto#232decl#232din;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\ttl#2dto#2decl#2din\sch_1\verilog.v;2;1
tubii_time;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\tubii_time\sch_1\verilog.v;2;1
prescaletrig;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\prescaletrig\sch_1\verilog.v;2;1
lvds#232decl;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\lvds#2decl\sch_1\verilog.v;2;1
ecl#232dlvds;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\ecl#2dlvds\sch_1\verilog.v;2;1
ttl#232decl;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\ttl#2decl\sch_1\verilog.v;2;1
ecl#232dttl;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\ecl#2dttl\sch_1\verilog.v;2;1
ecl#232dnim;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\ecl#2dnim\sch_1\verilog.v;2;1
nim#232decl;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\nim#2decl\sch_1\verilog.v;2;1
latchexttrig;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\latchexttrig\sch_1\verilog.v;2;1
powers;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\powers\sch_1\verilog.v;2;1
exttrig;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\exttrig\sch_1\verilog.v;2;1
caen_chat;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\caen_chat\sch_1\verilog.v;2;1
tubii;tubii_lib;sch_1;G:\My Dropbox\SNO+\TUBii\SPB_Data\TUBII1\worklib\tubii\sch_1\verilog.v;2;1
