// generated by newgenasym  Wed Oct 15 15:29:12 2014


module max9376 (in1, \in1* , in2, \in2* , out1, \out1* , out2, \out2* );
    inout in1;
    input \in1* ;
    input in2;
    input \in2* ;
    output out1;
    output \out1* ;
    output out2;
    output \out2* ;


    initial
        begin
        end

endmodule
