// generated by newgenasym  Tue Mar 29 11:56:02 2011


module \10h131_l  (cpc, cpn, d, q, \q* , r, s);
    parameter    size = 1;
    input cpc;
    input cpn;
    input [size-1:0] d;
    output [size-1:0] q;
    output [size-1:0] \q* ;
    input r;
    input s;


    initial
        begin
        end

endmodule
