// generated by newgenasym  Fri Feb 20 13:36:42 2015


module lvds_ecl_translation (ecl_in, ecl_out, lvds_out, lvdsh_in, lvdsl_in);
    input ecl_in;
    output ecl_out;
    output lvds_out;
    input lvdsh_in;
    input lvdsl_in;


    initial
        begin
        end

endmodule
