-- generated by newgenasym Fri Feb 20 13:36:42 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lvds_ecl_translation is
    port (    
	ECL_IN:    IN     STD_LOGIC;    
	ECL_OUT:   OUT    STD_LOGIC;    
	LVDS_OUT:  OUT    STD_LOGIC;    
	LVDSH_IN:  IN     STD_LOGIC;    
	LVDSL_IN:  IN     STD_LOGIC);
end lvds_ecl_translation;
