// generated by newgenasym  Mon Jan 19 16:41:50 2015


module fastcomp (anpulsein, dgt_gate, gtrig, \lo* , posneg, trig_outh,
        trig_outl, vbb_comp);
    input anpulsein;
    inout dgt_gate;
    inout gtrig;
    inout \lo* ;
    input posneg;
    output trig_outh;
    output trig_outl;
    input vbb_comp;


    initial
        begin
        end

endmodule
