// generated by newgenasym  Wed Jan 07 18:44:39 2015


module fastcomp (anpulsein, dgt_gate, gtrig, \lo* , posneg, trig_outh,
        trig_outl);
    input anpulsein;
    inout dgt_gate;
    inout gtrig;
    inout \lo* ;
    input posneg;
    output trig_outh;
    output trig_outl;


    initial
        begin
        end

endmodule
