// generated by newgenasym  Thu Oct 02 11:26:54 2014


module fastcomp (anpulsein, dgth, dgtl, lockout, \lockout* , posneg,
        trig_outh, trig_outl);
    input anpulsein;
    inout dgth;
    inout dgtl;
    inout lockout;
    inout \lockout* ;
    input posneg;
    output trig_outh;
    output trig_outl;


    initial
        begin
        end

endmodule
