-- generated by newgenasym Wed Jan 07 18:44:39 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fastcomp is
    port (    
	ANPULSEIN: IN     STD_LOGIC;    
	DGT_GATE:  INOUT  STD_LOGIC;    
	GTRIG:     INOUT  STD_LOGIC;    
	\lo*\:     INOUT  STD_LOGIC;    
	POSNEG:    IN     STD_LOGIC;    
	TRIG_OUTH: OUT    STD_LOGIC;    
	TRIG_OUTL: OUT    STD_LOGIC);
end fastcomp;
