-- generated by newgenasym Thu Oct 02 11:26:54 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fastcomp is
    port (    
	ANPULSEIN: IN     STD_LOGIC;    
	DGTH:      INOUT  STD_LOGIC;    
	DGTL:      INOUT  STD_LOGIC;    
	LOCKOUT:   INOUT  STD_LOGIC;    
	\lockout*\: INOUT  STD_LOGIC;    
	POSNEG:    IN     STD_LOGIC;    
	TRIG_OUTH: OUT    STD_LOGIC;    
	TRIG_OUTL: OUT    STD_LOGIC);
end fastcomp;
