-- generated by newgenasym Fri Oct 17 15:15:10 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fastcomp is
    port (    
	ANPULSEIN: IN     STD_LOGIC;    
	DGTH:      INOUT  STD_LOGIC;    
	GTRIG:     INOUT  STD_LOGIC;    
	\lockout*\: INOUT  STD_LOGIC;    
	POSNEG:    IN     STD_LOGIC;    
	TRIG_OUTH: OUT    STD_LOGIC;    
	TRIG_OUTL: OUT    STD_LOGIC);
end fastcomp;
