-- generated by newgenasym Tue Mar 29 12:00:12 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1n4000_l\ is
    port (    
	AN:        INOUT  STD_LOGIC;    
	CAT:       INOUT  STD_LOGIC);
end \1n4000_l\;
