// generated by newgenasym  Tue Mar 29 11:59:13 2011


module upf1765 (ca0, ca1, ca2, ca3, ca4, ca5, ca6, ca7, ca8, ca9, \casen* , cp,
        dtack, gnt, ma0, ma1, ma2, ma3, ma4, ma5, ma6, ma7, ma8, ma9, ra0,
        ra1, ra2, ra3, ra4, ra5, ra6, ra7, ra8, ra9, \ras* , rcp, \req1* ,
        \req2* , \sel1* , \sel2* , wg);
    input ca0;
    input ca1;
    input ca2;
    input ca3;
    input ca4;
    input ca5;
    input ca6;
    input ca7;
    input ca8;
    input ca9;
    output \casen* ;
    input cp;
    output dtack;
    output gnt;
    output ma0;
    output ma1;
    output ma2;
    output ma3;
    output ma4;
    output ma5;
    output ma6;
    output ma7;
    output ma8;
    output ma9;
    input ra0;
    input ra1;
    input ra2;
    input ra3;
    input ra4;
    input ra5;
    input ra6;
    input ra7;
    input ra8;
    input ra9;
    output \ras* ;
    input rcp;
    input \req1* ;
    input \req2* ;
    output \sel1* ;
    output \sel2* ;
    output wg;


    initial
        begin
        end

endmodule
