-- generated by newgenasym Tue Mar 29 11:59:13 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity UPF1765 is
    port (    
	CA0:       IN     STD_LOGIC;    
	CA1:       IN     STD_LOGIC;    
	CA2:       IN     STD_LOGIC;    
	CA3:       IN     STD_LOGIC;    
	CA4:       IN     STD_LOGIC;    
	CA5:       IN     STD_LOGIC;    
	CA6:       IN     STD_LOGIC;    
	CA7:       IN     STD_LOGIC;    
	CA8:       IN     STD_LOGIC;    
	CA9:       IN     STD_LOGIC;    
	\casen*\:  OUT    STD_LOGIC;    
	CP:        IN     STD_LOGIC;    
	DTACK:     OUT    STD_LOGIC;    
	GNT:       OUT    STD_LOGIC;    
	MA0:       OUT    STD_LOGIC;    
	MA1:       OUT    STD_LOGIC;    
	MA2:       OUT    STD_LOGIC;    
	MA3:       OUT    STD_LOGIC;    
	MA4:       OUT    STD_LOGIC;    
	MA5:       OUT    STD_LOGIC;    
	MA6:       OUT    STD_LOGIC;    
	MA7:       OUT    STD_LOGIC;    
	MA8:       OUT    STD_LOGIC;    
	MA9:       OUT    STD_LOGIC;    
	RA0:       IN     STD_LOGIC;    
	RA1:       IN     STD_LOGIC;    
	RA2:       IN     STD_LOGIC;    
	RA3:       IN     STD_LOGIC;    
	RA4:       IN     STD_LOGIC;    
	RA5:       IN     STD_LOGIC;    
	RA6:       IN     STD_LOGIC;    
	RA7:       IN     STD_LOGIC;    
	RA8:       IN     STD_LOGIC;    
	RA9:       IN     STD_LOGIC;    
	\ras*\:    OUT    STD_LOGIC;    
	RCP:       IN     STD_LOGIC;    
	\req1*\:   IN     STD_LOGIC;    
	\req2*\:   IN     STD_LOGIC;    
	\sel1*\:   OUT    STD_LOGIC;    
	\sel2*\:   OUT    STD_LOGIC;    
	WG:        OUT    STD_LOGIC);
end UPF1765;
