// generated by newgenasym  Tue Mar 29 12:00:16 2011


module ad9020 (\-vref , \-vsense , \analog#20in , \analog#20in2 , d, encode,
        \lsbs#20invert , midref, \msb#20invert , overflow, qrref, tqrref,
        vref, vsense);
    input \-vref ;
    input \-vsense ;
    input \analog#20in ;
    input \analog#20in2 ;
    output [9:0] d;
    input encode;
    input \lsbs#20invert ;
    input midref;
    input \msb#20invert ;
    output overflow;
    input qrref;
    input tqrref;
    input vref;
    input vsense;


    initial
        begin
        end

endmodule
