-- generated by newgenasym Tue Mar 29 12:00:16 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD9020 is
    port (    
	\-vref\:   IN     STD_LOGIC;    
	\-vsense\: IN     STD_LOGIC;    
	\analog in\: IN     STD_LOGIC;    
	\analog in2\: IN     STD_LOGIC;    
	D:         OUT    STD_LOGIC_VECTOR (9 DOWNTO 0);    
	ENCODE:    IN     STD_LOGIC;    
	\lsbs invert\: IN     STD_LOGIC;    
	MIDREF:    IN     STD_LOGIC;    
	\msb invert\: IN     STD_LOGIC;    
	OVERFLOW:  OUT    STD_LOGIC;    
	QRREF:     IN     STD_LOGIC;    
	TQRREF:    IN     STD_LOGIC;    
	VREF:      IN     STD_LOGIC;    
	VSENSE:    IN     STD_LOGIC);
end AD9020;
