// generated by newgenasym  Tue Mar 29 11:56:39 2011


module ad7575 (agnd, ain, \busy* , clk, \cs* , db0, db1, db2, db3, db4, db5, db6,
        db7, dgnd, \rd* , tp, vdd, vref);
    input agnd;
    inout ain;
    input \busy* ;
    input clk;
    input \cs* ;
    output db0;
    output db1;
    output db2;
    output db3;
    output db4;
    output db5;
    output db6;
    output db7;
    input dgnd;
    input \rd* ;
    input tp;
    input vdd;
    inout vref;


    initial
        begin
        end

endmodule
