-- generated by newgenasym Tue Mar 29 11:56:39 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD7575 is
    port (    
	AGND:      IN     STD_LOGIC;    
	AIN:       INOUT  STD_LOGIC;    
	\busy*\:   IN     STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	DB0:       OUT    STD_LOGIC;    
	DB1:       OUT    STD_LOGIC;    
	DB2:       OUT    STD_LOGIC;    
	DB3:       OUT    STD_LOGIC;    
	DB4:       OUT    STD_LOGIC;    
	DB5:       OUT    STD_LOGIC;    
	DB6:       OUT    STD_LOGIC;    
	DB7:       OUT    STD_LOGIC;    
	DGND:      IN     STD_LOGIC;    
	\rd*\:     IN     STD_LOGIC;    
	TP:        IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end AD7575;
