// generated by newgenasym  Tue Mar 29 11:59:52 2011


module hfbr_2316t (\analog#20signal , vcc, vee);
    input \analog#20signal ;
    input vcc;
    input vee;


    initial
        begin
        end

endmodule
