-- generated by newgenasym Tue Mar 29 11:59:52 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HFBR_2316T is
    port (    
	\analog signal\: IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end HFBR_2316T;
