`timescale 1ns/1ns

module asyncdelays (clk, \ddgt* , delay_val, dgth, dgtl, dgt_ttl, gtrigh, gtrigl, le_dgt );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:17 2015
// from tubii_lib/ASYNCDELAYS/sch_1

  inout  clk;
  inout  \ddgt* ;
  inout  delay_val;
  inout  dgth;
  inout  dgtl;
  inout  dgt_ttl;
  inout  gtrigh;
  inout  gtrigl;
  inout  le_dgt;
  // global signal glbl.gnd;
  // global signal glbl.vcc;

  wire  unnamed_1_10h125_i9_y;
  wire  unnamed_1_ds1023200_i31_q;
  wire  unnamed_1_ds1023500_i19_le;
  wire  unnamed_1_ds1023500_i19_out;
  wire  unnamed_1_mc10h124_i29_out;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;

// begin instances 

  \10h125  page1_i9  (.a(gtrigh),
	.\b* (gtrigl),
	.v(/* unconnected */),
	.y(unnamed_1_10h125_i9_y));
  defparam page1_i9.size = 1;

  ds1023500 page1_i19  (.\clk/p1 (clk),
	.\d/p2 (unnamed_1_ds1023200_i31_q),
	.in(unnamed_1_10h125_i9_y),
	.\le* (unnamed_1_ds1023500_i19_le),
	.ms(glbl.gnd),
	.out(unnamed_1_ds1023500_i19_out),
	.p3(/* unconnected */),
	.p4(/* unconnected */),
	.p5(/* unconnected */),
	.p6(/* unconnected */),
	.p7(/* unconnected */),
	.ps(glbl.vcc),
	.pwm(/* unconnected */),
	.\q/p0 (/* unconnected */));

  f06 page1_i22  (.a(le_dgt),
	.\y* (unnamed_1_ds1023500_i19_le),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i22.size = 1;

  testpoint_l page1_i24  (.a(unnamed_1_mc10h124_i29_out));

  led_pulse page1_i25  (.pulse_in(dgt_ttl));

  led_pulse page1_i26  (.pulse_in(unnamed_1_ds1023500_i19_out));

  rsmd0805 page1_i28  (.a(unnamed_1_ds1023500_i19_le),
	.b({glbl.vcc}));

  mc10h124 page1_i29  (.common(/* unconnected */),
	.in(unnamed_1_ds1023500_i19_out),
	.out(unnamed_1_mc10h124_i29_out),
	.\out* (\ddgt* ));

  mc10h124 page1_i30  (.common(/* unconnected */),
	.in(dgt_ttl),
	.out(dgth),
	.\out* (dgtl));

  ds1023200 page1_i31  (.\clk/p1 (clk),
	.\d/p2 (delay_val),
	.in(unnamed_1_10h125_i9_y),
	.\le* (unnamed_1_ds1023500_i19_le),
	.ms(glbl.gnd),
	.out(dgt_ttl),
	.p3(/* unconnected */),
	.p4(/* unconnected */),
	.p5(/* unconnected */),
	.p6(/* unconnected */),
	.p7(/* unconnected */),
	.ps(glbl.vcc),
	.pwm(/* unconnected */),
	.\q/p0 (unnamed_1_ds1023200_i31_q));

endmodule // asyncdelays(sch_1) 
