// generated by newgenasym  Wed Jun 08 19:13:05 2011


module block2 (clock_inh, clock_inl, pulse_inh, pulse_inl, pulse_outh,
        pulse_outl);
    input clock_inh;
    input clock_inl;
    input pulse_inh;
    input pulse_inl;
    output pulse_outh;
    output pulse_outl;


    initial
        begin
        end

endmodule
