-- generated by newgenasym Wed Jun 08 19:13:05 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity BLOCK2 is
    port (    
	CLOCK_INH: IN     STD_LOGIC;    
	CLOCK_INL: IN     STD_LOGIC;    
	PULSE_INH: IN     STD_LOGIC;    
	PULSE_INL: IN     STD_LOGIC;    
	PULSE_OUTH: OUT    STD_LOGIC;    
	PULSE_OUTL: OUT    STD_LOGIC);
end BLOCK2;
