// generated by newgenasym  Tue Mar 29 12:00:47 2011


module zpack_a (a, b, c, d, e);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;
    inout [size-1:0] c;
    inout [size-1:0] d;
    inout [size-1:0] e;


    initial
        begin
        end

endmodule
