`timescale 1ns/1ns

module generic_pulse (async_pulse_in, async_pulse_out, clk, data, le_async_pulse );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:23 2015
// from tubii_lib/GENERIC_PULSE/sch_1

  inout  async_pulse_in;
  inout  async_pulse_out;
  inout  clk;
  inout  data;
  inout  le_async_pulse;
  // global signal glbl.gnd;
  // global signal glbl.vcc;
  // global signal glbl.vcc5;
  // global signal glbl.vtt;

  wire  unnamed_1_ds102350_i15_le;
  wire  unnamed_1_ds102350_i15_out;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;
  wire  vcc5;
  wire  page1_vcc5;
  wire  vtt;
  wire  page1_vtt;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;
  assign vcc5 = glbl.vcc5;
  assign page1_vcc5 = vcc5;
  assign vtt = glbl.vtt;
  assign page1_vtt = vtt;

// begin instances 

  f06 page1_i14  (.a(le_async_pulse),
	.\y* (unnamed_1_ds102350_i15_le),
	.\y0* (/* unconnected */),
	.\y1* (/* unconnected */),
	.\y2* (/* unconnected */),
	.\y3* (/* unconnected */),
	.\y4* (/* unconnected */),
	.\y5* (/* unconnected */),
	.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */));
  defparam page1_i14.size = 1;

  ds102350 page1_i15  (.\clk/p1 (clk),
	.\d/p2 (data),
	.in(async_pulse_in),
	.\le* (unnamed_1_ds102350_i15_le),
	.ms(glbl.gnd),
	.out(unnamed_1_ds102350_i15_out),
	.p3(/* unconnected */),
	.p4(/* unconnected */),
	.p5(/* unconnected */),
	.p6(/* unconnected */),
	.p7(/* unconnected */),
	.ps(glbl.vcc5),
	.pwm(/* unconnected */),
	.\q/p0 (/* unconnected */));

  led_pulse page1_i16  (.pulse_in(unnamed_1_ds102350_i15_out));

  rsmd0805 page1_i17  (.a({glbl.vtt}),
	.b(async_pulse_out));

  rsmd0805 page1_i18  (.a(unnamed_1_ds102350_i15_le),
	.b({glbl.vcc}));

  mc10h124 page1_i19  (.common(glbl.vcc),
	.in(unnamed_1_ds102350_i15_out),
	.out(async_pulse_out),
	.\out* (/* unconnected */));

  csmd0603 page1_i20  (.a({glbl.gnd}),
	.b({glbl.vcc}));

endmodule // generic_pulse(sch_1) 
