-- generated by newgenasym Tue Mar 29 11:58:23 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MIC29373 is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	ERROR:     IN     STD_LOGIC;    
	GROUND:    INOUT  STD_LOGIC;    
	INPUT:     INOUT  STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC);
end MIC29373;
