// generated by newgenasym  Tue Mar 29 11:57:21 2011


module diosz (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
