`timescale 1ns/1ns

module microzedconnection (\100mhz_clk_in , async_delay_in, async_delay_out, async_pulse_out, caen_rdy, clk, clr_cnt, 
    cntrl_rdy, cntrl_register_chk, cnt_pulse, comp_rdy, data, dgt, exttrig, fox_200mhz_in, gtrig, latch_display, 
    load_enable, \lockout* , rawtrigs_in, smellie_delay_in, smellie_delay_out, smellie_pulse_out, 
    spkr, sync, sync24, sync_delay_in, sync_delay_out, sync_pulse_out, tellie_delay_in, tellie_delay_out, 
    tellie_pulse_out, tubiitime_data_rdy, tubii_rt_out, using_bckp );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:24 2015
// from tubii_lib/MICROZEDCONNECTION/sch_1

  inout  \100mhz_clk_in ;
  inout  async_delay_in;
  inout  async_delay_out;
  inout  async_pulse_out;
  inout  caen_rdy;
  inout  clk;
  inout  clr_cnt;
  inout  cntrl_rdy;
  inout  cntrl_register_chk;
  inout  cnt_pulse;
  inout  comp_rdy;
  inout  data;
  inout  dgt;
  inout [15:0] exttrig;
  inout  fox_200mhz_in;
  inout  gtrig;
  inout  latch_display;
  inout [2:0] load_enable;
  inout  \lockout* ;
  inout [3:0] rawtrigs_in;
  inout  smellie_delay_in;
  inout  smellie_delay_out;
  inout  smellie_pulse_out;
  inout  spkr;
  inout  sync;
  inout  sync24;
  inout  sync_delay_in;
  inout  sync_delay_out;
  inout  sync_pulse_out;
  inout  tellie_delay_in;
  inout  tellie_delay_out;
  inout  tellie_pulse_out;
  inout  tubiitime_data_rdy;
  inout  tubii_rt_out;
  inout  using_bckp;
  // global signal glbl.gnd;
  // global signal glbl.vcc;
  // global signal glbl.vcc5;
  // global signal glbl.vcci0_35;
  // global signal glbl.vp3_3;

  wire  bank13_lvds_2_n;
  wire  bank13_lvds_2_p;
  wire  bank13_lvds_3_n;
  wire  bank13_lvds_3_p;
  wire  bank13_lvds_6_p;
  wire  bank_0l10;
  wire  bank_0_k9;
  wire  bank_0_m10;
  wire  bank_0_m9;
  wire  \carrier_srst# ;
  wire  fpga_done;
  wire  gpio0;
  wire  gpio1;
  wire  gpio2;
  wire  gpio3;
  wire  gpio4;
  wire  gpio5;
  wire  i2c_scl;
  wire  i2c_sda;
  wire  \init# ;
  wire  jtag_tck;
  wire  jtag_tdi;
  wire  jtag_tdo;
  wire  jtag_tms;
  wire  jx1_guide_pin1;
  wire  jx1_guide_pin2;
  wire  jx1_se_0;
  wire  jx1_se_1;
  wire  jx2_guide_pin1;
  wire  jx2_guide_pin2;
  wire  jx2_se_0;
  wire  jx2_se_1;
  wire  pulse_out;
  wire  pwr_en;
  wire  pwr_good;
  wire  timingclockin;
  wire  timingcommandin;
  wire  timingsyncechoout;
  wire  timingsyncin;
  wire  vbat;
  wire  vccio_en_o;
  wire [5:5] bank13_lvds_n;
  wire [5:5] bank13_lvds_p;
  wire [23:1] jx1_lvds_n;
  wire [23:7] jx1_lvds_p;
  wire [23:22] jx2_lvds_n;
  wire [23:22] jx2_lvds_p;
  wire [2:0] nim_trig_in;
  wire [0:0] nim_trig_out;

  wire  gnd;
  wire  page3_gnd;
  wire  vcc;
  wire  page3_vcc;
  wire  vcc5;
  wire  page3_vcc5;
  wire  vcci0_35;
  wire  page3_vcci0_35;
  wire  vp3_3;
  wire  page3_vp3_3;

  assign gnd = glbl.gnd;
  assign page3_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page3_vcc = vcc;
  assign vcc5 = glbl.vcc5;
  assign page3_vcc5 = vcc5;
  assign vcci0_35 = glbl.vcci0_35;
  assign page3_vcci0_35 = vcci0_35;
  assign vp3_3 = glbl.vp3_3;
  assign page3_vp3_3 = vp3_3;

// begin instances 

  \fci_61083-101400lf  page3_i8  (.\1 (jtag_tck),
	.\2 (jtag_tms),
	.\3 (jtag_tdo),
	.\4 (jtag_tdi),
	.\5 (pwr_en),
	.\6 (\carrier_srst# ),
	.\7 (vbat),
	.\8 (fpga_done),
	.\9 (jx1_se_0),
	.\10 (jx1_se_1),
	.\11 (gtrig),
	.\12 (sync24),
	.\13 (sync),
	.\14 (jx1_lvds_n[1]),
	.\15 (glbl.gnd),
	.\16 (glbl.gnd),
	.\17 (load_enable[0]),
	.\18 (load_enable[2]),
	.\19 (load_enable[1]),
	.\20 (jx1_lvds_n[5]),
	.\21 (glbl.gnd),
	.\22 (glbl.gnd),
	.\23 (data),
	.\24 (clr_cnt),
	.\25 (clk),
	.\26 (latch_display),
	.\27 (glbl.gnd),
	.\28 (glbl.gnd),
	.\29 (cnt_pulse),
	.\30 (jx1_lvds_p[7]),
	.\31 (jx1_lvds_n[6]),
	.\32 (jx1_lvds_n[7]),
	.\33 (glbl.gnd),
	.\34 (glbl.gnd),
	.\35 (jx1_lvds_p[8]),
	.\36 (jx1_lvds_p[9]),
	.\37 (jx1_lvds_n[8]),
	.\38 (jx1_lvds_n[9]),
	.\39 (glbl.gnd),
	.\40 (glbl.gnd),
	.\41 (jx1_lvds_p[10]),
	.\42 (jx1_lvds_p[11]),
	.\43 (jx1_lvds_n[10]),
	.\44 (jx1_lvds_n[11]),
	.\45 (glbl.gnd),
	.\46 (glbl.gnd),
	.\47 (jx1_lvds_p[12]),
	.\48 (jx1_lvds_p[13]),
	.\49 (jx1_lvds_n[12]),
	.\50 (jx1_lvds_n[13]),
	.\51 (glbl.gnd),
	.\52 (glbl.gnd),
	.\53 (jx1_lvds_p[14]),
	.\54 (jx1_lvds_p[15]),
	.\55 (jx1_lvds_n[14]),
	.\56 (jx1_lvds_n[15]),
	.\57 (glbl.vcc),
	.\58 (glbl.vcc),
	.\59 (glbl.vcc),
	.\60 (glbl.vcc),
	.\61 (jx1_lvds_p[16]),
	.\62 (jx1_lvds_p[17]),
	.\63 (jx1_lvds_n[16]),
	.\64 (jx1_lvds_n[17]),
	.\65 (glbl.gnd),
	.\66 (glbl.gnd),
	.\67 (jx1_lvds_p[18]),
	.\68 (jx1_lvds_p[19]),
	.\69 (jx1_lvds_n[18]),
	.\70 (jx1_lvds_n[19]),
	.\71 (glbl.gnd),
	.\72 (glbl.gnd),
	.\73 (jx1_lvds_p[20]),
	.\74 (jx1_lvds_p[21]),
	.\75 (jx1_lvds_n[20]),
	.\76 (jx1_lvds_n[21]),
	.\77 (glbl.gnd),
	.\78 (glbl.vp3_3),
	.\79 (glbl.vp3_3),
	.\80 (glbl.vp3_3),
	.\81 (jx1_lvds_p[22]),
	.\82 (jx1_lvds_p[23]),
	.\83 (jx1_lvds_n[22]),
	.\84 (jx1_lvds_n[23]),
	.\85 (glbl.gnd),
	.\86 (glbl.gnd),
	.\87 (timingsyncin),
	.\88 (timingclockin),
	.\89 (timingcommandin),
	.\90 (timingsyncechoout),
	.\91 (bank13_lvds_2_p),
	.\92 (bank13_lvds_3_p),
	.\93 (bank13_lvds_2_n),
	.\94 (bank13_lvds_3_n),
	.\95 (glbl.gnd),
	.\96 (glbl.gnd),
	.\97 (bank_0l10),
	.\98 (bank_0_m9),
	.\99 (bank_0_k9),
	.\100 (bank_0_m10),
	.\101 (jx1_guide_pin2),
	.\102 (jx1_guide_pin1));

  \fci_61083-101400lf  page3_i9  (.\1 (i2c_scl),
	.\2 (i2c_sda),
	.\3 (gpio0),
	.\4 (gpio1),
	.\5 (gpio2),
	.\6 (gpio3),
	.\7 (gpio4),
	.\8 (gpio5),
	.\9 (\init# ),
	.\10 (vccio_en_o),
	.\11 (pwr_good),
	.\12 (glbl.vcc),
	.\13 (jx2_se_0),
	.\14 (jx2_se_1),
	.\15 (glbl.gnd),
	.\16 (glbl.gnd),
	.\17 (using_bckp),
	.\18 (\100mhz_clk_in ),
	.\19 (tubiitime_data_rdy),
	.\20 (fox_200mhz_in),
	.\21 (glbl.gnd),
	.\22 (glbl.gnd),
	.\23 (tellie_pulse_out),
	.\24 (tellie_delay_in),
	.\25 (smellie_pulse_out),
	.\26 (tellie_delay_out),
	.\27 (glbl.gnd),
	.\28 (glbl.gnd),
	.\29 (smellie_delay_in),
	.\30 (async_delay_in),
	.\31 (smellie_delay_out),
	.\32 (async_delay_out),
	.\33 (glbl.gnd),
	.\34 (glbl.gnd),
	.\35 (sync_delay_in),
	.\36 (async_pulse_out),
	.\37 (sync_delay_out),
	.\38 (sync_pulse_out),
	.\39 (glbl.gnd),
	.\40 (glbl.gnd),
	.\41 (rawtrigs_in[0]),
	.\42 (rawtrigs_in[2]),
	.\43 (rawtrigs_in[1]),
	.\44 (rawtrigs_in[3]),
	.\45 (glbl.gnd),
	.\46 (glbl.gnd),
	.\47 (tubii_rt_out),
	.\48 (spkr),
	.\49 (comp_rdy),
	.\50 (cntrl_register_chk),
	.\51 (glbl.gnd),
	.\52 (glbl.gnd),
	.\53 (cntrl_rdy),
	.\54 (\lockout* ),
	.\55 (caen_rdy),
	.\56 (dgt),
	.\57 (glbl.vcc),
	.\58 (glbl.vcc),
	.\59 (glbl.vcc),
	.\60 (glbl.vcc),
	.\61 (exttrig[0]),
	.\62 (exttrig[8]),
	.\63 (exttrig[1]),
	.\64 (exttrig[9]),
	.\65 (glbl.gnd),
	.\66 (glbl.gnd),
	.\67 (exttrig[2]),
	.\68 (exttrig[10]),
	.\69 (exttrig[3]),
	.\70 (exttrig[11]),
	.\71 (glbl.gnd),
	.\72 (glbl.gnd),
	.\73 (exttrig[4]),
	.\74 (exttrig[12]),
	.\75 (exttrig[5]),
	.\76 (exttrig[13]),
	.\77 (glbl.gnd),
	.\78 (glbl.vp3_3),
	.\79 (glbl.vp3_3),
	.\80 (glbl.vp3_3),
	.\81 (exttrig[6]),
	.\82 (exttrig[14]),
	.\83 (exttrig[7]),
	.\84 (exttrig[15]),
	.\85 (glbl.gnd),
	.\86 (glbl.gnd),
	.\87 (jx2_lvds_p[22]),
	.\88 (jx2_lvds_p[23]),
	.\89 (jx2_lvds_n[22]),
	.\90 (jx2_lvds_n[23]),
	.\91 (glbl.gnd),
	.\92 (glbl.gnd),
	.\93 (nim_trig_in[0]),
	.\94 (bank13_lvds_p[5]),
	.\95 (nim_trig_in[2]),
	.\96 (bank13_lvds_n[5]),
	.\97 (bank13_lvds_6_p),
	.\98 (glbl.vcci0_35),
	.\99 (nim_trig_out[0]),
	.\100 (pulse_out),
	.\101 (jx2_guide_pin2),
	.\102 (jx2_guide_pin1));

  testpoint_l page3_i35  (.a(glbl.gnd));

  testpoint_l page3_i36  (.a(glbl.gnd));

  testpoint_l page3_i37  (.a(glbl.gnd));

  testpoint_l page3_i38  (.a(glbl.gnd));

  csmd0805 page3_i39  (.a({glbl.gnd}),
	.b({glbl.vcc5}));

  csmd0805 page3_i40  (.a({glbl.gnd}),
	.b({glbl.vcc5}));

  csmd0805 page3_i41  (.a({glbl.gnd}),
	.b({glbl.vcc5}));

  csmd0805 page3_i42  (.a({glbl.gnd}),
	.b({glbl.vcc5}));

endmodule // microzedconnection(sch_1) 
