// generated by newgenasym  Tue Mar 29 12:46:31 2011


module tub_ledfanout (led1, led2, led3, led4, led5, led6, led7, led8, ped_ttl);
    output led1;
    output led2;
    output led3;
    output led4;
    output led5;
    output led6;
    output led7;
    output led8;
    input ped_ttl;


    initial
        begin
        end

endmodule
