// generated by newgenasym  Tue Mar 29 11:58:53 2011


module snodisc2 (discrn1, discrn2, discrn3, discrn4, discrp1, discrp2,
        discrp3, discrp4, gnda1, gnda2, gnda3, gnda4, gndd1, gndd2,
        gndd3, gndd4, gndd5, gndd6, ina1, ina2, ina3, ina4, inb1, inb2,
        inb3, inb4, outqhi1, outqhi2, outqhi3, outqhi4, outqlo1,
        outqlo2, outqlo3, outqlo4, pedn, pedp, pen1, pen2, pen3, pen4,
        qhiref1, qhiref2, qhiref3, qhiref4, qloref1, qloref2,
        qloref3, qloref4, resrf, rmpc1, rmpc2, sampn1, sampn2,
        sampn3, sampn4, sampp1, sampp2, sampp3, sampp4, suba1, suba2,
        subd1, subd2, vcca1, vcca2, vcca3, vccd, vchd1, vchd2, vdmp,
        veea, veed1, veed2, vli, vres, vsi, vth1, vth2, vth3, vth4);
    inout discrn1;
    inout discrn2;
    inout discrn3;
    inout discrn4;
    inout discrp1;
    inout discrp2;
    inout discrp3;
    inout discrp4;
    input gnda1;
    input gnda2;
    input gnda3;
    input gnda4;
    input gndd1;
    input gndd2;
    input gndd3;
    input gndd4;
    input gndd5;
    input gndd6;
    inout ina1;
    inout ina2;
    inout ina3;
    inout ina4;
    inout inb1;
    inout inb2;
    inout inb3;
    inout inb4;
    inout outqhi1;
    inout outqhi2;
    inout outqhi3;
    inout outqhi4;
    inout outqlo1;
    inout outqlo2;
    inout outqlo3;
    inout outqlo4;
    inout pedn;
    inout pedp;
    inout pen1;
    inout pen2;
    inout pen3;
    inout pen4;
    inout qhiref1;
    inout qhiref2;
    inout qhiref3;
    inout qhiref4;
    inout qloref1;
    inout qloref2;
    inout qloref3;
    inout qloref4;
    inout resrf;
    inout rmpc1;
    inout rmpc2;
    inout sampn1;
    inout sampn2;
    inout sampn3;
    inout sampn4;
    inout sampp1;
    inout sampp2;
    inout sampp3;
    inout sampp4;
    input suba1;
    input suba2;
    input subd1;
    input subd2;
    input vcca1;
    input vcca2;
    input vcca3;
    input vccd;
    input vchd1;
    input vchd2;
    input vdmp;
    input veea;
    input veed1;
    input veed2;
    inout vli;
    inout vres;
    inout vsi;
    inout vth1;
    inout vth2;
    inout vth3;
    inout vth4;


    initial
        begin
        end

endmodule
