-- generated by newgenasym Tue Mar 29 12:00:13 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD781 is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	S_H:       IN     STD_LOGIC);
end AD781;
