-- generated by newgenasym Tue Mar 29 12:00:11 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h600\ is
    generic (
        size:positive:= 1
            );
    port (    
	D:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	ENECL:     IN     STD_LOGIC;    
	ENTTL:     IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \10h600\;
