// generated by newgenasym  Tue Mar 29 11:58:50 2011


module snocmos7 (a0, a1, a2, a3, a4, \clr* , \csel* , d0, d1, d2, d3, d4, d5, d6, d7,
        davail, discrn, discrp, extgt, full, gnda1, gnda2, gnda3,
        gnda4, gnda5, gndcore1, gndcore2, gndcore3, gndcore4,
        gndcore5, gndcore6, gndguard, gndring1, gndring2, \gtrig* ,
        gtsel, gtvalid, iseta0, iseta1, isetm0, isetm1, lgisel, mode,
        outqhl, outqhs, outqll, outtac, qhi, qlo, rdstr, sampn, sampp,
        scin, scout, serclock, serdatin, serdatout, set, shift,
        spareclear, sparecount, store, \synclr* , tacref, tr100_out,
        tr20_out, triset, triset100, vdda1, vdda2, vdda3, vddcore1,
        vddcore2, vddcore3, vddcore4, vddcore5, vddguard, vddring1,
        vddring2, vmax);
    input a0;
    input a1;
    input a2;
    input a3;
    input a4;
    input \clr* ;
    input \csel* ;
    output d0;
    output d1;
    output d2;
    output d3;
    output d4;
    output d5;
    output d6;
    output d7;
    output davail;
    input discrn;
    input discrp;
    inout extgt;
    output full;
    input gnda1;
    input gnda2;
    input gnda3;
    input gnda4;
    input gnda5;
    input gndcore1;
    input gndcore2;
    input gndcore3;
    input gndcore4;
    input gndcore5;
    input gndcore6;
    input gndguard;
    input gndring1;
    input gndring2;
    input \gtrig* ;
    input gtsel;
    output gtvalid;
    inout iseta0;
    inout iseta1;
    inout isetm0;
    inout isetm1;
    input lgisel;
    inout mode;
    output outqhl;
    output outqhs;
    output outqll;
    output outtac;
    input qhi;
    input qlo;
    input rdstr;
    input sampn;
    input sampp;
    inout scin;
    inout scout;
    input serclock;
    input serdatin;
    output serdatout;
    input set;
    inout shift;
    inout spareclear;
    inout sparecount;
    input store;
    input \synclr* ;
    inout tacref;
    inout tr100_out;
    output tr20_out;
    input triset;
    inout triset100;
    input vdda1;
    input vdda2;
    input vdda3;
    input vddcore1;
    input vddcore2;
    input vddcore3;
    input vddcore4;
    input vddcore5;
    input vddguard;
    input vddring1;
    input vddring2;
    input vmax;


    initial
        begin
        end

endmodule
