// generated by newgenasym  Tue Sep 02 17:13:18 2014


module asyncdelaybig (clk, delay_val, delpulse_out, le_ttl, ttlpulse_in);
    input clk;
    input delay_val;
    output delpulse_out;
    input le_ttl;
    input ttlpulse_in;


    initial
        begin
        end

endmodule
