-- generated by newgenasym Tue Sep 02 17:13:18 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity asyncdelaybig is
    port (    
	CLK:       IN     STD_LOGIC;    
	DELAY_VAL: IN     STD_LOGIC;    
	DELPULSE_OUT: OUT    STD_LOGIC;    
	LE_TTL:    IN     STD_LOGIC;    
	TTLPULSE_IN: IN     STD_LOGIC);
end asyncdelaybig;
