// generated by newgenasym  Wed Oct 01 14:39:17 2014


module \ttl-ecl  (ecl_out_bnc, ecl_out_smb, ttl_in);
    output ecl_out_bnc;
    output ecl_out_smb;
    input ttl_in;


    initial
        begin
        end

endmodule
