-- generated by newgenasym Wed Oct 01 14:39:17 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ttl-ecl\ is
    port (    
	ECL_OUT_BNC: OUT    STD_LOGIC;    
	ECL_OUT_SMB: OUT    STD_LOGIC;    
	TTL_IN:    IN     STD_LOGIC);
end \ttl-ecl\;
