-- generated by newgenasym Tue Oct 14 18:35:27 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ttl-ecl\ is
    port (    
	ECL_OUT:   OUT    STD_LOGIC;    
	TTL_IN:    IN     STD_LOGIC);
end \ttl-ecl\;
