-- generated by newgenasym Tue Mar 29 12:46:31 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TUB_LEDFANOUT is
    port (    
	LED1:      OUT    STD_LOGIC;    
	LED2:      OUT    STD_LOGIC;    
	LED3:      OUT    STD_LOGIC;    
	LED4:      OUT    STD_LOGIC;    
	LED5:      OUT    STD_LOGIC;    
	LED6:      OUT    STD_LOGIC;    
	LED7:      OUT    STD_LOGIC;    
	LED8:      OUT    STD_LOGIC;    
	PED_TTL:   IN     STD_LOGIC);
end TUB_LEDFANOUT;
