// generated by newgenasym  Tue Mar 29 11:57:17 2011


module conn90_jack (jack, pin1, pin10, pin11, pin12, pin13, pin14, pin15, pin16,
        pin17, pin18, pin19, pin2, pin20, pin21, pin22, pin23, pin24,
        pin25, pin26, pin27, pin28, pin29, pin3, pin30, pin31, pin32,
        pin33, pin34, pin35, pin36, pin37, pin38, pin39, pin4, pin40,
        pin41, pin42, pin43, pin44, pin45, pin46, pin47, pin48, pin49,
        pin5, pin50, pin51, pin52, pin53, pin54, pin55, pin56, pin57,
        pin58, pin59, pin6, pin60, pin61, pin62, pin63, pin64, pin65,
        pin66, pin67, pin68, pin69, pin7, pin70, pin71, pin72, pin73,
        pin74, pin75, pin76, pin77, pin78, pin79, pin8, pin80, pin81,
        pin82, pin83, pin84, pin85, pin86, pin87, pin88, pin89, pin9,
        pin90);
    inout [90:1] jack;
    inout pin1;
    inout pin10;
    inout pin11;
    inout pin12;
    inout pin13;
    inout pin14;
    inout pin15;
    inout pin16;
    inout pin17;
    inout pin18;
    inout pin19;
    inout pin2;
    inout pin20;
    inout pin21;
    inout pin22;
    inout pin23;
    inout pin24;
    inout pin25;
    inout pin26;
    inout pin27;
    inout pin28;
    inout pin29;
    inout pin3;
    inout pin30;
    inout pin31;
    inout pin32;
    inout pin33;
    inout pin34;
    inout pin35;
    inout pin36;
    inout pin37;
    inout pin38;
    inout pin39;
    inout pin4;
    inout pin40;
    inout pin41;
    inout pin42;
    inout pin43;
    inout pin44;
    inout pin45;
    inout pin46;
    inout pin47;
    inout pin48;
    inout pin49;
    inout pin5;
    inout pin50;
    inout pin51;
    inout pin52;
    inout pin53;
    inout pin54;
    inout pin55;
    inout pin56;
    inout pin57;
    inout pin58;
    inout pin59;
    inout pin6;
    inout pin60;
    inout pin61;
    inout pin62;
    inout pin63;
    inout pin64;
    inout pin65;
    inout pin66;
    inout pin67;
    inout pin68;
    inout pin69;
    inout pin7;
    inout pin70;
    inout pin71;
    inout pin72;
    inout pin73;
    inout pin74;
    inout pin75;
    inout pin76;
    inout pin77;
    inout pin78;
    inout pin79;
    inout pin8;
    inout pin80;
    inout pin81;
    inout pin82;
    inout pin83;
    inout pin84;
    inout pin85;
    inout pin86;
    inout pin87;
    inout pin88;
    inout pin89;
    inout pin9;
    inout pin90;


    initial
        begin
        end

endmodule
