// generated by newgenasym  Wed Jul 06 18:02:12 2011


module \ttl-to-ecl-in  (bd, bd_ecl, trans_ie, trans_oe);
    input [7:0] bd;
    output [7:0] bd_ecl;
    input trans_ie;
    input trans_oe;


    initial
        begin
        end

endmodule
