-- generated by newgenasym Wed Jul 06 18:02:12 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ttl-to-ecl-in\ is
    port (    
	BD:        IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	BD_ECL:    OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	TRANS_IE:  IN     STD_LOGIC;    
	TRANS_OE:  IN     STD_LOGIC);
end \ttl-to-ecl-in\;
