// generated by newgenasym  Tue Mar 29 11:56:44 2011


module ad_amp02_l (inn, inp, out, ref, rg1, rg2, sense, v15n, v15p);
    input inn;
    input inp;
    output out;
    output ref;
    input rg1;
    input rg2;
    output sense;
    input v15n;
    input v15p;


    initial
        begin
        end

endmodule
