-- generated by newgenasym Tue Mar 29 11:56:44 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD_AMP02_L is
    port (    
	INN:       IN     STD_LOGIC;    
	INP:       IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	REF:       OUT    STD_LOGIC;    
	RG1:       IN     STD_LOGIC;    
	RG2:       IN     STD_LOGIC;    
	SENSE:     OUT    STD_LOGIC;    
	V15N:      IN     STD_LOGIC;    
	V15P:      IN     STD_LOGIC);
end AD_AMP02_L;
