// generated by newgenasym  Tue Mar 29 12:46:29 2011


module tub_disc (\lockout* , neg_in, pos_in, trig_out);
    input \lockout* ;
    input neg_in;
    input pos_in;
    output trig_out;


    initial
        begin
        end

endmodule
