-- generated by newgenasym Tue Mar 29 12:46:29 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TUB_DISC is
    port (    
	\lockout*\: IN     STD_LOGIC;    
	NEG_IN:    IN     STD_LOGIC;    
	POS_IN:    IN     STD_LOGIC;    
	TRIG_OUT:  OUT    STD_LOGIC);
end TUB_DISC;
