// generated by newgenasym  Thu Oct 02 11:58:17 2014


module generic_pulse (async_pulse_in, async_pulse_out, clk, data,
        le_async_pulse);
    input async_pulse_in;
    output async_pulse_out;
    input clk;
    input data;
    input le_async_pulse;


    initial
        begin
        end

endmodule
