-- generated by newgenasym Thu Oct 02 11:58:17 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity generic_pulse is
    port (    
	ASYNC_PULSE_IN: IN     STD_LOGIC;    
	ASYNC_PULSE_OUT: OUT    STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	DATA:      IN     STD_LOGIC;    
	LE_ASYNC_PULSE: IN     STD_LOGIC);
end generic_pulse;
