// generated by newgenasym  Wed Oct 01 14:39:05 2014


module \ecl-ttl  (ecl_in_bnc, ecl_in_smb, ttl_out);
    input ecl_in_bnc;
    input ecl_in_smb;
    output ttl_out;


    initial
        begin
        end

endmodule
