-- generated by newgenasym Tue Oct 14 18:11:56 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ecl-ttl\ is
    port (    
	ECL_IN:    IN     STD_LOGIC;    
	TTL_OUT:   OUT    STD_LOGIC);
end \ecl-ttl\;
