// generated by newgenasym  Wed Sep 10 16:19:06 2014


module async_pulse_gen (clk, data, le_a, le_b, oe, pulse_out);
    input clk;
    input data;
    input le_a;
    input le_b;
    input oe;
    output pulse_out;


    initial
        begin
        end

endmodule
