`timescale 1ns/1ns

module led_pulse (pulse_in );
// generated by  HDL Direct 16.6-p001 (v16-6-112A) 9/10/2012
// on Mon Jan 19 19:23:23 2015
// from tubii_lib/LED_PULSE/sch_1

  inout  pulse_in;
  // global signal glbl.gnd;
  // global signal glbl.vcc;

  wire  unnamed_1_csmd0805_i2_b;
  wire  unnamed_1_hct123_i5_q;
  wire  unnamed_1_ledl_i10_a;

  wire  gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page1_vcc;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  rsmd0805 page1_i1  (.a(unnamed_1_csmd0805_i2_b),
	.b({glbl.vcc}));

  csmd0805 page1_i2  (.a({glbl.gnd}),
	.b(unnamed_1_csmd0805_i2_b));

  hct123 page1_i5  (.c(glbl.gnd),
	.\c/r (unnamed_1_csmd0805_i2_b),
	.\cl* (glbl.vcc),
	.clock(pulse_in),
	.\clock* (glbl.gnd),
	.q(unnamed_1_hct123_i5_q),
	.\q* (/* unconnected */));

  rsmd0805 page1_i6  (.a(unnamed_1_ledl_i10_a),
	.b(unnamed_1_hct123_i5_q));

  led_l page1_i10  (.a(unnamed_1_ledl_i10_a),
	.b(glbl.gnd));

  csmd0603 page1_i12  (.a({glbl.gnd}),
	.b({glbl.vcc}));

endmodule // led_pulse(sch_1) 
