// generated by newgenasym  Wed Oct 01 14:01:54 2014


module \10h116  (a, \b* , v, y, \y* );
    parameter    section = 2;
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] \b* ;
    output v;
    output [size-1:0] y;
    output [size-1:0] \y* ;


    initial
        begin
        end

endmodule
