// generated by newgenasym  Tue Mar 29 11:59:21 2011


module xc1736 (\ce* , \ceo* , clk, d, \rsoe* );
    input \ce* ;
    output \ceo* ;
    input clk;
    output d;
    input \rsoe* ;


    initial
        begin
        end

endmodule
