// generated by newgenasym  Tue Mar 29 11:59:17 2011


module upftc16245 (a, \eo1* , \eo2* , \eo3* , \eo4* , y);
    input [15:0] a;
    input \eo1* ;
    input \eo2* ;
    output \eo3* ;
    output \eo4* ;
    output [15:0] y;


    initial
        begin
        end

endmodule
