-- generated by newgenasym Tue Mar 29 11:58:37 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RELAYSZ is
    generic (
        size:positive:= 1
            );
    port (    
	S1:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S2:        IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	VIN:       INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	VOUT:      INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end RELAYSZ;
