// generated by newgenasym  Thu Oct 09 12:00:25 2014


module caen_ports (caen_anpulse, caen_out, sync24h_lvds, sync24l_lvds,
        synch_lvds, syncl_lvds);
    output [11:0] caen_anpulse;
    input [7:0] caen_out;
    input sync24h_lvds;
    input sync24l_lvds;
    input synch_lvds;
    input syncl_lvds;


    initial
        begin
        end

endmodule
