// generated by newgenasym  Wed Feb 25 10:36:05 2015


module caen_ports (caen_anpulse, caen_out, sync24_lvds_n, sync24_lvds_p,
        sync_lvds_n, sync_lvds_p);
    output [11:0] caen_anpulse;
    input [7:0] caen_out;
    input sync24_lvds_n;
    input sync24_lvds_p;
    input sync_lvds_n;
    input sync_lvds_p;


    initial
        begin
        end

endmodule
