-- generated by newgenasym Wed Feb 25 10:36:05 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_ports is
    port (    
	CAEN_ANPULSE: OUT    STD_LOGIC_VECTOR (11 DOWNTO 0);    
	CAEN_OUT:  IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	SYNC24_LVDS_N: IN     STD_LOGIC;    
	SYNC24_LVDS_P: IN     STD_LOGIC;    
	SYNC_LVDS_N: IN     STD_LOGIC;    
	SYNC_LVDS_P: IN     STD_LOGIC);
end caen_ports;
