-- generated by newgenasym Thu Oct 09 10:31:02 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity caen_ports is
    port (    
	CAEN_OUT:  IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	SYNC24H_LVDS: IN     STD_LOGIC;    
	SYNC24L_LVDS: IN     STD_LOGIC;    
	SYNCH_LVDS: IN     STD_LOGIC;    
	SYNCL_LVDS: IN     STD_LOGIC);
end caen_ports;
