// generated by newgenasym  Fri Oct 03 15:54:41 2014


module ellie (smellie_delay_in, smellie_delay_out, smellie_pulse_out,
        tellie_delay_in, tellie_delay_out, tellie_pulse_out);
    output smellie_delay_in;
    output smellie_delay_out;
    output smellie_pulse_out;
    input tellie_delay_in;
    input tellie_delay_out;
    input tellie_pulse_out;


    initial
        begin
        end

endmodule
