-- generated by newgenasym Fri Oct 03 15:54:41 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ellie is
    port (    
	SMELLIE_DELAY_IN: OUT    STD_LOGIC;    
	SMELLIE_DELAY_OUT: OUT    STD_LOGIC;    
	SMELLIE_PULSE_OUT: OUT    STD_LOGIC;    
	TELLIE_DELAY_IN: IN     STD_LOGIC;    
	TELLIE_DELAY_OUT: IN     STD_LOGIC;    
	TELLIE_PULSE_OUT: IN     STD_LOGIC);
end ellie;
