-- generated by newgenasym Tue Mar 29 11:59:10 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TP_PAD_LS is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end TP_PAD_LS;
