// generated by newgenasym  Wed Sep 24 11:53:55 2014


module tubii_time (bckp_clk, clk100_outh, clk100_outl, data, data_rdy,
        default_clk, le, missedclock, sr_clk);
    input bckp_clk;
    output clk100_outh;
    output clk100_outl;
    input data;
    input data_rdy;
    input default_clk;
    input le;
    output missedclock;
    input sr_clk;


    initial
        begin
        end

endmodule
