// generated by newgenasym  Tue Feb 03 15:03:20 2015


module tubii_time (bckp_clk, clk100_outh, clk100_outl, clock100_out_ttl,
        data, data_rdy, default_clk, le, missedclock, sr_clk);
    input bckp_clk;
    output clk100_outh;
    output clk100_outl;
    output clock100_out_ttl;
    input data;
    input data_rdy;
    input default_clk;
    input le;
    output missedclock;
    input sr_clk;


    initial
        begin
        end

endmodule
