// generated by newgenasym  Wed Feb 25 16:09:49 2015


module tubii_time (bckp_clk, clk100_out_n, clk100_out_p, clock100_out_ttl,
        data, data_rdy, default_clk, le, missedclock, sr_clk);
    input bckp_clk;
    output clk100_out_n;
    output clk100_out_p;
    output clock100_out_ttl;
    input data;
    input data_rdy;
    input default_clk;
    input le;
    output missedclock;
    input sr_clk;


    initial
        begin
        end

endmodule
