// generated by newgenasym  Tue Mar 29 11:59:25 2011


module \10e016  (\ce* , clk, mr, p, \pe* , q, \tc* , tcld);
    input \ce* ;
    input clk;
    input mr;
    input [7:0] p;
    input \pe* ;
    output [7:0] q;
    output \tc* ;
    input tcld;


    initial
        begin
        end

endmodule
