-- generated by newgenasym Tue Mar 29 11:59:25 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10e016\ is
    port (    
	\ce*\:     IN     STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	MR:        IN     STD_LOGIC;    
	P:         IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\pe*\:     IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\tc*\:     OUT    STD_LOGIC;    
	TCLD:      IN     STD_LOGIC);
end \10e016\;
