-- generated by newgenasym Tue Mar 29 11:58:29 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MMBTH10_L is
    port (    
	B:         IN     STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end MMBTH10_L;
