// generated by newgenasym  Tue Mar 29 11:56:41 2011


module ad827 (in1_n, in1_p, in2_n, in2_p, out1, out2, v15_n, v15_p);
    inout in1_n;
    inout in1_p;
    inout in2_n;
    inout in2_p;
    inout out1;
    inout out2;
    inout v15_n;
    inout v15_p;


    initial
        begin
        end

endmodule
