-- generated by newgenasym Tue Mar 29 12:00:47 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ZPACK_A is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	C:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	D:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	E:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end ZPACK_A;
